select 
q.empresa,
q.cadcl,
q.cnpj,
q.fantasia,
q.razaosocial,
q.situacao,
q.endereco,
q.numero,
q.bairro,
q.codigo_cidade,
q.cidade,
q.estado,
q.datasituacao,
q.datainstalacao,
q.dataultimoreajuste,
q.vendedor,
q.classificacao,
q.representante,
q.representante2,
q.representante3,
q.contato,
q.telefone,
q.valor,
q.tecnicoresponsavel,
q.codigo_rede,
q.email,
q.tipoempresa,
q.`APP CLUBE DE DESCONTO`,
q.`34_Controle de Cashback`,
q.`34_Controle de Ofertas`,
q.`34_Controle de Pontos`,
q.`34_Controle de Pontos com Oferta por Cashback`,
q.`34_Repasse`,
q.`APP PRE VENDA`,
q.`CTE (TECNOSPEED)`,
q.`EMISSAO 1 NFCE CONTINGENCIA`,
q.`FORCA DE VENDA`,
q.`29_ESTACOES`,
q.`FORCA DE VENDAS - HERBIE`,
q.`41_ESTACOES`,
q.`GESTAO IMEDIATA`,
q.`GOMENU`,
q.`46_GOMenu Consulta (QR Code somente para consulta)`,
q.`46_GOMenu Delivery (Delivery)`,
q.`46_GOMenu Mobile (Consulta + pedido pelo celular do c`,
q.`46_GOMenu Pedido (Tablet na mesa)`,
q.`MANAGER SAAS`,
q.`57_CTe`,
q.`57_MDFe`,
q.`57_NFCe`,
q.`57_NFe`,
q.`57_NFSe`,
q.`MDFE (TECNOSPEED)`,
q.`MDFE-FLEXDOCS`,
q.`MOBI POCKET`,
q.`MOBIGESTAO`,
q.`NFCE (TECNOSPEED)`,
q.`NFCE-FLEXDOCS`,
q.`NFE (TECNOSPEED)`,
q.`NFE-FLEXDOCS`,
q.`NFSE (TECNOSPEED)`,
q.`NFSE-FLEXDOCS`,
q.`PORTAL XML`,
q.`R-GOURMET`,
q.`3_SUBMODULO`,
q.`3_PDVs`,
q.`3_ESTACOES`,
q.`3_Apoio Contabil`,
q.`3_Autopagamento`,
q.`3_Autopagamento - Demo`,
q.`3_Balcao`,
q.`3_Cartao`,
q.`3_Clientes`,
q.`3_Compras de Industrias/Distribuidoras`,
q.`3_Conciliacao de cartoes - Conciflex`,
q.`3_Conciliacao de cartoes - VIZZO`,
q.`3_Contas a Pagar`,
q.`3_Contas a Receber`,
q.`3_Contas Bancarias`,
q.`3_Contribuicao Solidaria`,
q.`3_Controle de Cheques`,
q.`3_Controle de Comissao`,
q.`3_Controle de Despesas`,
q.`3_Controle de Loja`,
q.`3_Controle de Producao`,
q.`3_Controle de Ticket/Cartao`,
q.`3_Controle Gerencial`,
q.`3_Donuz`,
q.`3_Emissao de Boletos`,
q.`3_Entrada de Notas`,
q.`3_Escrita Fiscal`,
q.`3_Fidelizacao`,
q.`3_Fidelizi`,
q.`3_Fluxo de Caixa`,
q.`3_Fornecedores`,
q.`3_Google Maps`,
q.`3_Integracao Anota Ai`,
q.`3_Integracao Area Central - ASSOCIADO`,
q.`3_Integracao Area Central - REDE`,
q.`3_Integracao Auditto`,
q.`3_Integracao Cresce Vendas`,
q.`3_Integracao Dominio XML`,
q.`3_Integracao IFOOD`,
q.`3_Integracao Neemo`,
q.`3_Integracao Nexfood`,
q.`3_Integracao PagPix`,
q.`3_Integracao RAPPI`,
q.`3_Integracao SG SISTEMAS`,
q.`3_Integracao Shipay`,
q.`3_Integracao SIMPLUS`,
q.`3_Integracao Site Mercado`,
q.`3_Integracao Tray`,
q.`3_Integracao XML SetUP - SGDFE GETCARD`,
q.`3_Inventario Fiscal`,
q.`3_Inventario Fisico ( Balanco)`,
q.`3_Levantamento Parcial de Estoque`,
q.`3_Mesa`,
q.`3_Mix Fiscal`,
q.`3_Movimentacao de Produtos`,
q.`3_Movimento de Caixa`,
q.`3_Pedidos`,
q.`3_PLAY VIEW`,
q.`3_Pre-Pedido`,
q.`3_Producao para entrega`,
q.`3_Produtos e Precos`,
q.`3_Resumo de Caixa`,
q.`3_SAT`,
q.`3_Scanntech`,
q.`3_Senha PDV por PINPAD - SITEF TUICCS`,
q.`3_Transferencia`,
q.`3_Troco Simples`,
q.`RJK-PDV`,
q.`2_SUBMODULO`,
q.`2_PDVs`,
q.`2_ESTACOES`,
q.`2_Apoio Contabil`,
q.`2_Clientes`,
q.`2_Comissoes`,
q.`2_Compras de Industrias/Distribuidoras`,
q.`2_Conciliacao de cartoes - Conciflex`,
q.`2_Conciliacao de cartoes - VIZZO`,
q.`2_Contas a Pagar`,
q.`2_Contas a Receber`,
q.`2_Contas Bancarias`,
q.`2_Contra Vales`,
q.`2_Contribuicao Solidaria`,
q.`2_Controle de Cheques`,
q.`2_Controle de Despesas`,
q.`2_Controle de Loja`,
q.`2_Controle de Producao`,
q.`2_Controle de Ticket/Cartao`,
q.`2_Controle de Trocas`,
q.`2_Controle de Vendas`,
q.`2_Controle Flex`,
q.`2_Controle Gerencial`,
q.`2_Cotacao de Atacado`,
q.`2_Donuz`,
q.`2_Emissao de Boletos`,
q.`2_Entrada de Notas`,
q.`2_Escrita Fiscal`,
q.`2_Fidelizacao`,
q.`2_Fluxo de Caixa`,
q.`2_Fornecedores`,
q.`2_Integracao APPMercados`,
q.`2_Integracao Area Central - ASSOCIADO`,
q.`2_Integracao Area Central - REDE`,
q.`2_Integracao Askyn`,
q.`2_Integracao Auditto`,
q.`2_Integracao Compre Facil`,
q.`2_Integracao Consignet`,
q.`2_Integracao Cresce Vendas`,
q.`2_Integracao Cupom Verde`,
q.`2_Integracao Deju`,
q.`2_Integracao Dominio XML`,
q.`2_Integracao IMENDES`,
q.`2_Integracao Insta Buy`,
q.`2_Integracao LOJAQUI`,
q.`2_Integracao Mercafacil`,
q.`2_Integracao Nexfood`,
q.`2_Integracao NovAmerica`,
q.`2_Integracao PagPix`,
q.`2_Integracao RAPPI`,
q.`2_Integracao SG SISTEMAS`,
q.`2_Integracao Shipay`,
q.`2_Integracao SIMPLUS`,
q.`2_Integracao Site Mercado`,
q.`2_Integracao Tray`,
q.`2_Integracao Web Jasper API`,
q.`2_Integracao WL Assessoria e Contabilidade`,
q.`2_Integracao XML SetUP - SGDFE GETCARD`,
q.`2_Inventario Fiscal`,
q.`2_Inventario Fisico ( Balanco)`,
q.`2_Levantamento Parcial de Estoque`,
q.`2_Mercafacil`,
q.`2_Mix Fiscal`,
q.`2_Movimentacao de Produtos`,
q.`2_Movimento de Caixa`,
q.`2_PLAY VIEW`,
q.`2_Prestacao de Servico`,
q.`2_Produtos e Precos`,
q.`2_Resumo de Caixa`,
q.`2_SAT`,
q.`2_Scanntech`,
q.`2_Senha PDV por PINPAD - SITEF TUICCS`,
q.`2_Senha venda prazo - Software Express`,
q.`2_SGCotacao On-line`,
q.`2_Transferencia`,
q.`2_Troco Simples`,
q.`SELF-CHECKOUT`,
q.`38_PDVs`,
q.`SG CARTAZ`,
q.`SG VIEW`,
q.`SG-NFCE`,
q.`22_SGDFE SG GETCARD`,
q.`SG-NFE`,
q.`21_SGDFE SG GETCARD`,
q.`SGBI`,
q.`SGCLOUD`,
q.`39_SUBMODULO`,
q.`39_PDVs`,
q.`39_ESTACOES`,
q.`39_Alteracoes`,
q.`39_Bancario`,
q.`39_Cadastro de Clientes e Funcionarios`,
q.`39_Cadastro de Fornecedores`,
q.`39_Cadastro de Produtos`,
q.`39_Cadastro de Tabela de Precos`,
q.`39_Cartao Presente`,
q.`39_Catalogo`,
q.`39_Clube de fidelizacao (Pontos)`,
q.`39_Comissao: Por Valor,Produto e Escalonado`,
q.`39_Compras`,
q.`39_Conciliacao de cartoes - Conciflex`,
q.`39_Consignado`,
q.`39_Contas a Pagar`,
q.`39_Contas a Receber`,
q.`39_Contrato de Cartao de Credito`,
q.`39_Contribuicao Solidaria`,
q.`39_Controle Caixa`,
q.`39_Controle de Estoque-Quantidade/Grade/Cor`,
q.`39_Controle de Manequim`,
q.`39_Controle de Metas`,
q.`39_Controle de Trocas`,
q.`39_Cotacao`,
q.`39_Cotacao Online`,
q.`39_Crediario`,
q.`39_D.R.E`,
q.`39_DashBoards`,
q.`39_Despesas`,
q.`39_Devolucoes de venda`,
q.`39_Emissao de Boletos`,
q.`39_Emissao de MDF-e`,
q.`39_Emissao de NFS-e`,
q.`39_Emissao de SAT / MFE`,
q.`39_Entrada de notas por XML`,
q.`39_Escrita fiscal`,
q.`39_Etiquetas`,
q.`39_Fracionamento`,
q.`39_Gerenciamento`,
q.`39_Homologacao Integradores`,
q.`39_Integracao Ad Rocket`,
q.`39_Integracao APPMercados`,
q.`39_Integracao Area Central - API`,
q.`39_Integracao Cartaz Facil`,
q.`39_Integracao Codevops`,
q.`39_Integracao Compre Facil`,
q.`39_Integracao Correios`,
q.`39_Integracao Cresce Vendas`,
q.`39_Integracao Dattion`,
q.`39_Integracao Deju`,
q.`39_Integracao Insta Buy`,
q.`39_Integracao Izi App`,
q.`39_Integracao Loja Integrada`,
q.`39_Integracao LOJAQUI`,
q.`39_Integracao Magazord`,
q.`39_Integracao Minus`,
q.`39_Integracao Nuvem Shop`,
q.`39_Integracao PagPix`,
q.`39_Integracao PlugLead`,
q.`39_Integracao Shipay`,
q.`39_Integracao Shopify`,
q.`39_Integracao Smart`,
q.`39_Integracao Supermercado Esperanca`,
q.`39_Integracao TI Soluti`,
q.`39_Integracao Tray`,
q.`39_Integracao Web Jasper`,
q.`39_Inventario de Estoque (Parcial ou Total)`,
q.`39_Inventario fiscal`,
q.`39_Movimentacao de Cheques`,
q.`39_Multilojas - Requisicao/Transferencia`,
q.`39_Nota Avulsa`,
q.`39_Ordem de Servico`,
q.`39_PDV OFFLINE`,
q.`39_Producao`,
q.`39_Promocoes`,
q.`39_Recibo Avulso`,
q.`39_Relatorios Dinamicos`,
q.`39_Vale para Funcionario`,
q.`39_Venda Ambulante/Sacoleiras`,
q.`SGERP LINUX`,
q.`1_SUBMODULO`,
q.`1_PDVs`,
q.`1_Apoio Contabil`,
q.`1_AT&M`,
q.`1_Atualizacao tributaria - Virtual`,
q.`1_Balanco Setorial`,
q.`1_Cartao Ponto`,
q.`1_Cheque Pre Datados`,
q.`1_Cheques Devolvidos`,
q.`1_Clientes`,
q.`1_Comissao de Vendedores`,
q.`1_Compras de Industrias/Distribuidoras`,
q.`1_Conciliacao cartoes - Valida Solucoes`,
q.`1_Conciliacao de cartoes - Conciflex`,
q.`1_Conciliacao de cartoes - PJM`,
q.`1_Conciliacao de cartoes - Procard`,
q.`1_Conciliacao de cartoes - TeiaCard`,
q.`1_Conciliacao de cartoes - VIZZO`,
q.`1_Consulta de Apoio Gerencial`,
q.`1_Contabilidade - Regras Fiscais`,
q.`1_Contas a Pagar`,
q.`1_Contas a Receber`,
q.`1_Contas Bancarias`,
q.`1_Contra Vales para Clientes`,
q.`1_Contribuicao Solidaria`,
q.`1_Controle de Convenios/Ticket/Cartao`,
q.`1_Controle de Despesas`,
q.`1_Controle de licitacoes`,
q.`1_Controle de Loja`,
q.`1_Controle de Promocoes`,
q.`1_Controle de Trocas`,
q.`1_Controle de Veiculos`,
q.`1_Controle de Verbas`,
q.`1_Controle Financeiro`,
q.`1_Controle Flex`,
q.`1_Controle Patrimonial`,
q.`1_Cotacao de Atacado`,
q.`1_DMCard - Integracao Soumais`,
q.`1_Emissao de Boletos`,
q.`1_Emissao NFCe Retaguarda`,
q.`1_Entrada de Notas/Calculo de Precos`,
q.`1_Escrita Fiscal`,
q.`1_Faturamento de Vendas`,
q.`1_Fechamento de Caixa de Lojas`,
q.`1_Fidelizacao`,
q.`1_Fluxo de Caixa`,
q.`1_Fornecedores`,
q.`1_Gerenciamento de Gondolas`,
q.`1_Grava Logs Externamente`,
q.`1_Homologacao Integradores`,
q.`1_Importacao/Exportacao`,
q.`1_Indices Financeiros`,
q.`1_Integracao Ad Rocket`,
q.`1_Integracao Alfred`,
q.`1_Integracao Amo Delivery`,
q.`1_Integracao APPMercados`,
q.`1_Integracao Area Central - API`,
q.`1_Integracao Area Central - ASSOCIADO`,
q.`1_Integracao Area Central - REDE`,
q.`1_Integracao arMHAzena`,
q.`1_Integracao Askyn`,
q.`1_Integracao Auditto`,
q.`1_Integracao Beblue`,
q.`1_Integracao Cartaz Facil`,
q.`1_Integracao cartoes Cocalcard`,
q.`1_Integracao Cerprosoft Sav`,
q.`1_Integracao Codevops`,
q.`1_Integracao Compre Facil`,
q.`1_Integracao Consignet`,
q.`1_Integracao controle de catraca CloudPark`,
q.`1_Integracao Cresce Vendas`,
q.`1_Integracao Cupom Verde`,
q.`1_Integracao Cyberlog - WMS`,
q.`1_Integracao Dattion`,
q.`1_Integracao de Associacao (Menu)`,
q.`1_Integracao Deju`,
q.`1_Integracao Docerrano`,
q.`1_Integracao Dominio XML`,
q.`1_Integracao Fiscal FGF`,
q.`1_Integracao Go Find`,
q.`1_Integracao IANDEV`,
q.`1_Integracao Ideris`,
q.`1_Integracao IMENDES`,
q.`1_Integracao InfoPrice`,
q.`1_Integracao Insta Buy`,
q.`1_Integracao Izi App`,
q.`1_Integracao KIKKER`,
q.`1_Integracao Loja Integrada`,
q.`1_Integracao LOJAQUI`,
q.`1_Integracao Matera`,
q.`1_Integracao Mercadex`,
q.`1_Integracao Mercafacil`,
q.`1_Integracao Minus`,
q.`1_Integracao Moria Consultoria`,
q.`1_Integracao NappSync`,
q.`1_Integracao Nexfood`,
q.`1_Integracao NovAmerica`,
q.`1_Integracao PagPix`,
q.`1_Integracao SG SISTEMAS`,
q.`1_Integracao Shipay`,
q.`1_Integracao Simpletask`,
q.`1_Integracao SIMPLUS`,
q.`1_Integracao Site Mercado`,
q.`1_Integracao Site Mercado API`,
q.`1_Integracao Smart`,
q.`1_Integracao Supermercado Esperanca`,
q.`1_Integracao TI Soluti`,
q.`1_Integracao Tray`,
q.`1_Integracao Web Jasper`,
q.`1_Integracao WL Assessoria e Contabilidade`,
q.`1_Integracao XML SetUP - SGDFE GETCARD`,
q.`1_Integracao XML SetUP - SGDFE LOCAL`,
q.`1_Inventario Fiscal`,
q.`1_Inventario Fisico ( Balanco)`,
q.`1_Levantamento Parcial de Estoque`,
q.`1_Mapa Fiscal`,
q.`1_Mix Fiscal`,
q.`1_Modulo Gestao`,
q.`1_Modulos de Consulta de Loja`,
q.`1_Movimentacao de Produtos`,
q.`1_Movimento de Caixa`,
q.`1_PAF ECF`,
q.`1_Pesquisa de Precos`,
q.`1_PLAY VIEW`,
q.`1_Producao ( Padaria , Acougue)`,
q.`1_Produtos e Precos`,
q.`1_Proposta`,
q.`1_Resumo de Caixa`,
q.`1_SAT`,
q.`1_Scanntech`,
q.`1_Senha PDV por PINPAD - SITEF TUICCS`,
q.`1_Senha venda prazo - Software Express`,
q.`1_Servico de Atendimento ao Cliente`,
q.`1_SGCotacao On-line`,
q.`1_SGPESQ`,
q.`1_Solucoes Fiscais`,
q.`1_Transferencia`,
q.`1_Troco Simples`,
q.`1_Vendas Cooperados/Associados`,
q.`1_Vendas de PDV's/Rentabilidade`,
q.`SGFOODS MOBILE`,
q.`19_ESTACOES`,
q.`SGMOBILE`,
q.`5_ESTACOES`,
q.`SGMONITORAMENTONOTAS`,
q.`SGNFE WINDOWS`,
q.`SGPOCKET`,
q.`6_ESTACOES`,
q.`TEF`,
q.`12_TEF CLOUD (SITEF - S.E.CONDUCTOR)`,
q.`12_TEF CLOUD (SITEF - TLS FISERV - S.E.CONDUCTOR)`,
q.`12_TEF CLOUD (SITEF - TLS FISERV)`,
q.`12_TEF CLOUD (SITEF)`,
q.`12_TEF CLOUD (SITEF) - CNPJ SG`,
q.`12_TEF CLOUD GETCARD (SITEF)`,
q.`12_TEF CLOUD GETCARD (SITEF) - CNPJ SG`,
q.`12_TEF REDE (SITEF - S.E.CONDUCTOR)`,
q.`12_TEF REDE (SITEF - TLS FISERV - S.E.CONDUCTOR)`,
q.`12_TEF REDE (SITEF - TLS FISERV)`,
q.`12_TEF REDE (SITEF)`,
q.`12_TEF SCOPE INTEGRACAO GETCARD`,
q.`12_TEF SCOPE ITAUTEC GETCARD`,
q.`12_TEF SCOPE ITAUTEC LOCAL`,
q.`12_TEF SITEF - OUTROS`,
q.`12_TEF SITEF - TEFWAY`,
q.`12_TEF SITEF - VPN GSURF`,
q.`12_TEF SMART`,
q.`12_TEFWAY`,
q.`TISS`,
q.dataPesquisaSatisfacaoCliente,
q.notaPesquisaSatisfacaoCliente,
q.contatoPesquisaSatisfacaoCliente,
q.dataUltimoControleVisita,
q.contatoUltimoControleVisita,
q.totalControleVisita12Meses,
q.dataOSVelha, 
q.tecnicoUltimaVisita,
q.totalOSUltimosDozeMeses,
q.quantidadeOSEmAberto,
q.quantidadeOSEmAbertoBug,
q.quantidadeOSEmAbertoAlteracao,
q.quantidadeOSEmAbertoPendencia
from
(
    select
	sg.empresa as "EMPRESA",
	cc.codcli10 as "CADCL",
	cc.nomefan10 as "FANTASIA",
	cc.razsoc10 as "RAZAOSOCIAL",
	cc.situacao10 as "SITUACAO",
	cc.dtultsit10 as "DATASITUACAO",
	sg.datainstal as "DATAINSTALACAO",
	sg.dtreajuste as "DATAULTIMOREAJUSTE",
	tv.nome as "VENDEDOR",
  	tv2.nome as "TECNICORESPONSAVEL",
	ct.descricao as "CLASSIFICACAO",
	tp.desctipo as "REPRESENTANTE",
	tp2.desctipo as "REPRESENTANTE2",
	tp3.desctipo as "REPRESENTANTE3",
	cc.endcli10 as "ENDERECO",
	CC.NUMENDCL10 as "NUMERO",
	CC.bairro10 as "BAIRRO",
	cc.codmunic10 as "CODIGO_CIDADE",
	tm.nome as "CIDADE",
	tm.uf as "ESTADO",
	cc.nomecon10 as "CONTATO",
        if(sg.codrede is null, 0,sg.codrede) as "CODIGO_REDE",
	cc.fonecli10 as "TELEFONE",
	sr.VALOR,
	SG.cgc as "CNPJ",
	date_format(ultimaSatisfacaoCliente.dataPesquisa, '%d/%m/%Y') as dataPesquisaSatisfacaoCliente,
	ultimaSatisfacaoCliente.nota as notaPesquisaSatisfacaoCliente,
	ultimaSatisfacaoCliente.contato as contatoPesquisaSatisfacaoCliente,
	date_format(ultimoControleVisita.dataVisita, '%d/%m/%Y') as dataUltimoControleVisita,
	ultimoControleVisita.contato as contatoUltimoControleVisita,
	ifnull(totalControleVisita12Meses.numeroVisitas12Meses,0) as totalControleVisita12Meses,
	dataOSVelha.dataOSAbertaAntiga as dataOSVelha, 
	concat(ultimoControleVisita.fkIdUsuario, ' ', ultimoControleVisita.login) as tecnicoUltimaVisita,
	ifnull(totalOS12meses.totalOSUltimosDozeMeses,0) as totalOSUltimosDozeMeses,
	ifnull(quantidadeOSEmAberto.totalOSEmAberto,0) as quantidadeOSEmAberto,
	ifnull(quantidadeOSEmAbertoBug.totalOSEmAbertoBug,0) as quantidadeOSEmAbertoBug,
	ifnull(quantidadeOSEmAbertoAlteracao.totalOSEmAbertoAlteracao,0) as quantidadeOSEmAbertoAlteracao,
	ifnull(quantidadeOSEmAbertoPendencia.totalOSEmAbertoPendencia,0) as quantidadeOSEmAbertoPendencia,
	produtos.*,
	modulos.*,
	submodulos.*,
	quantidadesPDV.*,
	quantidadesESTACOES.*,
	cc.emailcli10 as "EMAIL",
	case sg.tipo
		 WHEN 'C' THEN "ADMINISTRADORA DE CARTOES" 
         WHEN 'T' THEN "ASSISTENCIA TECNICA"       
         WHEN 'A' THEN "ASSOCIACAO DE COMPRAS"     
         WHEN 'P' THEN "AUTO PECAS"                
         WHEN 'F' THEN "ACOUGUE"                   
         WHEN 'K' THEN "C.D."                      
         WHEN 'V' THEN "CONFECCOES/CALCADOS"       
         WHEN 'D' THEN "DISTRIBUIDORA"             
         WHEN 'I' THEN "IND. PANIFICACAO"          
         WHEN 'L' THEN "LOJA DE DEPARTAMENTOS"     
         WHEN 'M' THEN "MATERIAL DE CONSTRUCAO"    
         WHEN 'B' THEN "MONITORAMENTO DE TELA"     
         WHEN 'J' THEN "OFICINAS MECANICA/ELETRICA"
         WHEN 'G' THEN "PANIFICADORA"              
         WHEN 'N' THEN "PAPELARIA"                 
         WHEN 'R' THEN "RESTAURANTE E SIMILAR"     
         WHEN 'S' THEN "SUPERMERCADO"              
         WHEN 'O' THEN "OUTROS" 
         ELSE          "NAO INFORMADO"  
     end TIPOEMPRESA
from
	sgscli sg
inner join cadcli cc on
	cc.cgccpf10 = sg.cgc
left join tabven tv on
	tv.codigo = cc.vended210
left join tabven tv2 on
	tv2.codigo = cc.vended10
left join catcli ct on
	ct.codigo = sg.codcatcli
inner join tipcli tp on
	tp.codtipo = cc.tipocli10
left join tipcli tp2 on
	tp2.codtipo = sg.parceiro2
left join tipcli tp3 on
	tp3.codtipo = sg.parceiro3
left join (
	select
		sc.codcli,
		sum(sc.valor) as VALOR
	from
		sercli sc
	inner join (
		select
			codigo
		from
			tipser
		where
			servrecor is null) tp on
		tp.codigo = sc.codsercli
	group by
		sc.codcli ) sr on
	sr.codcli = cc.codcli10
LEFT JOIN(
        SELECT wpsc.fkCodcliCadcli, wpsc.dataPesquisa,wpsc.nota, wpsc.contato
        FROM webPesquisaSatisfacaoCliente wpsc
        INNER JOIN (
                    SELECT fkCodcliCadcli,max(dataPesquisa) as dataPesquisa
                    FROM webPesquisaSatisfacaoCliente group by fkCodcliCadcli
        ) wpscsub ON wpsc.dataPesquisa = wpscsub.dataPesquisa AND wpsc.fkCodcliCadcli = wpscsub.fkCodcliCadcli
) as ultimaSatisfacaoCliente ON ultimaSatisfacaoCliente.fkCodcliCadcli = cc.codcli10
LEFT JOIN(
        SELECT c.codcli10, controleVisita.dataVisita, controleVisita.contato, controleVisita.fkIdUsuario, wu.login FROM webcontrolevisita controleVisita
        INNER JOIN (
                    SELECT wc.cnpj, max(wc.dataVisita) as dataPesquisa from webcontrolevisita wc group by wc.cnpj
        ) t2 ON (controleVisita.dataVisita = t2.dataPesquisa AND t2.cnpj = controleVisita.cnpj)
        inner join cadcli c on (c.cgccpf10 = t2.cnpj)
        left join webUsuario wu on wu.id = controleVisita.fkIdUsuario
        group by t2.cnpj
) as ultimoControleVisita ON ultimoControleVisita.codcli10 = cc.codcli10
LEFT JOIN (
        SELECT c.codcli10 as codcli, count(*) as numeroVisitas12Meses
        FROM webcontrolevisita wc
        INNER JOIN cadcli c on (c.cgccpf10 = wc.cnpj)
        WHERE wc.dataVisita is not null AND DATE_ADD(wc.dataVisita, INTERVAL 12 MONTH) >= NOW()
        GROUP BY c.codcli10
) as totalControleVisita12Meses ON (totalControleVisita12Meses.codcli = cc.codcli10)
LEFT JOIN(
        SELECT codcli, count(codord) as totalOSEmAberto
        FROM suptec spt
        WHERE spt.codsit is null
        GROUP BY codcli
) as quantidadeOSEmAberto ON (quantidadeOSEmAberto.codcli = cc.codcli10)
LEFT JOIN(
        SELECT codcli, date_format(min(data), '%d/%m/%Y') as dataOSAbertaAntiga FROM suptec spt WHERE spt.codsit is null
        GROUP BY codcli
) as dataOSVelha ON (dataOSVelha.codcli = cc.codcli10)
LEFT JOIN(
        SELECT codcli, count(codord) as totalOSUltimosDozeMeses
        FROM suptec spt
        WHERE DATE_ADD(spt.data, INTERVAL 12 MONTH) >= NOW()
        GROUP BY codcli
) as totalOS12meses ON (totalOS12meses.codcli = cc.codcli10)
LEFT JOIN(
        SELECT codcli, count(codord) as totalOSEmAbertoBug
        FROM suptec spt
        WHERE spt.codcat in (3, 27, 29) and codsit is null
        GROUP BY codcli
) as quantidadeOSEmAbertoBug ON (quantidadeOSEmAbertoBug.codcli = cc.codcli10)
LEFT JOIN(
        SELECT codcli, count(codord) as totalOSEmAbertoAlteracao
        FROM suptec spt
        WHERE spt.codcat in (4,25) and codsit is null
        GROUP BY codcli
) as quantidadeOSEmAbertoAlteracao ON (quantidadeOSEmAbertoAlteracao.codcli = cc.codcli10)
LEFT JOIN(
        SELECT codcli, count(codord) as totalOSEmAbertoPendencia
        FROM suptec spt
        WHERE spt.codcat in (6,11,19,21) and codsit is null
        GROUP BY codcli
) as quantidadeOSEmAbertoPendencia ON (quantidadeOSEmAbertoPendencia.codcli = cc.codcli10)
left join tabmun tm on
	tm.codigo = cc.codmunic10 
left join (
SELECT cnpj AS CNPJPRODUTO, 
  IF(SUM(IF(pd.produto = 1, 1, 0)) > 0, 'OK', '') AS `SGERP LINUX`,
  IF(SUM(IF(pd.produto = 2, 1, 0)) > 0, 'OK', '') AS `RJK-PDV`,
  IF(SUM(IF(pd.produto = 3, 1, 0)) > 0, 'OK', '') AS `R-GOURMET`,
  IF(SUM(IF(pd.produto = 37, 1, 0)) > 0, 'OK', '') AS `EMISSAO 1 NFCE CONTINGENCIA`,
  IF(SUM(IF(pd.produto = 5, 1, 0)) > 0, 'OK', '') AS `SGMOBILE`,
  IF(SUM(IF(pd.produto = 6, 1, 0)) > 0, 'OK', '') AS `SGPOCKET`,
  IF(SUM(IF(pd.produto = 54, 1, 0)) > 0, 'OK', '') AS `MOBI POCKET`,
  IF(SUM(IF(pd.produto = 7, 1, 0)) > 0, 'OK', '') AS `NFE (TECNOSPEED)`,
  IF(SUM(IF(pd.produto = 8, 1, 0)) > 0, 'OK', '') AS `NFSE (TECNOSPEED)`,
  IF(SUM(IF(pd.produto = 9, 1, 0)) > 0, 'OK', '') AS `CTE (TECNOSPEED)`,
  IF(SUM(IF(pd.produto = 10, 1, 0)) > 0, 'OK', '') AS `MDFE (TECNOSPEED)`,
  IF(SUM(IF(pd.produto = 11, 1, 0)) > 0, 'OK', '') AS `NFCE (TECNOSPEED)`,
  IF(SUM(IF(pd.produto = 12, 1, 0)) > 0, 'OK', '') AS `TEF`,
  IF(SUM(IF(pd.produto = 13, 1, 0)) > 0, 'OK', '') AS `SGMONITORAMENTONOTAS`,
  IF(SUM(IF(pd.produto = 18, 1, 0)) > 0, 'OK', '') AS `SGNFE WINDOWS`,
  IF(SUM(IF(pd.produto = 19, 1, 0)) > 0, 'OK', '') AS `SGFOODS MOBILE`,
  IF(SUM(IF(pd.produto = 21, 1, 0)) > 0, 'OK', '') AS `SG-NFE`,
  IF(SUM(IF(pd.produto = 22, 1, 0)) > 0, 'OK', '') AS `SG-NFCE`,
  IF(SUM(IF(pd.produto = 24, 1, 0)) > 0, 'OK', '') AS `NFE-FLEXDOCS`,
  IF(SUM(IF(pd.produto = 25, 1, 0)) > 0, 'OK', '') AS `NFCE-FLEXDOCS`,
  IF(SUM(IF(pd.produto = 26, 1, 0)) > 0, 'OK', '') AS `NFSE-FLEXDOCS`,
  IF(SUM(IF(pd.produto = 27, 1, 0)) > 0, 'OK', '') AS `MDFE-FLEXDOCS`,
  IF(SUM(IF(pd.produto = 29, 1, 0)) > 0, 'OK', '') AS `FORCA DE VENDA`,
  IF(SUM(IF(pd.produto = 31, 1, 0)) > 0, 'OK', '') AS `GESTAO IMEDIATA`,
  IF(SUM(IF(pd.produto = 34, 1, 0)) > 0, 'OK', '') AS `APP CLUBE DE DESCONTO`,
  IF(SUM(IF(pd.produto = 38, 1, 0)) > 0, 'OK', '') AS `SELF-CHECKOUT`,
  IF(SUM(IF(pd.produto = 39, 1, 0)) > 0, 'OK', '') AS `SGCLOUD`,
  IF(SUM(IF(pd.produto = 41, 1, 0)) > 0, 'OK', '') AS `FORCA DE VENDAS - HERBIE`,
  IF(SUM(IF(pd.produto = 44, 1, 0)) > 0, 'OK', '') AS `SG CARTAZ`,
  IF(SUM(IF(pd.produto = 45, 1, 0)) > 0, 'OK', '') AS `SG VIEW`,
  IF(SUM(IF(pd.produto = 46, 1, 0)) > 0, 'OK', '') AS `GOMENU`,
  IF(SUM(IF(pd.produto = 51, 1, 0)) > 0, 'OK', '') AS `PORTAL XML`,
  IF(SUM(IF(pd.produto = 52, 1, 0)) > 0, 'OK', '') AS `MOBIGESTAO`,
  IF(SUM(IF(pd.produto = 53, 1, 0)) > 0, 'OK', '') AS `APP PRE VENDA`,
  IF(SUM(IF(pd.produto = 55, 1, 0)) > 0, 'OK', '') AS `SGBI`,
  IF(SUM(IF(pd.produto = 56, 1, 0)) > 0, 'OK', '') AS `TISS`,
  IF(SUM(IF(pd.produto = 57, 1, 0)) > 0, 'OK', '') AS `MANAGER SAAS` FROM prodsg pd GROUP BY cnpj
)  produtos on
	produtos.CNPJPRODUTO = sg.cgc
left join (
SELECT cnpj AS CNPJMODULO, 
	IF( modulosg.modulo = '1' AND modulosg.produto = '1', 'OK', '') AS `1_Produtos e Precos`,
	IF( modulosg.modulo = '2' AND modulosg.produto = '1', 'OK', '') AS `1_Fornecedores`,
	IF( modulosg.modulo = '3' AND modulosg.produto = '1', 'OK', '') AS `1_Clientes`,
	IF( modulosg.modulo = '4' AND modulosg.produto = '1', 'OK', '') AS `1_Contas a Pagar`,
	IF( modulosg.modulo = '5' AND modulosg.produto = '1', 'OK', '') AS `1_Contas a Receber`,
	IF( modulosg.modulo = '6' AND modulosg.produto = '1', 'OK', '') AS `1_Resumo de Caixa`,
	IF( modulosg.modulo = '7' AND modulosg.produto = '1', 'OK', '') AS `1_Controle de Loja`,
	IF( modulosg.modulo = '8' AND modulosg.produto = '1', 'OK', '') AS `1_Cartao Ponto`,
	IF( modulosg.modulo = '9' AND modulosg.produto = '1', 'OK', '') AS `1_Contra Vales para Clientes`,
	IF( modulosg.modulo = '10' AND modulosg.produto = '1', 'OK', '') AS `1_Modulos de Consulta de Loja`,
	IF( modulosg.modulo = '11' AND modulosg.produto = '1', 'OK', '') AS `1_Faturamento de Vendas`,
	IF( modulosg.modulo = '12' AND modulosg.produto = '1', 'OK', '') AS `1_Cheque Pre Datados`,
	IF( modulosg.modulo = '13' AND modulosg.produto = '1', 'OK', '') AS `1_Inventario Fisico ( Balanco)`,
	IF( modulosg.modulo = '14' AND modulosg.produto = '1', 'OK', '') AS `1_Movimentacao de Produtos`,
	IF( modulosg.modulo = '15' AND modulosg.produto = '1', 'OK', '') AS `1_Entrada de Notas/Calculo de Precos`,
	IF( modulosg.modulo = '16' AND modulosg.produto = '1', 'OK', '') AS `1_Vendas de PDV's/Rentabilidade`,
	IF( modulosg.modulo = '17' AND modulosg.produto = '1', 'OK', '') AS `1_Cotacao de Atacado`,
	IF( modulosg.modulo = '18' AND modulosg.produto = '1', 'OK', '') AS `1_Cheques Devolvidos`,
	IF( modulosg.modulo = '19' AND modulosg.produto = '1', 'OK', '') AS `1_Producao ( Padaria , Acougue)`,
	IF( modulosg.modulo = '20' AND modulosg.produto = '1', 'OK', '') AS `1_Contas Bancarias`,
	IF( modulosg.modulo = '21' AND modulosg.produto = '1', 'OK', '') AS `1_Controle de Despesas`,
	IF( modulosg.modulo = '22' AND modulosg.produto = '1', 'OK', '') AS `1_Controle de Convenios/Ticket/Cartao`,
	IF( modulosg.modulo = '23' AND modulosg.produto = '1', 'OK', '') AS `1_Comissao de Vendedores`,
	IF( modulosg.modulo = '24' AND modulosg.produto = '1', 'OK', '') AS `1_Compras de Industrias/Distribuidoras`,
	IF( modulosg.modulo = '25' AND modulosg.produto = '1', 'OK', '') AS `1_Indices Financeiros`,
	IF( modulosg.modulo = '26' AND modulosg.produto = '1', 'OK', '') AS `1_Inventario Fiscal`,
	IF( modulosg.modulo = '27' AND modulosg.produto = '1', 'OK', '') AS `1_Importacao/Exportacao`,
	IF( modulosg.modulo = '28' AND modulosg.produto = '1', 'OK', '') AS `1_Controle de Trocas`,
	IF( modulosg.modulo = '29' AND modulosg.produto = '1', 'OK', '') AS `1_Levantamento Parcial de Estoque`,
	IF( modulosg.modulo = '30' AND modulosg.produto = '1', 'OK', '') AS `1_Movimento de Caixa`,
	IF( modulosg.modulo = '31' AND modulosg.produto = '1', 'OK', '') AS `1_Pesquisa de Precos`,
	IF( modulosg.modulo = '32' AND modulosg.produto = '1', 'OK', '') AS `1_Controle de Verbas`,
	IF( modulosg.modulo = '33' AND modulosg.produto = '1', 'OK', '') AS `1_Transferencia`,
	IF( modulosg.modulo = '34' AND modulosg.produto = '1', 'OK', '') AS `1_Apoio Contabil`,
	IF( modulosg.modulo = '35' AND modulosg.produto = '1', 'OK', '') AS `1_Balanco Setorial`,
	IF( modulosg.modulo = '36' AND modulosg.produto = '1', 'OK', '') AS `1_Controle de Promocoes`,
	IF( modulosg.modulo = '37' AND modulosg.produto = '1', 'OK', '') AS `1_Controle Patrimonial`,
	IF( modulosg.modulo = '39' AND modulosg.produto = '1', 'OK', '') AS `1_Controle de Veiculos`,
	IF( modulosg.modulo = '40' AND modulosg.produto = '1', 'OK', '') AS `1_Escrita Fiscal`,
	IF( modulosg.modulo = '41' AND modulosg.produto = '1', 'OK', '') AS `1_Fidelizacao`,
	IF( modulosg.modulo = '42' AND modulosg.produto = '1', 'OK', '') AS `1_Fluxo de Caixa`,
	IF( modulosg.modulo = '43' AND modulosg.produto = '1', 'OK', '') AS `1_Fechamento de Caixa de Lojas`,
	IF( modulosg.modulo = '44' AND modulosg.produto = '1', 'OK', '') AS `1_Gerenciamento de Gondolas`,
	IF( modulosg.modulo = '46' AND modulosg.produto = '1', 'OK', '') AS `1_Servico de Atendimento ao Cliente`,
	IF( modulosg.modulo = '47' AND modulosg.produto = '1', 'OK', '') AS `1_Consulta de Apoio Gerencial`,
	IF( modulosg.modulo = '48' AND modulosg.produto = '1', 'OK', '') AS `1_Vendas Cooperados/Associados`,
	IF( modulosg.modulo = '71' AND modulosg.produto = '1', 'OK', '') AS `1_Controle Financeiro`,
	IF( modulosg.modulo = '58' AND modulosg.produto = '1', 'OK', '') AS `1_Mapa Fiscal`,
	IF( modulosg.modulo = '59' AND modulosg.produto = '1', 'OK', '') AS `1_SGCotacao On-line`,
	IF( modulosg.modulo = '60' AND modulosg.produto = '1', 'OK', '') AS `1_SGPESQ`,
	IF( modulosg.modulo = '61' AND modulosg.produto = '1', 'OK', '') AS `1_AT&M`,
	IF( modulosg.modulo = '72' AND modulosg.produto = '1', 'OK', '') AS `1_Modulo Gestao`,
	IF( modulosg.modulo = '73' AND modulosg.produto = '1', 'OK', '') AS `1_PAF ECF`,
	IF( modulosg.modulo = '74' AND modulosg.produto = '1', 'OK', '') AS `1_SAT`,
	IF( modulosg.modulo = '75' AND modulosg.produto = '1', 'OK', '') AS `1_Proposta`,
	IF( modulosg.modulo = '104' AND modulosg.produto = '1', 'OK', '') AS `1_Scanntech`,
	IF( modulosg.modulo = '107' AND modulosg.produto = '1', 'OK', '') AS `1_Contribuicao Solidaria`,
	IF( modulosg.modulo = '108' AND modulosg.produto = '1', 'OK', '') AS `1_Conciliacao de cartoes - Conciflex`,
	IF( modulosg.modulo = '109' AND modulosg.produto = '1', 'OK', '') AS `1_Conciliacao de cartoes - Procard`,
	IF( modulosg.modulo = '110' AND modulosg.produto = '1', 'OK', '') AS `1_Atualizacao tributaria - Virtual`,
	IF( modulosg.modulo = '115' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Cerprosoft Sav`,
	IF( modulosg.modulo = '116' AND modulosg.produto = '1', 'OK', '') AS `1_Conciliacao de cartoes - TeiaCard`,
	IF( modulosg.modulo = '117' AND modulosg.produto = '1', 'OK', '') AS `1_Mix Fiscal`,
	IF( modulosg.modulo = '118' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao NovAmerica`,
	IF( modulosg.modulo = '119' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Consignet`,
	IF( modulosg.modulo = '120' AND modulosg.produto = '1', 'OK', '') AS `1_PLAY VIEW`,
	IF( modulosg.modulo = '121' AND modulosg.produto = '1', 'OK', '') AS `1_Senha venda prazo - Software Express`,
	IF( modulosg.modulo = '122' AND modulosg.produto = '1', 'OK', '') AS `1_DMCard - Integracao Soumais`,
	IF( modulosg.modulo = '124' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao cartoes Cocalcard`,
	IF( modulosg.modulo = '126' AND modulosg.produto = '1', 'OK', '') AS `1_Conciliacao de cartoes - PJM`,
	IF( modulosg.modulo = '129' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Mercadex`,
	IF( modulosg.modulo = '130' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Site Mercado`,
	IF( modulosg.modulo = '131' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao XML SetUP - SGDFE LOCAL`,
	IF( modulosg.modulo = '132' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao XML SetUP - SGDFE GETCARD`,
	IF( modulosg.modulo = '134' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Fiscal FGF`,
	IF( modulosg.modulo = '136' AND modulosg.produto = '1', 'OK', '') AS `1_Grava Logs Externamente`,
	IF( modulosg.modulo = '137' AND modulosg.produto = '1', 'OK', '') AS `1_Troco Simples`,
	IF( modulosg.modulo = '139' AND modulosg.produto = '1', 'OK', '') AS `1_Emissao de Boletos`,
	IF( modulosg.modulo = '140' AND modulosg.produto = '1', 'OK', '') AS `1_Emissao NFCe Retaguarda`,
	IF( modulosg.modulo = '141' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao SIMPLUS`,
	IF( modulosg.modulo = '143' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao controle de catraca CloudPark`,
	IF( modulosg.modulo = '146' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Area Central - REDE`,
	IF( modulosg.modulo = '147' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Area Central - ASSOCIADO`,
	IF( modulosg.modulo = '148' AND modulosg.produto = '1', 'OK', '') AS `1_Controle Flex`,
	IF( modulosg.modulo = '150' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Alfred`,
	IF( modulosg.modulo = '152' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao WL Assessoria e Contabilidade`,
	IF( modulosg.modulo = '153' AND modulosg.produto = '1', 'OK', '') AS `1_Solucoes Fiscais`,
	IF( modulosg.modulo = '155' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Cyberlog - WMS`,
	IF( modulosg.modulo = '157' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Askyn`,
	IF( modulosg.modulo = '158' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Beblue`,
	IF( modulosg.modulo = '159' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao APPMercados`,
	IF( modulosg.modulo = '160' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao arMHAzena`,
	IF( modulosg.modulo = '161' AND modulosg.produto = '1', 'OK', '') AS `1_Contabilidade - Regras Fiscais`,
	IF( modulosg.modulo = '163' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao LOJAQUI`,
	IF( modulosg.modulo = '165' AND modulosg.produto = '1', 'OK', '') AS `1_Conciliacao de cartoes - VIZZO`,
	IF( modulosg.modulo = '167' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Nexfood`,
	IF( modulosg.modulo = '168' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao IANDEV`,
	IF( modulosg.modulo = '169' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao KIKKER`,
	IF( modulosg.modulo = '170' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Amo Delivery`,
	IF( modulosg.modulo = '171' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Tray`,
	IF( modulosg.modulo = '172' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Auditto`,
	IF( modulosg.modulo = '173' AND modulosg.produto = '1', 'OK', '') AS `1_Senha PDV por PINPAD - SITEF TUICCS`,
	IF( modulosg.modulo = '174' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Cresce Vendas`,
	IF( modulosg.modulo = '175' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao NappSync`,
	IF( modulosg.modulo = '177' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao de Associacao (Menu)`,
	IF( modulosg.modulo = '178' AND modulosg.produto = '1', 'OK', '') AS `1_Controle de licitacoes`,
	IF( modulosg.modulo = '179' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Site Mercado API`,
	IF( modulosg.modulo = '176' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao SG SISTEMAS`,
	IF( modulosg.modulo = '180' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Compre Facil`,
	IF( modulosg.modulo = '181' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Insta Buy`,
	IF( modulosg.modulo = '182' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Deju`,
	IF( modulosg.modulo = '211' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Cupom Verde`,
	IF( modulosg.modulo = '254' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Smart`,
	IF( modulosg.modulo = '253' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Shipay`,
	IF( modulosg.modulo = '256' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Web Jasper`,
	IF( modulosg.modulo = '291' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Go Find`,
	IF( modulosg.modulo = '294' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Dominio XML`,
	IF( modulosg.modulo = '295' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Matera`,
	IF( modulosg.modulo = '301' AND modulosg.produto = '1', 'OK', '') AS `1_Homologacao Integradores`,
	IF( modulosg.modulo = '302' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Ideris`,
	IF( modulosg.modulo = '308' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Minus`,
	IF( modulosg.modulo = '309' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao InfoPrice`,
	IF( modulosg.modulo = '311' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Supermercado Esperanca`,
	IF( modulosg.modulo = '312' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao PagPix`,
	IF( modulosg.modulo = '313' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Ad Rocket`,
	IF( modulosg.modulo = '314' AND modulosg.produto = '1', 'OK', '') AS `1_Conciliacao cartoes - Valida Solucoes`,
	IF( modulosg.modulo = '315' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao IMENDES`,
	IF( modulosg.modulo = '320' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Area Central - API`,
	IF( modulosg.modulo = '322' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao TI Soluti`,
	IF( modulosg.modulo = '323' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Loja Integrada`,
	IF( modulosg.modulo = '333' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Izi App`,
	IF( modulosg.modulo = '334' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Mercafacil`,
	IF( modulosg.modulo = '343' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Cartaz Facil`,
	IF( modulosg.modulo = '344' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Dattion`,
	IF( modulosg.modulo = '345' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Codevops`,
	IF( modulosg.modulo = '346' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Docerrano`,
	IF( modulosg.modulo = '347' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Moria Consultoria`,
	IF( modulosg.modulo = '348' AND modulosg.produto = '1', 'OK', '') AS `1_Integracao Simpletask`,
	IF( modulosg.modulo = '1' AND modulosg.produto = '2', 'OK', '') AS `2_Produtos e Precos`,
	IF( modulosg.modulo = '2' AND modulosg.produto = '2', 'OK', '') AS `2_Fornecedores`,
	IF( modulosg.modulo = '3' AND modulosg.produto = '2', 'OK', '') AS `2_Clientes`,
	IF( modulosg.modulo = '11' AND modulosg.produto = '2', 'OK', '') AS `2_Controle de Vendas`,
	IF( modulosg.modulo = '7' AND modulosg.produto = '2', 'OK', '') AS `2_Controle de Loja`,
	IF( modulosg.modulo = '14' AND modulosg.produto = '2', 'OK', '') AS `2_Movimentacao de Produtos`,
	IF( modulosg.modulo = '15' AND modulosg.produto = '2', 'OK', '') AS `2_Entrada de Notas`,
	IF( modulosg.modulo = '33' AND modulosg.produto = '2', 'OK', '') AS `2_Transferencia`,
	IF( modulosg.modulo = '19' AND modulosg.produto = '2', 'OK', '') AS `2_Controle de Producao`,
	IF( modulosg.modulo = '29' AND modulosg.produto = '2', 'OK', '') AS `2_Levantamento Parcial de Estoque`,
	IF( modulosg.modulo = '30' AND modulosg.produto = '2', 'OK', '') AS `2_Movimento de Caixa`,
	IF( modulosg.modulo = '4' AND modulosg.produto = '2', 'OK', '') AS `2_Contas a Pagar`,
	IF( modulosg.modulo = '5' AND modulosg.produto = '2', 'OK', '') AS `2_Contas a Receber`,
	IF( modulosg.modulo = '23' AND modulosg.produto = '2', 'OK', '') AS `2_Comissoes`,
	IF( modulosg.modulo = '24' AND modulosg.produto = '2', 'OK', '') AS `2_Compras de Industrias/Distribuidoras`,
	IF( modulosg.modulo = '22' AND modulosg.produto = '2', 'OK', '') AS `2_Controle de Ticket/Cartao`,
	IF( modulosg.modulo = '9' AND modulosg.produto = '2', 'OK', '') AS `2_Contra Vales`,
	IF( modulosg.modulo = '40' AND modulosg.produto = '2', 'OK', '') AS `2_Escrita Fiscal`,
	IF( modulosg.modulo = '6' AND modulosg.produto = '2', 'OK', '') AS `2_Resumo de Caixa`,
	IF( modulosg.modulo = '34' AND modulosg.produto = '2', 'OK', '') AS `2_Apoio Contabil`,
	IF( modulosg.modulo = '56' AND modulosg.produto = '2', 'OK', '') AS `2_Controle Gerencial`,
	IF( modulosg.modulo = '21' AND modulosg.produto = '2', 'OK', '') AS `2_Controle de Despesas`,
	IF( modulosg.modulo = '42' AND modulosg.produto = '2', 'OK', '') AS `2_Fluxo de Caixa`,
	IF( modulosg.modulo = '20' AND modulosg.produto = '2', 'OK', '') AS `2_Contas Bancarias`,
	IF( modulosg.modulo = '12' AND modulosg.produto = '2', 'OK', '') AS `2_Controle de Cheques`,
	IF( modulosg.modulo = '55' AND modulosg.produto = '2', 'OK', '') AS `2_Prestacao de Servico`,
	IF( modulosg.modulo = '26' AND modulosg.produto = '2', 'OK', '') AS `2_Inventario Fiscal`,
	IF( modulosg.modulo = '74' AND modulosg.produto = '2', 'OK', '') AS `2_SAT`,
	IF( modulosg.modulo = '104' AND modulosg.produto = '2', 'OK', '') AS `2_Scanntech`,
	IF( modulosg.modulo = '107' AND modulosg.produto = '2', 'OK', '') AS `2_Contribuicao Solidaria`,
	IF( modulosg.modulo = '13' AND modulosg.produto = '2', 'OK', '') AS `2_Inventario Fisico ( Balanco)`,
	IF( modulosg.modulo = '28' AND modulosg.produto = '2', 'OK', '') AS `2_Controle de Trocas`,
	IF( modulosg.modulo = '117' AND modulosg.produto = '2', 'OK', '') AS `2_Mix Fiscal`,
	IF( modulosg.modulo = '118' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao NovAmerica`,
	IF( modulosg.modulo = '119' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Consignet`,
	IF( modulosg.modulo = '120' AND modulosg.produto = '2', 'OK', '') AS `2_PLAY VIEW`,
	IF( modulosg.modulo = '121' AND modulosg.produto = '2', 'OK', '') AS `2_Senha venda prazo - Software Express`,
	IF( modulosg.modulo = '41' AND modulosg.produto = '2', 'OK', '') AS `2_Fidelizacao`,
	IF( modulosg.modulo = '135' AND modulosg.produto = '2', 'OK', '') AS `2_Donuz`,
	IF( modulosg.modulo = '139' AND modulosg.produto = '2', 'OK', '') AS `2_Emissao de Boletos`,
	IF( modulosg.modulo = '141' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao SIMPLUS`,
	IF( modulosg.modulo = '137' AND modulosg.produto = '2', 'OK', '') AS `2_Troco Simples`,
	IF( modulosg.modulo = '132' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao XML SetUP - SGDFE GETCARD`,
	IF( modulosg.modulo = '148' AND modulosg.produto = '2', 'OK', '') AS `2_Controle Flex`,
	IF( modulosg.modulo = '146' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Area Central - REDE`,
	IF( modulosg.modulo = '147' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Area Central - ASSOCIADO`,
	IF( modulosg.modulo = '130' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Site Mercado`,
	IF( modulosg.modulo = '17' AND modulosg.produto = '2', 'OK', '') AS `2_Cotacao de Atacado`,
	IF( modulosg.modulo = '59' AND modulosg.produto = '2', 'OK', '') AS `2_SGCotacao On-line`,
	IF( modulosg.modulo = '157' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Askyn`,
	IF( modulosg.modulo = '165' AND modulosg.produto = '2', 'OK', '') AS `2_Conciliacao de cartoes - VIZZO`,
	IF( modulosg.modulo = '167' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Nexfood`,
	IF( modulosg.modulo = '166' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao RAPPI`,
	IF( modulosg.modulo = '108' AND modulosg.produto = '2', 'OK', '') AS `2_Conciliacao de cartoes - Conciflex`,
	IF( modulosg.modulo = '171' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Tray`,
	IF( modulosg.modulo = '172' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Auditto`,
	IF( modulosg.modulo = '111' AND modulosg.produto = '2', 'OK', '') AS `2_Mercafacil`,
	IF( modulosg.modulo = '176' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao SG SISTEMAS`,
	IF( modulosg.modulo = '180' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Compre Facil`,
	IF( modulosg.modulo = '181' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Insta Buy`,
	IF( modulosg.modulo = '182' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Deju`,
	IF( modulosg.modulo = '159' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao APPMercados`,
	IF( modulosg.modulo = '163' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao LOJAQUI`,
	IF( modulosg.modulo = '174' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Cresce Vendas`,
	IF( modulosg.modulo = '211' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Cupom Verde`,
	IF( modulosg.modulo = '294' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Dominio XML`,
	IF( modulosg.modulo = '173' AND modulosg.produto = '2', 'OK', '') AS `2_Senha PDV por PINPAD - SITEF TUICCS`,
	IF( modulosg.modulo = '253' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Shipay`,
	IF( modulosg.modulo = '152' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao WL Assessoria e Contabilidade`,
	IF( modulosg.modulo = '310' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Web Jasper API`,
	IF( modulosg.modulo = '312' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao PagPix`,
	IF( modulosg.modulo = '315' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao IMENDES`,
	IF( modulosg.modulo = '334' AND modulosg.produto = '2', 'OK', '') AS `2_Integracao Mercafacil`,
	IF( modulosg.modulo = '1' AND modulosg.produto = '3', 'OK', '') AS `3_Produtos e Precos`,
	IF( modulosg.modulo = '2' AND modulosg.produto = '3', 'OK', '') AS `3_Fornecedores`,
	IF( modulosg.modulo = '3' AND modulosg.produto = '3', 'OK', '') AS `3_Clientes`,
	IF( modulosg.modulo = '49' AND modulosg.produto = '3', 'OK', '') AS `3_Balcao`,
	IF( modulosg.modulo = '50' AND modulosg.produto = '3', 'OK', '') AS `3_Pedidos`,
	IF( modulosg.modulo = '51' AND modulosg.produto = '3', 'OK', '') AS `3_Mesa`,
	IF( modulosg.modulo = '52' AND modulosg.produto = '3', 'OK', '') AS `3_Producao para entrega`,
	IF( modulosg.modulo = '53' AND modulosg.produto = '3', 'OK', '') AS `3_Cartao`,
	IF( modulosg.modulo = '54' AND modulosg.produto = '3', 'OK', '') AS `3_Pre-Pedido`,
	IF( modulosg.modulo = '7' AND modulosg.produto = '3', 'OK', '') AS `3_Controle de Loja`,
	IF( modulosg.modulo = '14' AND modulosg.produto = '3', 'OK', '') AS `3_Movimentacao de Produtos`,
	IF( modulosg.modulo = '15' AND modulosg.produto = '3', 'OK', '') AS `3_Entrada de Notas`,
	IF( modulosg.modulo = '19' AND modulosg.produto = '3', 'OK', '') AS `3_Controle de Producao`,
	IF( modulosg.modulo = '30' AND modulosg.produto = '3', 'OK', '') AS `3_Movimento de Caixa`,
	IF( modulosg.modulo = '4' AND modulosg.produto = '3', 'OK', '') AS `3_Contas a Pagar`,
	IF( modulosg.modulo = '5' AND modulosg.produto = '3', 'OK', '') AS `3_Contas a Receber`,
	IF( modulosg.modulo = '23' AND modulosg.produto = '3', 'OK', '') AS `3_Controle de Comissao`,
	IF( modulosg.modulo = '24' AND modulosg.produto = '3', 'OK', '') AS `3_Compras de Industrias/Distribuidoras`,
	IF( modulosg.modulo = '22' AND modulosg.produto = '3', 'OK', '') AS `3_Controle de Ticket/Cartao`,
	IF( modulosg.modulo = '6' AND modulosg.produto = '3', 'OK', '') AS `3_Resumo de Caixa`,
	IF( modulosg.modulo = '40' AND modulosg.produto = '3', 'OK', '') AS `3_Escrita Fiscal`,
	IF( modulosg.modulo = '34' AND modulosg.produto = '3', 'OK', '') AS `3_Apoio Contabil`,
	IF( modulosg.modulo = '56' AND modulosg.produto = '3', 'OK', '') AS `3_Controle Gerencial`,
	IF( modulosg.modulo = '21' AND modulosg.produto = '3', 'OK', '') AS `3_Controle de Despesas`,
	IF( modulosg.modulo = '20' AND modulosg.produto = '3', 'OK', '') AS `3_Contas Bancarias`,
	IF( modulosg.modulo = '12' AND modulosg.produto = '3', 'OK', '') AS `3_Controle de Cheques`,
	IF( modulosg.modulo = '26' AND modulosg.produto = '3', 'OK', '') AS `3_Inventario Fiscal`,
	IF( modulosg.modulo = '42' AND modulosg.produto = '3', 'OK', '') AS `3_Fluxo de Caixa`,
	IF( modulosg.modulo = '103' AND modulosg.produto = '3', 'OK', '') AS `3_Autopagamento`,
	IF( modulosg.modulo = '106' AND modulosg.produto = '3', 'OK', '') AS `3_Autopagamento - Demo`,
	IF( modulosg.modulo = '74' AND modulosg.produto = '3', 'OK', '') AS `3_SAT`,
	IF( modulosg.modulo = '104' AND modulosg.produto = '3', 'OK', '') AS `3_Scanntech`,
	IF( modulosg.modulo = '107' AND modulosg.produto = '3', 'OK', '') AS `3_Contribuicao Solidaria`,
	IF( modulosg.modulo = '29' AND modulosg.produto = '3', 'OK', '') AS `3_Levantamento Parcial de Estoque`,
	IF( modulosg.modulo = '13' AND modulosg.produto = '3', 'OK', '') AS `3_Inventario Fisico ( Balanco)`,
	IF( modulosg.modulo = '41' AND modulosg.produto = '3', 'OK', '') AS `3_Fidelizacao`,
	IF( modulosg.modulo = '33' AND modulosg.produto = '3', 'OK', '') AS `3_Transferencia`,
	IF( modulosg.modulo = '120' AND modulosg.produto = '3', 'OK', '') AS `3_PLAY VIEW`,
	IF( modulosg.modulo = '125' AND modulosg.produto = '3', 'OK', '') AS `3_Fidelizi`,
	IF( modulosg.modulo = '133' AND modulosg.produto = '3', 'OK', '') AS `3_Google Maps`,
	IF( modulosg.modulo = '135' AND modulosg.produto = '3', 'OK', '') AS `3_Donuz`,
	IF( modulosg.modulo = '139' AND modulosg.produto = '3', 'OK', '') AS `3_Emissao de Boletos`,
	IF( modulosg.modulo = '141' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao SIMPLUS`,
	IF( modulosg.modulo = '137' AND modulosg.produto = '3', 'OK', '') AS `3_Troco Simples`,
	IF( modulosg.modulo = '132' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao XML SetUP - SGDFE GETCARD`,
	IF( modulosg.modulo = '146' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Area Central - REDE`,
	IF( modulosg.modulo = '147' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Area Central - ASSOCIADO`,
	IF( modulosg.modulo = '130' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Site Mercado`,
	IF( modulosg.modulo = '162' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Neemo`,
	IF( modulosg.modulo = '164' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao IFOOD`,
	IF( modulosg.modulo = '165' AND modulosg.produto = '3', 'OK', '') AS `3_Conciliacao de cartoes - VIZZO`,
	IF( modulosg.modulo = '166' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao RAPPI`,
	IF( modulosg.modulo = '167' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Nexfood`,
	IF( modulosg.modulo = '108' AND modulosg.produto = '3', 'OK', '') AS `3_Conciliacao de cartoes - Conciflex`,
	IF( modulosg.modulo = '171' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Tray`,
	IF( modulosg.modulo = '172' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Auditto`,
	IF( modulosg.modulo = '294' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Dominio XML`,
	IF( modulosg.modulo = '253' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Shipay`,
	IF( modulosg.modulo = '173' AND modulosg.produto = '3', 'OK', '') AS `3_Senha PDV por PINPAD - SITEF TUICCS`,
	IF( modulosg.modulo = '176' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao SG SISTEMAS`,
	IF( modulosg.modulo = '312' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao PagPix`,
	IF( modulosg.modulo = '326' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Anota Ai`,
	IF( modulosg.modulo = '117' AND modulosg.produto = '3', 'OK', '') AS `3_Mix Fiscal`,
	IF( modulosg.modulo = '174' AND modulosg.produto = '3', 'OK', '') AS `3_Integracao Cresce Vendas`,
	IF( modulosg.modulo = '1' AND modulosg.produto = '4', 'OK', '') AS `4_Produtos e Precos`,
	IF( modulosg.modulo = '2' AND modulosg.produto = '4', 'OK', '') AS `4_Fornecedores`,
	IF( modulosg.modulo = '3' AND modulosg.produto = '4', 'OK', '') AS `4_Clientes`,
	IF( modulosg.modulo = '57' AND modulosg.produto = '4', 'OK', '') AS `4_Quartos`,
	IF( modulosg.modulo = '49' AND modulosg.produto = '4', 'OK', '') AS `4_Balcao`,
	IF( modulosg.modulo = '53' AND modulosg.produto = '4', 'OK', '') AS `4_Cartao`,
	IF( modulosg.modulo = '52' AND modulosg.produto = '4', 'OK', '') AS `4_Producao para entrega`,
	IF( modulosg.modulo = '14' AND modulosg.produto = '4', 'OK', '') AS `4_Movimentacao de Produtos`,
	IF( modulosg.modulo = '15' AND modulosg.produto = '4', 'OK', '') AS `4_Entrada de Notas`,
	IF( modulosg.modulo = '19' AND modulosg.produto = '4', 'OK', '') AS `4_Controle de Producao`,
	IF( modulosg.modulo = '30' AND modulosg.produto = '4', 'OK', '') AS `4_Movimento de Caixa`,
	IF( modulosg.modulo = '4' AND modulosg.produto = '4', 'OK', '') AS `4_Contas a Pagar`,
	IF( modulosg.modulo = '5' AND modulosg.produto = '4', 'OK', '') AS `4_Contas a Receber`,
	IF( modulosg.modulo = '23' AND modulosg.produto = '4', 'OK', '') AS `4_Controle de Comissao`,
	IF( modulosg.modulo = '24' AND modulosg.produto = '4', 'OK', '') AS `4_Compras de Industrias/Distribuidoras`,
	IF( modulosg.modulo = '40' AND modulosg.produto = '4', 'OK', '') AS `4_Escrita Fiscal`,
	IF( modulosg.modulo = '34' AND modulosg.produto = '4', 'OK', '') AS `4_Apoio Contabil`,
	IF( modulosg.modulo = '56' AND modulosg.produto = '4', 'OK', '') AS `4_Controle Gerencial`,
	IF( modulosg.modulo = '20' AND modulosg.produto = '4', 'OK', '') AS `4_Contas Bancarias`,
	IF( modulosg.modulo = '12' AND modulosg.produto = '4', 'OK', '') AS `4_Controle de Cheques`,
	IF( modulosg.modulo = '26' AND modulosg.produto = '4', 'OK', '') AS `4_Inventario Fiscal`,
	IF( modulosg.modulo = '42' AND modulosg.produto = '4', 'OK', '') AS `4_Fluxo de Caixa`,
	IF( modulosg.modulo = '62' AND modulosg.produto = '12', 'OK', '') AS `12_TEF SITEF - VPN GSURF`,
	IF( modulosg.modulo = '63' AND modulosg.produto = '12', 'OK', '') AS `12_TEF SCOPE ITAUTEC LOCAL`,
	IF( modulosg.modulo = '64' AND modulosg.produto = '12', 'OK', '') AS `12_TEF SCOPE ITAUTEC GETCARD`,
	IF( modulosg.modulo = '127' AND modulosg.produto = '12', 'OK', '') AS `12_TEF SCOPE INTEGRACAO GETCARD`,
	IF( modulosg.modulo = '65' AND modulosg.produto = '12', 'OK', '') AS `12_TEFWAY`,
	IF( modulosg.modulo = '66' AND modulosg.produto = '12', 'OK', '') AS `12_TEF SMART`,
	IF( modulosg.modulo = '69' AND modulosg.produto = '12', 'OK', '') AS `12_TEF SITEF - TEFWAY`,
	IF( modulosg.modulo = '70' AND modulosg.produto = '12', 'OK', '') AS `12_TEF SITEF - OUTROS`,
	IF( modulosg.modulo = '144' AND modulosg.produto = '12', 'OK', '') AS `12_TEF REDE (SITEF)`,
	IF( modulosg.modulo = '342' AND modulosg.produto = '12', 'OK', '') AS `12_TEF REDE (SITEF - TLS FISERV)`,
	IF( modulosg.modulo = '352' AND modulosg.produto = '12', 'OK', '') AS `12_TEF REDE (SITEF - S.E.CONDUCTOR)`,
	IF( modulosg.modulo = '351' AND modulosg.produto = '12', 'OK', '') AS `12_TEF REDE (SITEF - TLS FISERV - S.E.CONDUCTOR)`,
	IF( modulosg.modulo = '145' AND modulosg.produto = '12', 'OK', '') AS `12_TEF CLOUD (SITEF)`,
	IF( modulosg.modulo = '336' AND modulosg.produto = '12', 'OK', '') AS `12_TEF CLOUD (SITEF - TLS FISERV)`,
	IF( modulosg.modulo = '350' AND modulosg.produto = '12', 'OK', '') AS `12_TEF CLOUD (SITEF - S.E.CONDUCTOR)`,
	IF( modulosg.modulo = '349' AND modulosg.produto = '12', 'OK', '') AS `12_TEF CLOUD (SITEF - TLS FISERV - S.E.CONDUCTOR)`,
	IF( modulosg.modulo = '210' AND modulosg.produto = '12', 'OK', '') AS `12_TEF CLOUD GETCARD (SITEF)`,
	IF( modulosg.modulo = '285' AND modulosg.produto = '12', 'OK', '') AS `12_TEF CLOUD (SITEF) - CNPJ SG`,
	IF( modulosg.modulo = '286' AND modulosg.produto = '12', 'OK', '') AS `12_TEF CLOUD GETCARD (SITEF) - CNPJ SG`,
	IF( modulosg.modulo = '11' AND modulosg.produto = '20', 'OK', '') AS `20_Vendas`,
	IF( modulosg.modulo = '79' AND modulosg.produto = '20', 'OK', '') AS `20_Ajuste de Estoque`,
	IF( modulosg.modulo = '82' AND modulosg.produto = '20', 'OK', '') AS `20_Caixas e bancos`,
	IF( modulosg.modulo = '1' AND modulosg.produto = '20', 'OK', '') AS `20_Produtos`,
	IF( modulosg.modulo = '86' AND modulosg.produto = '20', 'OK', '') AS `20_Clientes e fornecedores`,
	IF( modulosg.modulo = '88' AND modulosg.produto = '20', 'OK', '') AS `20_Vendedores-Usuario`,
	IF( modulosg.modulo = '94' AND modulosg.produto = '20', 'OK', '') AS `20_CFOP`,
	IF( modulosg.modulo = '99' AND modulosg.produto = '20', 'OK', '') AS `20_Grupo de imposto`,
	IF( modulosg.modulo = '76' AND modulosg.produto = '20', 'OK', '') AS `20_Orcamentos`,
	IF( modulosg.modulo = '77' AND modulosg.produto = '20', 'OK', '') AS `20_Consignado`,
	IF( modulosg.modulo = '78' AND modulosg.produto = '20', 'OK', '') AS `20_Multipedido`,
	IF( modulosg.modulo = '24' AND modulosg.produto = '20', 'OK', '') AS `20_Compras`,
	IF( modulosg.modulo = '13' AND modulosg.produto = '20', 'OK', '') AS `20_Balanco`,
	IF( modulosg.modulo = '5' AND modulosg.produto = '20', 'OK', '') AS `20_Contas a receber`,
	IF( modulosg.modulo = '4' AND modulosg.produto = '20', 'OK', '') AS `20_Contas a pagar`,
	IF( modulosg.modulo = '87' AND modulosg.produto = '20', 'OK', '') AS `20_Fabricantes`,
	IF( modulosg.modulo = '89' AND modulosg.produto = '20', 'OK', '') AS `20_Transportadora`,
	IF( modulosg.modulo = '90' AND modulosg.produto = '20', 'OK', '') AS `20_Condicao de pagamento`,
	IF( modulosg.modulo = '91' AND modulosg.produto = '20', 'OK', '') AS `20_ICMS por estado`,
	IF( modulosg.modulo = '92' AND modulosg.produto = '20', 'OK', '') AS `20_Cadastros diversos`,
	IF( modulosg.modulo = '93' AND modulosg.produto = '20', 'OK', '') AS `20_Vencimento`,
	IF( modulosg.modulo = '95' AND modulosg.produto = '20', 'OK', '') AS `20_Contabilista`,
	IF( modulosg.modulo = '96' AND modulosg.produto = '20', 'OK', '') AS `20_Impressora fiscal`,
	IF( modulosg.modulo = '80' AND modulosg.produto = '20', 'OK', '') AS `20_Pedido de compras`,
	IF( modulosg.modulo = '81' AND modulosg.produto = '20', 'OK', '') AS `20_Transformacao`,
	IF( modulosg.modulo = '33' AND modulosg.produto = '20', 'OK', '') AS `20_Transferencia`,
	IF( modulosg.modulo = '83' AND modulosg.produto = '20', 'OK', '') AS `20_Cheques proprio`,
	IF( modulosg.modulo = '84' AND modulosg.produto = '20', 'OK', '') AS `20_Cheques terceiros`,
	IF( modulosg.modulo = '85' AND modulosg.produto = '20', 'OK', '') AS `20_Bordero`,
	IF( modulosg.modulo = '97' AND modulosg.produto = '20', 'OK', '') AS `20_Tabela de precos`,
	IF( modulosg.modulo = '98' AND modulosg.produto = '20', 'OK', '') AS `20_Cartao de credito`,
	IF( modulosg.modulo = '100' AND modulosg.produto = '20', 'OK', '') AS `20_Plano de contas`,
	IF( modulosg.modulo = '39' AND modulosg.produto = '20', 'OK', '') AS `20_Veiculos`,
	IF( modulosg.modulo = '101' AND modulosg.produto = '20', 'OK', '') AS `20_Ordem de servico`,
	IF( modulosg.modulo = '102' AND modulosg.produto = '20', 'OK', '') AS `20_Locacao`,
	IF( modulosg.modulo = '105' AND modulosg.produto = '20', 'OK', '') AS `20_Equipamentos`,
	IF( modulosg.modulo = '74' AND modulosg.produto = '20', 'OK', '') AS `20_SAT`,
	IF( modulosg.modulo = '112' AND modulosg.produto = '20', 'OK', '') AS `20_MonitoraNFE`,
	IF( modulosg.modulo = '9' AND modulosg.produto = '20', 'OK', '') AS `20_Contra Vales`,
	IF( modulosg.modulo = '37' AND modulosg.produto = '20', 'OK', '') AS `20_Controle Patrimonial`,
	IF( modulosg.modulo = '123' AND modulosg.produto = '20', 'OK', '') AS `20_Integracao TEF Scope`,
	IF( modulosg.modulo = '209' AND modulosg.produto = '20', 'OK', '') AS `20_Controle de perdas`,
	IF( modulosg.modulo = '251' AND modulosg.produto = '20', 'OK', '') AS `20_Controle de despesas`,
	IF( modulosg.modulo = '252' AND modulosg.produto = '20', 'OK', '') AS `20_Arquivos Fiscais`,
	IF( modulosg.modulo = '290' AND modulosg.produto = '21', 'OK', '') AS `21_SGDFE SG GETCARD`,
	IF( modulosg.modulo = '290' AND modulosg.produto = '22', 'OK', '') AS `22_SGDFE SG GETCARD`,
	IF( modulosg.modulo = '113' AND modulosg.produto = '23', 'OK', '') AS `23_KW`,
	IF( modulosg.modulo = '114' AND modulosg.produto = '23', 'OK', '') AS `23_RJK`,
	IF( modulosg.modulo = '138' AND modulosg.produto = '34', 'OK', '') AS `34_Controle de Pontos`,
	IF( modulosg.modulo = '149' AND modulosg.produto = '34', 'OK', '') AS `34_Repasse`,
	IF( modulosg.modulo = '156' AND modulosg.produto = '34', 'OK', '') AS `34_Controle de Cashback`,
	IF( modulosg.modulo = '292' AND modulosg.produto = '34', 'OK', '') AS `34_Controle de Pontos com Oferta por Cashback`,
	IF( modulosg.modulo = '293' AND modulosg.produto = '34', 'OK', '') AS `34_Controle de Ofertas`,
	IF( modulosg.modulo = '223' AND modulosg.produto = '39', 'OK', '') AS `39_Alteracoes`,
	IF( modulosg.modulo = '216' AND modulosg.produto = '39', 'OK', '') AS `39_Cadastro de Tabela de Precos`,
	IF( modulosg.modulo = '274' AND modulosg.produto = '39', 'OK', '') AS `39_Cadastro de Clientes e Funcionarios`,
	IF( modulosg.modulo = '186' AND modulosg.produto = '39', 'OK', '') AS `39_Cadastro de Fornecedores`,
	IF( modulosg.modulo = '184' AND modulosg.produto = '39', 'OK', '') AS `39_Cadastro de Produtos`,
	IF( modulosg.modulo = '187' AND modulosg.produto = '39', 'OK', '') AS `39_Controle Caixa`,
	IF( modulosg.modulo = '188' AND modulosg.produto = '39', 'OK', '') AS `39_Controle de Estoque-Quantidade/Grade/Cor`,
	IF( modulosg.modulo = '183' AND modulosg.produto = '39', 'OK', '') AS `39_DashBoards`,
	IF( modulosg.modulo = '275' AND modulosg.produto = '39', 'OK', '') AS `39_Emissao de SAT / MFE`,
	IF( modulosg.modulo = '328' AND modulosg.produto = '39', 'OK', '') AS `39_Emissao de MDF-e`,
	IF( modulosg.modulo = '329' AND modulosg.produto = '39', 'OK', '') AS `39_Emissao de NFS-e`,
	IF( modulosg.modulo = '190' AND modulosg.produto = '39', 'OK', '') AS `39_Entrada de notas por XML`,
	IF( modulosg.modulo = '189' AND modulosg.produto = '39', 'OK', '') AS `39_Etiquetas`,
	IF( modulosg.modulo = '248' AND modulosg.produto = '39', 'OK', '') AS `39_Nota Avulsa`,
	IF( modulosg.modulo = '224' AND modulosg.produto = '39', 'OK', '') AS `39_Recibo Avulso`,
	IF( modulosg.modulo = '205' AND modulosg.produto = '39', 'OK', '') AS `39_Relatorios Dinamicos`,
	IF( modulosg.modulo = '202' AND modulosg.produto = '39', 'OK', '') AS `39_Cartao Presente`,
	IF( modulosg.modulo = '196' AND modulosg.produto = '39', 'OK', '') AS `39_Consignado`,
	IF( modulosg.modulo = '199' AND modulosg.produto = '39', 'OK', '') AS `39_Contas a Pagar`,
	IF( modulosg.modulo = '200' AND modulosg.produto = '39', 'OK', '') AS `39_Contas a Receber`,
	IF( modulosg.modulo = '192' AND modulosg.produto = '39', 'OK', '') AS `39_Controle de Manequim`,
	IF( modulosg.modulo = '194' AND modulosg.produto = '39', 'OK', '') AS `39_Controle de Metas`,
	IF( modulosg.modulo = '277' AND modulosg.produto = '39', 'OK', '') AS `39_Controle de Trocas`,
	IF( modulosg.modulo = '278' AND modulosg.produto = '39', 'OK', '') AS `39_Devolucoes de venda`,
	IF( modulosg.modulo = '204' AND modulosg.produto = '39', 'OK', '') AS `39_Promocoes`,
	IF( modulosg.modulo = '235' AND modulosg.produto = '39', 'OK', '') AS `39_Vale para Funcionario`,
	IF( modulosg.modulo = '191' AND modulosg.produto = '39', 'OK', '') AS `39_Crediario`,
	IF( modulosg.modulo = '193' AND modulosg.produto = '39', 'OK', '') AS `39_Clube de fidelizacao (Pontos)`,
	IF( modulosg.modulo = '195' AND modulosg.produto = '39', 'OK', '') AS `39_Comissao: Por Valor,Produto e Escalonado`,
	IF( modulosg.modulo = '218' AND modulosg.produto = '39', 'OK', '') AS `39_Emissao de Boletos`,
	IF( modulosg.modulo = '280' AND modulosg.produto = '39', 'OK', '') AS `39_Inventario de Estoque (Parcial ou Total)`,
	IF( modulosg.modulo = '245' AND modulosg.produto = '39', 'OK', '') AS `39_Movimentacao de Cheques`,
	IF( modulosg.modulo = '203' AND modulosg.produto = '39', 'OK', '') AS `39_Venda Ambulante/Sacoleiras`,
	IF( modulosg.modulo = '281' AND modulosg.produto = '39', 'OK', '') AS `39_Bancario`,
	IF( modulosg.modulo = '244' AND modulosg.produto = '39', 'OK', '') AS `39_Contrato de Cartao de Credito`,
	IF( modulosg.modulo = '206' AND modulosg.produto = '39', 'OK', '') AS `39_D.R.E`,
	IF( modulosg.modulo = '282' AND modulosg.produto = '39', 'OK', '') AS `39_Despesas`,
	IF( modulosg.modulo = '284' AND modulosg.produto = '39', 'OK', '') AS `39_Gerenciamento`,
	IF( modulosg.modulo = '221' AND modulosg.produto = '39', 'OK', '') AS `39_PDV OFFLINE`,
	IF( modulosg.modulo = '283' AND modulosg.produto = '39', 'OK', '') AS `39_Multilojas - Requisicao/Transferencia`,
	IF( modulosg.modulo = '289' AND modulosg.produto = '39', 'OK', '') AS `39_Catalogo`,
	IF( modulosg.modulo = '297' AND modulosg.produto = '39', 'OK', '') AS `39_Producao`,
	IF( modulosg.modulo = '298' AND modulosg.produto = '39', 'OK', '') AS `39_Fracionamento`,
	IF( modulosg.modulo = '324' AND modulosg.produto = '39', 'OK', '') AS `39_Inventario fiscal`,
	IF( modulosg.modulo = '325' AND modulosg.produto = '39', 'OK', '') AS `39_Escrita fiscal`,
	IF( modulosg.modulo = '171' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Tray`,
	IF( modulosg.modulo = '317' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao PlugLead`,
	IF( modulosg.modulo = '318' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Magazord`,
	IF( modulosg.modulo = '319' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Nuvem Shop`,
	IF( modulosg.modulo = '321' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Shopify`,
	IF( modulosg.modulo = '253' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Shipay`,
	IF( modulosg.modulo = '323' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Loja Integrada`,
	IF( modulosg.modulo = '327' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Correios`,
	IF( modulosg.modulo = '330' AND modulosg.produto = '39', 'OK', '') AS `39_Compras`,
	IF( modulosg.modulo = '331' AND modulosg.produto = '39', 'OK', '') AS `39_Cotacao`,
	IF( modulosg.modulo = '332' AND modulosg.produto = '39', 'OK', '') AS `39_Cotacao Online`,
	IF( modulosg.modulo = '108' AND modulosg.produto = '39', 'OK', '') AS `39_Conciliacao de cartoes - Conciflex`,
	IF( modulosg.modulo = '159' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao APPMercados`,
	IF( modulosg.modulo = '163' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao LOJAQUI`,
	IF( modulosg.modulo = '180' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Compre Facil`,
	IF( modulosg.modulo = '181' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Insta Buy`,
	IF( modulosg.modulo = '182' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Deju`,
	IF( modulosg.modulo = '254' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Smart`,
	IF( modulosg.modulo = '301' AND modulosg.produto = '39', 'OK', '') AS `39_Homologacao Integradores`,
	IF( modulosg.modulo = '308' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Minus`,
	IF( modulosg.modulo = '311' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Supermercado Esperanca`,
	IF( modulosg.modulo = '313' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Ad Rocket`,
	IF( modulosg.modulo = '320' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Area Central - API`,
	IF( modulosg.modulo = '174' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Cresce Vendas`,
	IF( modulosg.modulo = '322' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao TI Soluti`,
	IF( modulosg.modulo = '333' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Izi App`,
	IF( modulosg.modulo = '312' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao PagPix`,
	IF( modulosg.modulo = '343' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Cartaz Facil`,
	IF( modulosg.modulo = '256' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Web Jasper`,
	IF( modulosg.modulo = '344' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Dattion`,
	IF( modulosg.modulo = '345' AND modulosg.produto = '39', 'OK', '') AS `39_Integracao Codevops`,
	IF( modulosg.modulo = '107' AND modulosg.produto = '39', 'OK', '') AS `39_Contribuicao Solidaria`,
	IF( modulosg.modulo = '101' AND modulosg.produto = '39', 'OK', '') AS `39_Ordem de Servico`,
	IF( modulosg.modulo = '151' AND modulosg.produto = '42', 'OK', '') AS `42_Iti - Itau`,
	IF( modulosg.modulo = '304' AND modulosg.produto = '46', 'OK', '') AS `46_GOMenu Consulta (QR Code somente para consulta)`,
	IF( modulosg.modulo = '305' AND modulosg.produto = '46', 'OK', '') AS `46_GOMenu Delivery (Delivery)`,
	IF( modulosg.modulo = '306' AND modulosg.produto = '46', 'OK', '') AS `46_GOMenu Mobile (Consulta + pedido pelo celular do c`,
	IF( modulosg.modulo = '307' AND modulosg.produto = '46', 'OK', '') AS `46_GOMenu Pedido (Tablet na mesa)`,
	IF( modulosg.modulo = '223' AND modulosg.produto = '48', 'OK', '') AS `48_Alteracoes`,
	IF( modulosg.modulo = '216' AND modulosg.produto = '48', 'OK', '') AS `48_Cadastro de Tabela de Precos`,
	IF( modulosg.modulo = '274' AND modulosg.produto = '48', 'OK', '') AS `48_Cadastro de Clientes e Funcionarios`,
	IF( modulosg.modulo = '186' AND modulosg.produto = '48', 'OK', '') AS `48_Cadastro de Fornecedores`,
	IF( modulosg.modulo = '184' AND modulosg.produto = '48', 'OK', '') AS `48_Cadastro de Produtos`,
	IF( modulosg.modulo = '187' AND modulosg.produto = '48', 'OK', '') AS `48_Controle Caixa`,
	IF( modulosg.modulo = '188' AND modulosg.produto = '48', 'OK', '') AS `48_Controle de Estoque-Quantidade/Grade/Cor`,
	IF( modulosg.modulo = '183' AND modulosg.produto = '48', 'OK', '') AS `48_DashBoards`,
	IF( modulosg.modulo = '275' AND modulosg.produto = '48', 'OK', '') AS `48_Emissao de SAT / MFE`,
	IF( modulosg.modulo = '328' AND modulosg.produto = '48', 'OK', '') AS `48_Emissao de MDF-e`,
	IF( modulosg.modulo = '329' AND modulosg.produto = '48', 'OK', '') AS `48_Emissao de NFS-e`,
	IF( modulosg.modulo = '190' AND modulosg.produto = '48', 'OK', '') AS `48_Entrada de notas por XML`,
	IF( modulosg.modulo = '189' AND modulosg.produto = '48', 'OK', '') AS `48_Etiquetas`,
	IF( modulosg.modulo = '248' AND modulosg.produto = '48', 'OK', '') AS `48_Nota Avulsa`,
	IF( modulosg.modulo = '224' AND modulosg.produto = '48', 'OK', '') AS `48_Recibo Avulso`,
	IF( modulosg.modulo = '205' AND modulosg.produto = '48', 'OK', '') AS `48_Relatorios Dinamicos`,
	IF( modulosg.modulo = '202' AND modulosg.produto = '48', 'OK', '') AS `48_Cartao Presente`,
	IF( modulosg.modulo = '196' AND modulosg.produto = '48', 'OK', '') AS `48_Consignado`,
	IF( modulosg.modulo = '199' AND modulosg.produto = '48', 'OK', '') AS `48_Contas a Pagar`,
	IF( modulosg.modulo = '200' AND modulosg.produto = '48', 'OK', '') AS `48_Contas a Receber`,
	IF( modulosg.modulo = '192' AND modulosg.produto = '48', 'OK', '') AS `48_Controle de Manequim`,
	IF( modulosg.modulo = '194' AND modulosg.produto = '48', 'OK', '') AS `48_Controle de Metas`,
	IF( modulosg.modulo = '277' AND modulosg.produto = '48', 'OK', '') AS `48_Controle de Trocas`,
	IF( modulosg.modulo = '278' AND modulosg.produto = '48', 'OK', '') AS `48_Devolucoes de venda`,
	IF( modulosg.modulo = '204' AND modulosg.produto = '48', 'OK', '') AS `48_Promocoes`,
	IF( modulosg.modulo = '235' AND modulosg.produto = '48', 'OK', '') AS `48_Vale para Funcionario`,
	IF( modulosg.modulo = '191' AND modulosg.produto = '48', 'OK', '') AS `48_Crediario`,
	IF( modulosg.modulo = '193' AND modulosg.produto = '48', 'OK', '') AS `48_Clube de fidelizacao (Pontos)`,
	IF( modulosg.modulo = '195' AND modulosg.produto = '48', 'OK', '') AS `48_Comissao: Por Valor,Produto e Escalonado`,
	IF( modulosg.modulo = '218' AND modulosg.produto = '48', 'OK', '') AS `48_Emissao de Boletos`,
	IF( modulosg.modulo = '280' AND modulosg.produto = '48', 'OK', '') AS `48_Inventario de Estoque (Parcial ou Total)`,
	IF( modulosg.modulo = '245' AND modulosg.produto = '48', 'OK', '') AS `48_Movimentacao de Cheques`,
	IF( modulosg.modulo = '203' AND modulosg.produto = '48', 'OK', '') AS `48_Venda Ambulante/Sacoleiras`,
	IF( modulosg.modulo = '281' AND modulosg.produto = '48', 'OK', '') AS `48_Bancario`,
	IF( modulosg.modulo = '244' AND modulosg.produto = '48', 'OK', '') AS `48_Contrato de Cartao de Credito`,
	IF( modulosg.modulo = '206' AND modulosg.produto = '48', 'OK', '') AS `48_D.R.E`,
	IF( modulosg.modulo = '282' AND modulosg.produto = '48', 'OK', '') AS `48_Despesas`,
	IF( modulosg.modulo = '284' AND modulosg.produto = '48', 'OK', '') AS `48_Gerenciamento`,
	IF( modulosg.modulo = '221' AND modulosg.produto = '48', 'OK', '') AS `48_PDV OFFLINE`,
	IF( modulosg.modulo = '283' AND modulosg.produto = '48', 'OK', '') AS `48_Multilojas - Requisicao/Transferencia`,
	IF( modulosg.modulo = '289' AND modulosg.produto = '48', 'OK', '') AS `48_Catalogo`,
	IF( modulosg.modulo = '297' AND modulosg.produto = '48', 'OK', '') AS `48_Producao`,
	IF( modulosg.modulo = '298' AND modulosg.produto = '48', 'OK', '') AS `48_Fracionamento`,
	IF( modulosg.modulo = '324' AND modulosg.produto = '48', 'OK', '') AS `48_Invetario fiscal`,
	IF( modulosg.modulo = '325' AND modulosg.produto = '48', 'OK', '') AS `48_Escrita fiscal`,
	IF( modulosg.modulo = '171' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Tray`,
	IF( modulosg.modulo = '317' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao PlugLead`,
	IF( modulosg.modulo = '318' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Magazord`,
	IF( modulosg.modulo = '319' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Nuvem Shop`,
	IF( modulosg.modulo = '321' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Shopify`,
	IF( modulosg.modulo = '253' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Shipay`,
	IF( modulosg.modulo = '323' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Loja Integrada`,
	IF( modulosg.modulo = '327' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Correios`,
	IF( modulosg.modulo = '330' AND modulosg.produto = '48', 'OK', '') AS `48_Compras`,
	IF( modulosg.modulo = '331' AND modulosg.produto = '48', 'OK', '') AS `48_Cotacao`,
	IF( modulosg.modulo = '332' AND modulosg.produto = '48', 'OK', '') AS `48_Cotacao Online`,
	IF( modulosg.modulo = '108' AND modulosg.produto = '48', 'OK', '') AS `48_Conciliacao de cartoes - Conciflex`,
	IF( modulosg.modulo = '159' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao APPMercados`,
	IF( modulosg.modulo = '163' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao LOJAQUI`,
	IF( modulosg.modulo = '180' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Compre Facil`,
	IF( modulosg.modulo = '181' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Insta Buy`,
	IF( modulosg.modulo = '182' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Deju`,
	IF( modulosg.modulo = '254' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Smart`,
	IF( modulosg.modulo = '301' AND modulosg.produto = '48', 'OK', '') AS `48_Homologacao Integradores`,
	IF( modulosg.modulo = '308' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Minus`,
	IF( modulosg.modulo = '311' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Supermercado Esperanca`,
	IF( modulosg.modulo = '313' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Ad Rocket`,
	IF( modulosg.modulo = '320' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Area Central - API`,
	IF( modulosg.modulo = '174' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Cresce Vendas`,
	IF( modulosg.modulo = '322' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao TI Soluti`,
	IF( modulosg.modulo = '333' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Izi App`,
	IF( modulosg.modulo = '312' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao PagPix`,
	IF( modulosg.modulo = '343' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Cartaz Facil`,
	IF( modulosg.modulo = '256' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Web Jasper`,
	IF( modulosg.modulo = '344' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Dattion`,
	IF( modulosg.modulo = '345' AND modulosg.produto = '48', 'OK', '') AS `48_Integracao Codevops`,
	IF( modulosg.modulo = '107' AND modulosg.produto = '48', 'OK', '') AS `48_Contribuicao Solidaria`,
	IF( modulosg.modulo = '101' AND modulosg.produto = '48', 'OK', '') AS `48_Ordem de Servico`,
	IF( modulosg.modulo = '223' AND modulosg.produto = '50', 'OK', '') AS `50_Alteracoes`,
	IF( modulosg.modulo = '216' AND modulosg.produto = '50', 'OK', '') AS `50_Cadastro de Tabela de Precos`,
	IF( modulosg.modulo = '274' AND modulosg.produto = '50', 'OK', '') AS `50_Cadastro de Clientes e Funcionarios`,
	IF( modulosg.modulo = '186' AND modulosg.produto = '50', 'OK', '') AS `50_Cadastro de Fornecedores`,
	IF( modulosg.modulo = '184' AND modulosg.produto = '50', 'OK', '') AS `50_Cadastro de Produtos`,
	IF( modulosg.modulo = '187' AND modulosg.produto = '50', 'OK', '') AS `50_Controle Caixa`,
	IF( modulosg.modulo = '188' AND modulosg.produto = '50', 'OK', '') AS `50_Controle de Estoque-Quantidade/Grade/Cor`,
	IF( modulosg.modulo = '183' AND modulosg.produto = '50', 'OK', '') AS `50_DashBoards`,
	IF( modulosg.modulo = '275' AND modulosg.produto = '50', 'OK', '') AS `50_Emissao de SAT / MFE`,
	IF( modulosg.modulo = '328' AND modulosg.produto = '50', 'OK', '') AS `50_Emissao de MDF-e`,
	IF( modulosg.modulo = '329' AND modulosg.produto = '50', 'OK', '') AS `50_Emissao de NFS-e`,
	IF( modulosg.modulo = '190' AND modulosg.produto = '50', 'OK', '') AS `50_Entrada de notas por XML`,
	IF( modulosg.modulo = '189' AND modulosg.produto = '50', 'OK', '') AS `50_Etiquetas`,
	IF( modulosg.modulo = '248' AND modulosg.produto = '50', 'OK', '') AS `50_Nota Avulsa`,
	IF( modulosg.modulo = '224' AND modulosg.produto = '50', 'OK', '') AS `50_Recibo Avulso`,
	IF( modulosg.modulo = '205' AND modulosg.produto = '50', 'OK', '') AS `50_Relatorios Dinamicos`,
	IF( modulosg.modulo = '202' AND modulosg.produto = '50', 'OK', '') AS `50_Cartao Presente`,
	IF( modulosg.modulo = '196' AND modulosg.produto = '50', 'OK', '') AS `50_Consignado`,
	IF( modulosg.modulo = '199' AND modulosg.produto = '50', 'OK', '') AS `50_Contas a Pagar`,
	IF( modulosg.modulo = '200' AND modulosg.produto = '50', 'OK', '') AS `50_Contas a Receber`,
	IF( modulosg.modulo = '192' AND modulosg.produto = '50', 'OK', '') AS `50_Controle de Manequim`,
	IF( modulosg.modulo = '194' AND modulosg.produto = '50', 'OK', '') AS `50_Controle de Metas`,
	IF( modulosg.modulo = '277' AND modulosg.produto = '50', 'OK', '') AS `50_Controle de Trocas`,
	IF( modulosg.modulo = '278' AND modulosg.produto = '50', 'OK', '') AS `50_Devolucoes de venda`,
	IF( modulosg.modulo = '204' AND modulosg.produto = '50', 'OK', '') AS `50_Promocoes`,
	IF( modulosg.modulo = '235' AND modulosg.produto = '50', 'OK', '') AS `50_Vale para Funcionario`,
	IF( modulosg.modulo = '191' AND modulosg.produto = '50', 'OK', '') AS `50_Crediario`,
	IF( modulosg.modulo = '193' AND modulosg.produto = '50', 'OK', '') AS `50_Clube de fidelizacao (Pontos)`,
	IF( modulosg.modulo = '195' AND modulosg.produto = '50', 'OK', '') AS `50_Comissao: Por Valor,Produto e Escalonado`,
	IF( modulosg.modulo = '218' AND modulosg.produto = '50', 'OK', '') AS `50_Emissao de Boletos`,
	IF( modulosg.modulo = '280' AND modulosg.produto = '50', 'OK', '') AS `50_Inventario de Estoque (Parcial ou Total)`,
	IF( modulosg.modulo = '245' AND modulosg.produto = '50', 'OK', '') AS `50_Movimentacao de Cheques`,
	IF( modulosg.modulo = '203' AND modulosg.produto = '50', 'OK', '') AS `50_Venda Ambulante/Sacoleiras`,
	IF( modulosg.modulo = '281' AND modulosg.produto = '50', 'OK', '') AS `50_Bancario`,
	IF( modulosg.modulo = '244' AND modulosg.produto = '50', 'OK', '') AS `50_Contrato de Cartao de Credito`,
	IF( modulosg.modulo = '206' AND modulosg.produto = '50', 'OK', '') AS `50_D.R.E`,
	IF( modulosg.modulo = '282' AND modulosg.produto = '50', 'OK', '') AS `50_Despesas`,
	IF( modulosg.modulo = '284' AND modulosg.produto = '50', 'OK', '') AS `50_Gerenciamento`,
	IF( modulosg.modulo = '221' AND modulosg.produto = '50', 'OK', '') AS `50_PDV OFFLINE`,
	IF( modulosg.modulo = '283' AND modulosg.produto = '50', 'OK', '') AS `50_Multilojas - Requisicao/Transferencia`,
	IF( modulosg.modulo = '289' AND modulosg.produto = '50', 'OK', '') AS `50_Catalogo`,
	IF( modulosg.modulo = '324' AND modulosg.produto = '50', 'OK', '') AS `50_Invetario fiscal`,
	IF( modulosg.modulo = '325' AND modulosg.produto = '50', 'OK', '') AS `50_Escrita fiscal`,
	IF( modulosg.modulo = '171' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Tray`,
	IF( modulosg.modulo = '317' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao PlugLead`,
	IF( modulosg.modulo = '318' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Magazord`,
	IF( modulosg.modulo = '319' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Nuvem Shop`,
	IF( modulosg.modulo = '321' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Shopify`,
	IF( modulosg.modulo = '253' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Shipay`,
	IF( modulosg.modulo = '323' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Loja Integrada`,
	IF( modulosg.modulo = '327' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Correios`,
	IF( modulosg.modulo = '330' AND modulosg.produto = '50', 'OK', '') AS `50_Compras`,
	IF( modulosg.modulo = '331' AND modulosg.produto = '50', 'OK', '') AS `50_Cotacao`,
	IF( modulosg.modulo = '332' AND modulosg.produto = '50', 'OK', '') AS `50_Cotacao Online`,
	IF( modulosg.modulo = '108' AND modulosg.produto = '50', 'OK', '') AS `50_Conciliacao de cartoes - Conciflex`,
	IF( modulosg.modulo = '159' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao APPMercados`,
	IF( modulosg.modulo = '163' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao LOJAQUI`,
	IF( modulosg.modulo = '180' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Compre Facil`,
	IF( modulosg.modulo = '181' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Insta Buy`,
	IF( modulosg.modulo = '182' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Deju`,
	IF( modulosg.modulo = '254' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Smart`,
	IF( modulosg.modulo = '301' AND modulosg.produto = '50', 'OK', '') AS `50_Homologacao Integradores`,
	IF( modulosg.modulo = '308' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Minus`,
	IF( modulosg.modulo = '311' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Supermercado Esperanca`,
	IF( modulosg.modulo = '313' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Ad Rocket`,
	IF( modulosg.modulo = '320' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Area Central - API`,
	IF( modulosg.modulo = '174' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Cresce Vendas`,
	IF( modulosg.modulo = '322' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao TI Soluti`,
	IF( modulosg.modulo = '333' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Izi App`,
	IF( modulosg.modulo = '312' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao PagPix`,
	IF( modulosg.modulo = '343' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Cartaz Facil`,
	IF( modulosg.modulo = '256' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Web Jasper`,
	IF( modulosg.modulo = '344' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Dattion`,
	IF( modulosg.modulo = '345' AND modulosg.produto = '50', 'OK', '') AS `50_Integracao Codevops`,
	IF( modulosg.modulo = '101' AND modulosg.produto = '50', 'OK', '') AS `50_Ordem de Servico`,
	IF( modulosg.modulo = '337' AND modulosg.produto = '57', 'OK', '') AS `57_NFe`,
	IF( modulosg.modulo = '338' AND modulosg.produto = '57', 'OK', '') AS `57_NFSe`,
	IF( modulosg.modulo = '339' AND modulosg.produto = '57', 'OK', '') AS `57_CTe`,
	IF( modulosg.modulo = '340' AND modulosg.produto = '57', 'OK', '') AS `57_MDFe`,
	IF( modulosg.modulo = '341' AND modulosg.produto = '57', 'OK', '') AS `57_NFCe` FROM modulosg GROUP BY cnpj
)  modulos on
    modulos.CNPJMODULO = sg.cgc
left join (
SELECT cnpj AS CNPJPDV,
SUM(qtdpdv) as "TOTAL_PDVs", 
	IF(p.produto = 1, p.qtdpdv, 0) AS `1_PDVs`,
	IF(p.produto = 2, p.qtdpdv, 0) AS `2_PDVs`,
	IF(p.produto = 3, p.qtdpdv, 0) AS `3_PDVs`,
	IF(p.produto = 38, p.qtdpdv, 0) AS `38_PDVs`,
	IF(p.produto = 39, p.qtdpdv, 0) AS `39_PDVs` 
FROM prodsg p GROUP BY cnpj
)   quantidadesPDV on quantidadesPDV.CNPJPDV = sg.cgc
	left join (		
SELECT cnpj AS CNPJESTACOES,
SUM(qtdestac) as "TOTAL_ESTACOES", 
	IF(p.produto = 2, p.qtdestac, 0) AS `2_ESTACOES`,
	IF(p.produto = 3, p.qtdestac, 0) AS `3_ESTACOES`,
	IF(p.produto = 5, p.qtdestac, 0) AS `5_ESTACOES`,
	IF(p.produto = 6, p.qtdestac, 0) AS `6_ESTACOES`,
	IF(p.produto = 19, p.qtdestac, 0) AS `19_ESTACOES`,
	IF(p.produto = 29, p.qtdestac, 0) AS `29_ESTACOES`,
	IF(p.produto = 39, p.qtdestac, 0) AS `39_ESTACOES`,
	IF(p.produto = 41, p.qtdestac, 0) AS `41_ESTACOES` 
FROM prodsg p GROUP BY cnpj
)   quantidadesESTACOES on quantidadesESTACOES.CNPJESTACOES = sg.cgc
left join (
SELECT cnpj AS CNPJSUBMODULOS, 
if(sum(IF(p.produto = 1 && p.submodulo > 0, 1, 0 )) > 0, s.descricao, '') AS `1_SUBMODULO`,
if(sum(IF(p.produto = 2 && p.submodulo > 0, 1, 0 )) > 0, s.descricao, '') AS `2_SUBMODULO`,
if(sum(IF(p.produto = 3 && p.submodulo > 0, 1, 0 )) > 0, s.descricao, '') AS `3_SUBMODULO`,
if(sum(IF(p.produto = 39 && p.submodulo > 0, 1, 0 )) > 0, s.descricao, '') AS `39_SUBMODULO`
FROM prodsg p
left join submodul s on p.submodulo = s.submodulo GROUP BY cnpj
) submodulos on submodulos.CNPJSUBMODULOS = sg.cgc
) as q