q.empresa,
q.cadcl,
q.fantasia,
q.razaosocial,
q.situacao,
q.datasituacao,
q.datainstalacao,
q.dataultimoreajuste,
q.vendedor,
q.classificacao,
q.representante,
q.representante2,
q.representante3,
q.contato,
q.telefone,
q.valor,
q.cnpj,
q.tecnicoresponsavel,
q.email,
q.tipoempresa,


q.dataPesquisaSatisfacaoCliente,
q.notaPesquisaSatisfacaoCliente,
q.contatoPesquisaSatisfacaoCliente,
q.dataUltimoControleVisita,
q.contatoUltimoControleVisita,
q.totalControleVisita12Meses,
q.dataOSVelha, 
q.tecnicoUltimaVisita,
q.totalOSUltimosDozeMeses,
q.quantidadeOSEmAberto,
q.quantidadeOSEmAbertoBug,
q.quantidadeOSEmAbertoAlteracao,
q.quantidadeOSEmAbertoPendencia

	