(
    select
	sg.empresa as "EMPRESA",
	cc.codcli10 as "CADCL",
	cc.nomefan10 as "FANTASIA",
	cc.razsoc10 as "RAZAOSOCIAL",
	cc.situacao10 as "SITUACAO",
	cc.dtultsit10 as "DATASITUACAO",
	sg.datainstal as "DATAINSTALACAO",
	sg.dtreajuste as "DATAULTIMOREAJUSTE",
	tv.nome as "VENDEDOR",
	ct.descricao as "CLASSIFICACAO",
	tp.desctipo as "REPRESENTANTE",
	tp2.desctipo as "REPRESENTANTE2",
	cc.nomecon10 as "CONTATO",
	cc.fonecli10 as "TELEFONE",
	sr.VALOR,
	SG.cgc as "CNPJ",
	produtos.*,
	modulos.*,
	submodulos.*,
	quantidadesPDV.*,
	quantidadesESTACOES.*,
	cc.vended10 as "TECNICO",
	cc.emailcli10 as "EMAIL",
	case sg.tipo
		 WHEN 'C' THEN "ADMINISTRADORA DE CARTOES" 
         WHEN 'T' THEN "ASSISTENCIA TECNICA"       
         WHEN 'A' THEN "ASSOCIACAO DE COMPRAS"     
         WHEN 'P' THEN "AUTO PECAS"                
         WHEN 'F' THEN "ACOUGUE"                   
         WHEN 'K' THEN "C.D."                      
         WHEN 'V' THEN "CONFECCOES/CALCADOS"       
         WHEN 'D' THEN "DISTRIBUIDORA"             
         WHEN 'I' THEN "IND. PANIFICACAO"          
         WHEN 'L' THEN "LOJA DE DEPARTAMENTOS"     
         WHEN 'M' THEN "MATERIAL DE CONSTRUCAO"    
         WHEN 'B' THEN "MONITORAMENTO DE TELA"     
         WHEN 'J' THEN "OFICINAS MECANICA/ELETRICA"
         WHEN 'G' THEN "PANIFICADORA"              
         WHEN 'N' THEN "PAPELARIA"                 
         WHEN 'R' THEN "RESTAURANTE E SIMILAR"     
         WHEN 'S' THEN "SUPERMERCADO"              
         WHEN 'O' THEN "OUTROS" 
         ELSE          "NAO INFORMADO"  
     end TIPOEMPRESA
from
	sgscli sg
inner join cadcli cc on
	cc.cgccpf10 = sg.cgc
left join tabven tv on
	tv.codigo = cc.vended210
left join catcli ct on
	ct.codigo = sg.codcatcli
inner join tipcli tp on
	tp.codtipo = cc.tipocli10
left join tipcli tp2 on
	tp2.codtipo = sg.parceiro2
left join (
	select
		sc.codcli,
		sum(sc.valor) as VALOR
	from
		sercli sc
	inner join (
		select
			codigo
		from
			tipser
		where
			servrecor is null) tp on
		tp.codigo = sc.codsercli
	group by
		sc.codcli ) sr on
	sr.codcli = cc.codcli10
left join (
    select cnpj as CNPJPRODUTO, 
IF( prodsg.produto = 1, 'OK', '') AS 'SGERP LINUX',
IF( prodsg.produto = 2, 'OK', '') AS 'SGERP WINDOWS',
IF( prodsg.produto = 3, 'OK', '') AS 'SGFOODS',
IF( prodsg.produto = 4, 'OK', '') AS 'SGHOTEL',
IF( prodsg.produto = 14, 'OK', '') AS 'EMULADOR',
IF( prodsg.produto = 15, 'OK', '') AS 'SGCONTABIL',
IF( prodsg.produto = 16, 'OK', '') AS 'SGESTAR',
IF( prodsg.produto = 17, 'OK', '') AS 'SGBLUE EYE',
IF( prodsg.produto = 20, 'OK', '') AS 'SG ANALISE',
IF( prodsg.produto = 23, 'OK', '') AS 'INTEGRACAO PDV',
IF( prodsg.produto = 28, 'OK', '') AS 'SG MAPA FISCAL',
IF( prodsg.produto = 33, 'OK', '') AS 'SGCONCILIADOR',
IF( prodsg.produto = 35, 'OK', '') AS 'INTEGRACAO VSELL MOBILE',
IF( prodsg.produto = 36, 'OK', '') AS 'INTEGRACAO WMW',
IF( prodsg.produto = 42, 'OK', '') AS 'CARTEIRA DIGITAL',
IF( prodsg.produto = 43, 'OK', '') AS 'SG ACESSO',
IF( prodsg.produto = 47, 'OK', '') AS 'SG COMANDA',
IF( prodsg.produto = 48, 'OK', '') AS 'SGMODA',
IF( prodsg.produto = 37, 'OK', '') AS 'EMISSAO 1 NFCE CONTINGENCIA',
IF( prodsg.produto = 5, 'OK', '') AS 'SGMOBILE',
IF( prodsg.produto = 6, 'OK', '') AS 'SGPOCKET',
IF( prodsg.produto = 54, 'OK', '') AS 'MOBI POCKET',
IF( prodsg.produto = 7, 'OK', '') AS 'NFE (TECNOSPEED)',
IF( prodsg.produto = 8, 'OK', '') AS 'NFSE (TECNOSPEED)',
IF( prodsg.produto = 9, 'OK', '') AS 'CTE (TECNOSPEED)',
IF( prodsg.produto = 10, 'OK', '') AS 'MDFE (TECNOSPEED)',
IF( prodsg.produto = 11, 'OK', '') AS 'NFCE (TECNOSPEED)',
IF( prodsg.produto = 12, 'OK', '') AS 'TEF',
IF( prodsg.produto = 13, 'OK', '') AS 'SGMONITORAMENTONOTAS',
IF( prodsg.produto = 18, 'OK', '') AS 'SGNFE WINDOWS',
IF( prodsg.produto = 19, 'OK', '') AS 'SGFOODS MOBILE',
IF( prodsg.produto = 21, 'OK', '') AS 'SG-NFE',
IF( prodsg.produto = 22, 'OK', '') AS 'SG-NFCE',
IF( prodsg.produto = 24, 'OK', '') AS 'NFE-FLEXDOCS',
IF( prodsg.produto = 25, 'OK', '') AS 'NFCE-FLEXDOCS',
IF( prodsg.produto = 26, 'OK', '') AS 'NFSE-FLEXDOCS',
IF( prodsg.produto = 27, 'OK', '') AS 'MDFE-FLEXDOCS',
IF( prodsg.produto = 31, 'OK', '') AS 'GESTAO IMEDIATA',
IF( prodsg.produto = 34, 'OK', '') AS 'APP CLUBE DE DESCONTO',
IF( prodsg.produto = 38, 'OK', '') AS 'SELF-CHECKOUT',
IF( prodsg.produto = 39, 'OK', '') AS 'SGCLOUD',
IF( prodsg.produto = 41, 'OK', '') AS 'FORCA DE VENDAS - HERBIE',
IF( prodsg.produto = 44, 'OK', '') AS 'SG CARTAZ',
IF( prodsg.produto = 45, 'OK', '') AS 'SG VIEW',
IF( prodsg.produto = 46, 'OK', '') AS 'GOMENU',
IF( prodsg.produto = 51, 'OK', '') AS 'PORTAL XML',
IF( prodsg.produto = 52, 'OK', '') AS 'MOBIGESTAO',
IF( prodsg.produto = 53, 'OK', '') AS 'APP PRE VENDA',
IF( prodsg.produto = 55, 'OK', '') AS 'SGBI',
IF( prodsg.produto = 56, 'OK', '') AS 'TISS',
IF( prodsg.produto = 57, 'OK', '') AS 'MANAGER SAAS',
IF( prodsg.produto = 58, 'OK', '') AS 'NFSE (SGCLOUD)' from prodsg group by cnpj
)  produtos on
	produtos.CNPJPRODUTO = sg.cgc
left join (
SELECT cnpj as CNPJMODULO, 
IF( modulosg.modulo = '34' AND modulosg.produto = '1', 'OK', '') AS '34_Apoio Contabil',
IF( modulosg.modulo = '61' AND modulosg.produto = '1', 'OK', '') AS '61_AT&M',
IF( modulosg.modulo = '110' AND modulosg.produto = '1', 'OK', '') AS '110_Atualizacao tributaria - Virtual',
IF( modulosg.modulo = '35' AND modulosg.produto = '1', 'OK', '') AS '35_Balanco Setorial',
IF( modulosg.modulo = '8' AND modulosg.produto = '1', 'OK', '') AS '8_Cartao Ponto',
IF( modulosg.modulo = '12' AND modulosg.produto = '1', 'OK', '') AS '12_Cheque Pre Datados',
IF( modulosg.modulo = '18' AND modulosg.produto = '1', 'OK', '') AS '18_Cheques Devolvidos',
IF( modulosg.modulo = '3' AND modulosg.produto = '1', 'OK', '') AS '3_Clientes',
IF( modulosg.modulo = '23' AND modulosg.produto = '1', 'OK', '') AS '23_Comissao de Vendedores',
IF( modulosg.modulo = '24' AND modulosg.produto = '1', 'OK', '') AS '24_Compras de Ind£strias/Distribuidoras',
IF( modulosg.modulo = '314' AND modulosg.produto = '1', 'OK', '') AS '314_Conciliacao cartoes - Valida Solucoes',
IF( modulosg.modulo = '108' AND modulosg.produto = '1', 'OK', '') AS '108_Conciliacao de cartoes - Conciflex',
IF( modulosg.modulo = '126' AND modulosg.produto = '1', 'OK', '') AS '126_Conciliacao de cartoes - PJM',
IF( modulosg.modulo = '109' AND modulosg.produto = '1', 'OK', '') AS '109_Conciliacao de cartoes - Procard',
IF( modulosg.modulo = '116' AND modulosg.produto = '1', 'OK', '') AS '116_Conciliacao de cartoes - TeiaCard',
IF( modulosg.modulo = '165' AND modulosg.produto = '1', 'OK', '') AS '165_Conciliacao de cartoes - VIZZO',
IF( modulosg.modulo = '47' AND modulosg.produto = '1', 'OK', '') AS '47_Consulta de Apoio Gerencial',
IF( modulosg.modulo = '161' AND modulosg.produto = '1', 'OK', '') AS '161_Contabilidade - Regras Fiscais',
IF( modulosg.modulo = '4' AND modulosg.produto = '1', 'OK', '') AS '4_Contas a Pagar',
IF( modulosg.modulo = '5' AND modulosg.produto = '1', 'OK', '') AS '5_Contas a Receber',
IF( modulosg.modulo = '20' AND modulosg.produto = '1', 'OK', '') AS '20_Contas Bancarias',
IF( modulosg.modulo = '9' AND modulosg.produto = '1', 'OK', '') AS '9_Contra Vales para Clientes',
IF( modulosg.modulo = '107' AND modulosg.produto = '1', 'OK', '') AS '107_Contribuicao Solidaria',
IF( modulosg.modulo = '22' AND modulosg.produto = '1', 'OK', '') AS '22_Controle de Convenios/Ticket/Cartao',
IF( modulosg.modulo = '21' AND modulosg.produto = '1', 'OK', '') AS '21_Controle de Despesas',
IF( modulosg.modulo = '178' AND modulosg.produto = '1', 'OK', '') AS '178_Controle de licitacoes',
IF( modulosg.modulo = '7' AND modulosg.produto = '1', 'OK', '') AS '7_Controle de Loja',
IF( modulosg.modulo = '36' AND modulosg.produto = '1', 'OK', '') AS '36_Controle de Promocoes',
IF( modulosg.modulo = '28' AND modulosg.produto = '1', 'OK', '') AS '28_Controle de Trocas',
IF( modulosg.modulo = '39' AND modulosg.produto = '1', 'OK', '') AS '39_Controle de Veiculos',
IF( modulosg.modulo = '32' AND modulosg.produto = '1', 'OK', '') AS '32_Controle de Verbas',
IF( modulosg.modulo = '71' AND modulosg.produto = '1', 'OK', '') AS '71_Controle Financeiro',
IF( modulosg.modulo = '148' AND modulosg.produto = '1', 'OK', '') AS '148_Controle Flex',
IF( modulosg.modulo = '37' AND modulosg.produto = '1', 'OK', '') AS '37_Controle Patrimonial',
IF( modulosg.modulo = '17' AND modulosg.produto = '1', 'OK', '') AS '17_Cotacao de Atacado',
IF( modulosg.modulo = '122' AND modulosg.produto = '1', 'OK', '') AS '122_DMCard - Integracao Soumais',
IF( modulosg.modulo = '139' AND modulosg.produto = '1', 'OK', '') AS '139_Emissao de Boletos',
IF( modulosg.modulo = '140' AND modulosg.produto = '1', 'OK', '') AS '140_Emissao NFCe Retaguarda',
IF( modulosg.modulo = '15' AND modulosg.produto = '1', 'OK', '') AS '15_Entrada de Notas/Calculo de Precos',
IF( modulosg.modulo = '40' AND modulosg.produto = '1', 'OK', '') AS '40_Escrita Fiscal',
IF( modulosg.modulo = '11' AND modulosg.produto = '1', 'OK', '') AS '11_Faturamento de Vendas',
IF( modulosg.modulo = '43' AND modulosg.produto = '1', 'OK', '') AS '43_Fechamento de Caixa de Lojas',
IF( modulosg.modulo = '41' AND modulosg.produto = '1', 'OK', '') AS '41_Fidelizacao',
IF( modulosg.modulo = '42' AND modulosg.produto = '1', 'OK', '') AS '42_Fluxo de Caixa',
IF( modulosg.modulo = '2' AND modulosg.produto = '1', 'OK', '') AS '2_Fornecedores',
IF( modulosg.modulo = '44' AND modulosg.produto = '1', 'OK', '') AS '44_Gerenciamento de Gondolas',
IF( modulosg.modulo = '136' AND modulosg.produto = '1', 'OK', '') AS '136_Grava Logs Externamente',
IF( modulosg.modulo = '301' AND modulosg.produto = '1', 'OK', '') AS '301_Homologacao Integradores',
IF( modulosg.modulo = '355' AND modulosg.produto = '1', 'OK', '') AS '355_ICMS Centralizado',
IF( modulosg.modulo = '27' AND modulosg.produto = '1', 'OK', '') AS '27_Importacao/Exportacao',
IF( modulosg.modulo = '25' AND modulosg.produto = '1', 'OK', '') AS '25_Indices Financeiros',
IF( modulosg.modulo = '313' AND modulosg.produto = '1', 'OK', '') AS '313_Integracao Ad Rocket',
IF( modulosg.modulo = '150' AND modulosg.produto = '1', 'OK', '') AS '150_Integracao Alfred',
IF( modulosg.modulo = '170' AND modulosg.produto = '1', 'OK', '') AS '170_Integracao Amo Delivery',
IF( modulosg.modulo = '356' AND modulosg.produto = '1', 'OK', '') AS '356_Integracao Apice',
IF( modulosg.modulo = '159' AND modulosg.produto = '1', 'OK', '') AS '159_Integracao APPMercados',
IF( modulosg.modulo = '320' AND modulosg.produto = '1', 'OK', '') AS '320_Integracao Area Central - API',
IF( modulosg.modulo = '147' AND modulosg.produto = '1', 'OK', '') AS '147_Integracao Area Central - ASSOCIADO',
IF( modulosg.modulo = '146' AND modulosg.produto = '1', 'OK', '') AS '146_Integracao Area Central - REDE',
IF( modulosg.modulo = '160' AND modulosg.produto = '1', 'OK', '') AS '160_Integracao arMHAzena',
IF( modulosg.modulo = '157' AND modulosg.produto = '1', 'OK', '') AS '157_Integracao Askyn',
IF( modulosg.modulo = '172' AND modulosg.produto = '1', 'OK', '') AS '172_Integracao Auditto',
IF( modulosg.modulo = '158' AND modulosg.produto = '1', 'OK', '') AS '158_Integracao Beblue',
IF( modulosg.modulo = '343' AND modulosg.produto = '1', 'OK', '') AS '343_Integracao Cartaz Facil',
IF( modulosg.modulo = '124' AND modulosg.produto = '1', 'OK', '') AS '124_Integracao cartoes Cocalcard',
IF( modulosg.modulo = '115' AND modulosg.produto = '1', 'OK', '') AS '115_Integracao Cerprosoft Sav',
IF( modulosg.modulo = '345' AND modulosg.produto = '1', 'OK', '') AS '345_Integracao Codevops',
IF( modulosg.modulo = '180' AND modulosg.produto = '1', 'OK', '') AS '180_Integracao Compre Facil',
IF( modulosg.modulo = '119' AND modulosg.produto = '1', 'OK', '') AS '119_Integracao Consignet',
IF( modulosg.modulo = '143' AND modulosg.produto = '1', 'OK', '') AS '143_Integracao controle de catraca CloudPark',
IF( modulosg.modulo = '174' AND modulosg.produto = '1', 'OK', '') AS '174_Integracao Cresce Vendas',
IF( modulosg.modulo = '211' AND modulosg.produto = '1', 'OK', '') AS '211_Integracao Cupom Verde',
IF( modulosg.modulo = '155' AND modulosg.produto = '1', 'OK', '') AS '155_Integracao Cyberlog - WMS',
IF( modulosg.modulo = '344' AND modulosg.produto = '1', 'OK', '') AS '344_Integracao Dattion',
IF( modulosg.modulo = '177' AND modulosg.produto = '1', 'OK', '') AS '177_Integracao de Associacao (Menu)',
IF( modulosg.modulo = '182' AND modulosg.produto = '1', 'OK', '') AS '182_Integracao Deju',
IF( modulosg.modulo = '346' AND modulosg.produto = '1', 'OK', '') AS '346_Integracao Docerrano',
IF( modulosg.modulo = '294' AND modulosg.produto = '1', 'OK', '') AS '294_Integracao Dominio XML',
IF( modulosg.modulo = '134' AND modulosg.produto = '1', 'OK', '') AS '134_Integracao Fiscal FGF',
IF( modulosg.modulo = '291' AND modulosg.produto = '1', 'OK', '') AS '291_Integracao Go Find',
IF( modulosg.modulo = '168' AND modulosg.produto = '1', 'OK', '') AS '168_Integracao IANDEV',
IF( modulosg.modulo = '302' AND modulosg.produto = '1', 'OK', '') AS '302_Integracao Ideris',
IF( modulosg.modulo = '315' AND modulosg.produto = '1', 'OK', '') AS '315_Integracao IMENDES',
IF( modulosg.modulo = '309' AND modulosg.produto = '1', 'OK', '') AS '309_Integracao InfoPrice',
IF( modulosg.modulo = '181' AND modulosg.produto = '1', 'OK', '') AS '181_Integracao Insta Buy',
IF( modulosg.modulo = '333' AND modulosg.produto = '1', 'OK', '') AS '333_Integracao Izi App',
IF( modulosg.modulo = '169' AND modulosg.produto = '1', 'OK', '') AS '169_Integracao KIKKER',
IF( modulosg.modulo = '323' AND modulosg.produto = '1', 'OK', '') AS '323_Integracao Loja Integrada',
IF( modulosg.modulo = '163' AND modulosg.produto = '1', 'OK', '') AS '163_Integracao LOJAQUI',
IF( modulosg.modulo = '295' AND modulosg.produto = '1', 'OK', '') AS '295_Integracao Matera',
IF( modulosg.modulo = '129' AND modulosg.produto = '1', 'OK', '') AS '129_Integracao Mercadex',
IF( modulosg.modulo = '334' AND modulosg.produto = '1', 'OK', '') AS '334_Integracao Mercafacil',
IF( modulosg.modulo = '308' AND modulosg.produto = '1', 'OK', '') AS '308_Integracao Minus',
IF( modulosg.modulo = '347' AND modulosg.produto = '1', 'OK', '') AS '347_Integracao Moria Consultoria',
IF( modulosg.modulo = '175' AND modulosg.produto = '1', 'OK', '') AS '175_Integracao NappSync',
IF( modulosg.modulo = '360' AND modulosg.produto = '1', 'OK', '') AS '360_Integracao Nexello',
IF( modulosg.modulo = '167' AND modulosg.produto = '1', 'OK', '') AS '167_Integracao Nexfood',
IF( modulosg.modulo = '118' AND modulosg.produto = '1', 'OK', '') AS '118_Integracao NovAmerica',
IF( modulosg.modulo = '353' AND modulosg.produto = '1', 'OK', '') AS '353_Integracao One BI',
IF( modulosg.modulo = '312' AND modulosg.produto = '1', 'OK', '') AS '312_Integracao PagPix',
IF( modulosg.modulo = '359' AND modulosg.produto = '1', 'OK', '') AS '359_Integracao Proffer',
IF( modulosg.modulo = '176' AND modulosg.produto = '1', 'OK', '') AS '176_Integracao SG SISTEMAS',
IF( modulosg.modulo = '253' AND modulosg.produto = '1', 'OK', '') AS '253_Integracao Shipay',
IF( modulosg.modulo = '348' AND modulosg.produto = '1', 'OK', '') AS '348_Integracao Simpletask',
IF( modulosg.modulo = '141' AND modulosg.produto = '1', 'OK', '') AS '141_Integracao SIMPLUS',
IF( modulosg.modulo = '130' AND modulosg.produto = '1', 'OK', '') AS '130_Integracao Site Mercado',
IF( modulosg.modulo = '179' AND modulosg.produto = '1', 'OK', '') AS '179_Integracao Site Mercado API',
IF( modulosg.modulo = '254' AND modulosg.produto = '1', 'OK', '') AS '254_Integracao Smart',
IF( modulosg.modulo = '311' AND modulosg.produto = '1', 'OK', '') AS '311_Integracao Supermercado Esperanca',
IF( modulosg.modulo = '322' AND modulosg.produto = '1', 'OK', '') AS '322_Integracao TI Soluti',
IF( modulosg.modulo = '171' AND modulosg.produto = '1', 'OK', '') AS '171_Integracao Tray',
IF( modulosg.modulo = '256' AND modulosg.produto = '1', 'OK', '') AS '256_Integracao Web Jasper',
IF( modulosg.modulo = '152' AND modulosg.produto = '1', 'OK', '') AS '152_Integracao WL Assessoria e Contabilidade',
IF( modulosg.modulo = '132' AND modulosg.produto = '1', 'OK', '') AS '132_Integracao XML SetUP - SGDFE GETCARD',
IF( modulosg.modulo = '131' AND modulosg.produto = '1', 'OK', '') AS '131_Integracao XML SetUP - SGDFE LOCAL',
IF( modulosg.modulo = '26' AND modulosg.produto = '1', 'OK', '') AS '26_Inventario Fiscal',
IF( modulosg.modulo = '13' AND modulosg.produto = '1', 'OK', '') AS '13_Inventario Fisico ( Balanco)',
IF( modulosg.modulo = '29' AND modulosg.produto = '1', 'OK', '') AS '29_Levantamento Parcial de Estoque',
IF( modulosg.modulo = '58' AND modulosg.produto = '1', 'OK', '') AS '58_Mapa Fiscal',
IF( modulosg.modulo = '117' AND modulosg.produto = '1', 'OK', '') AS '117_Mix Fiscal',
IF( modulosg.modulo = '72' AND modulosg.produto = '1', 'OK', '') AS '72_Modulo Gestao',
IF( modulosg.modulo = '14' AND modulosg.produto = '1', 'OK', '') AS '14_Movimentacao de Produtos',
IF( modulosg.modulo = '30' AND modulosg.produto = '1', 'OK', '') AS '30_Movimento de Caixa',
IF( modulosg.modulo = '10' AND modulosg.produto = '1', 'OK', '') AS '10_M¢dulos de Consulta de Loja',
IF( modulosg.modulo = '73' AND modulosg.produto = '1', 'OK', '') AS '73_PAF ECF',
IF( modulosg.modulo = '31' AND modulosg.produto = '1', 'OK', '') AS '31_Pesquisa de Precos',
IF( modulosg.modulo = '120' AND modulosg.produto = '1', 'OK', '') AS '120_PLAY VIEW',
IF( modulosg.modulo = '19' AND modulosg.produto = '1', 'OK', '') AS '19_Producao ( Padaria , Acougue)',
IF( modulosg.modulo = '1' AND modulosg.produto = '1', 'OK', '') AS '1_Produtos e Precos',
IF( modulosg.modulo = '75' AND modulosg.produto = '1', 'OK', '') AS '75_Proposta',
IF( modulosg.modulo = '6' AND modulosg.produto = '1', 'OK', '') AS '6_Resumo de Caixa',
IF( modulosg.modulo = '74' AND modulosg.produto = '1', 'OK', '') AS '74_SAT',
IF( modulosg.modulo = '104' AND modulosg.produto = '1', 'OK', '') AS '104_Scanntech',
IF( modulosg.modulo = '173' AND modulosg.produto = '1', 'OK', '') AS '173_Senha PDV por PINPAD - SITEF TUICCS',
IF( modulosg.modulo = '121' AND modulosg.produto = '1', 'OK', '') AS '121_Senha venda prazo - Software Express',
IF( modulosg.modulo = '46' AND modulosg.produto = '1', 'OK', '') AS '46_Servico de Atendimento ao Cliente',
IF( modulosg.modulo = '59' AND modulosg.produto = '1', 'OK', '') AS '59_SGCotacao On-line',
IF( modulosg.modulo = '60' AND modulosg.produto = '1', 'OK', '') AS '60_SGPESQ',
IF( modulosg.modulo = '153' AND modulosg.produto = '1', 'OK', '') AS '153_Solucoes Fiscais',
IF( modulosg.modulo = '33' AND modulosg.produto = '1', 'OK', '') AS '33_Transferencia',
IF( modulosg.modulo = '137' AND modulosg.produto = '1', 'OK', '') AS '137_Troco Simples',
IF( modulosg.modulo = '48' AND modulosg.produto = '1', 'OK', '') AS '48_Vendas Cooperados/Associados',
IF( modulosg.modulo = '16' AND modulosg.produto = '1', 'OK', '') AS '16_Vendas de PDVs/Rentabilidade',
IF( modulosg.modulo = '34' AND modulosg.produto = '2', 'OK', '') AS '34_Apoio Contabil',
IF( modulosg.modulo = '3' AND modulosg.produto = '2', 'OK', '') AS '3_Clientes',
IF( modulosg.modulo = '23' AND modulosg.produto = '2', 'OK', '') AS '23_Comissoes',
IF( modulosg.modulo = '24' AND modulosg.produto = '2', 'OK', '') AS '24_Compras de Ind£strias/Distribuidoras',
IF( modulosg.modulo = '108' AND modulosg.produto = '2', 'OK', '') AS '108_Conciliacao de cartoes - Conciflex',
IF( modulosg.modulo = '165' AND modulosg.produto = '2', 'OK', '') AS '165_Conciliacao de cartoes - VIZZO',
IF( modulosg.modulo = '4' AND modulosg.produto = '2', 'OK', '') AS '4_Contas a Pagar',
IF( modulosg.modulo = '5' AND modulosg.produto = '2', 'OK', '') AS '5_Contas a Receber',
IF( modulosg.modulo = '20' AND modulosg.produto = '2', 'OK', '') AS '20_Contas Bancarias',
IF( modulosg.modulo = '9' AND modulosg.produto = '2', 'OK', '') AS '9_Contra Vales',
IF( modulosg.modulo = '107' AND modulosg.produto = '2', 'OK', '') AS '107_Contribuicao Solidaria',
IF( modulosg.modulo = '12' AND modulosg.produto = '2', 'OK', '') AS '12_Controle de Cheques',
IF( modulosg.modulo = '21' AND modulosg.produto = '2', 'OK', '') AS '21_Controle de Despesas',
IF( modulosg.modulo = '7' AND modulosg.produto = '2', 'OK', '') AS '7_Controle de Loja',
IF( modulosg.modulo = '19' AND modulosg.produto = '2', 'OK', '') AS '19_Controle de Producao',
IF( modulosg.modulo = '22' AND modulosg.produto = '2', 'OK', '') AS '22_Controle de Ticket/Cartao',
IF( modulosg.modulo = '28' AND modulosg.produto = '2', 'OK', '') AS '28_Controle de Trocas',
IF( modulosg.modulo = '11' AND modulosg.produto = '2', 'OK', '') AS '11_Controle de Vendas',
IF( modulosg.modulo = '148' AND modulosg.produto = '2', 'OK', '') AS '148_Controle Flex',
IF( modulosg.modulo = '56' AND modulosg.produto = '2', 'OK', '') AS '56_Controle Gerencial',
IF( modulosg.modulo = '17' AND modulosg.produto = '2', 'OK', '') AS '17_Cotacao de Atacado',
IF( modulosg.modulo = '135' AND modulosg.produto = '2', 'OK', '') AS '135_Donuz',
IF( modulosg.modulo = '139' AND modulosg.produto = '2', 'OK', '') AS '139_Emissao de Boletos',
IF( modulosg.modulo = '15' AND modulosg.produto = '2', 'OK', '') AS '15_Entrada de Notas',
IF( modulosg.modulo = '40' AND modulosg.produto = '2', 'OK', '') AS '40_Escrita Fiscal',
IF( modulosg.modulo = '41' AND modulosg.produto = '2', 'OK', '') AS '41_Fidelizacao',
IF( modulosg.modulo = '42' AND modulosg.produto = '2', 'OK', '') AS '42_Fluxo de Caixa',
IF( modulosg.modulo = '2' AND modulosg.produto = '2', 'OK', '') AS '2_Fornecedores',
IF( modulosg.modulo = '301' AND modulosg.produto = '2', 'OK', '') AS '301_Homologacao Integradores',
IF( modulosg.modulo = '313' AND modulosg.produto = '2', 'OK', '') AS '313_Integracao Ad Rocket',
IF( modulosg.modulo = '326' AND modulosg.produto = '2', 'OK', '') AS '326_Integracao Anota Ai',
IF( modulosg.modulo = '356' AND modulosg.produto = '2', 'OK', '') AS '356_Integracao Apice',
IF( modulosg.modulo = '159' AND modulosg.produto = '2', 'OK', '') AS '159_Integracao APPMercados',
IF( modulosg.modulo = '320' AND modulosg.produto = '2', 'OK', '') AS '320_Integracao Area Central - API',
IF( modulosg.modulo = '147' AND modulosg.produto = '2', 'OK', '') AS '147_Integracao Area Central - ASSOCIADO',
IF( modulosg.modulo = '146' AND modulosg.produto = '2', 'OK', '') AS '146_Integracao Area Central - REDE',
IF( modulosg.modulo = '157' AND modulosg.produto = '2', 'OK', '') AS '157_Integracao Askyn',
IF( modulosg.modulo = '172' AND modulosg.produto = '2', 'OK', '') AS '172_Integracao Auditto',
IF( modulosg.modulo = '343' AND modulosg.produto = '2', 'OK', '') AS '343_Integracao Cartaz Facil',
IF( modulosg.modulo = '345' AND modulosg.produto = '2', 'OK', '') AS '345_Integracao Codevops',
IF( modulosg.modulo = '180' AND modulosg.produto = '2', 'OK', '') AS '180_Integracao Compre Facil',
IF( modulosg.modulo = '119' AND modulosg.produto = '2', 'OK', '') AS '119_Integracao Consignet',
IF( modulosg.modulo = '174' AND modulosg.produto = '2', 'OK', '') AS '174_Integracao Cresce Vendas',
IF( modulosg.modulo = '211' AND modulosg.produto = '2', 'OK', '') AS '211_Integracao Cupom Verde',
IF( modulosg.modulo = '344' AND modulosg.produto = '2', 'OK', '') AS '344_Integracao Dattion',
IF( modulosg.modulo = '182' AND modulosg.produto = '2', 'OK', '') AS '182_Integracao Deju',
IF( modulosg.modulo = '346' AND modulosg.produto = '2', 'OK', '') AS '346_Integracao Docerrano',
IF( modulosg.modulo = '294' AND modulosg.produto = '2', 'OK', '') AS '294_Integracao Dominio XML',
IF( modulosg.modulo = '291' AND modulosg.produto = '2', 'OK', '') AS '291_Integracao Go Find',
IF( modulosg.modulo = '315' AND modulosg.produto = '2', 'OK', '') AS '315_Integracao IMENDES',
IF( modulosg.modulo = '181' AND modulosg.produto = '2', 'OK', '') AS '181_Integracao Insta Buy',
IF( modulosg.modulo = '333' AND modulosg.produto = '2', 'OK', '') AS '333_Integracao Izi App',
IF( modulosg.modulo = '163' AND modulosg.produto = '2', 'OK', '') AS '163_Integracao LOJAQUI',
IF( modulosg.modulo = '334' AND modulosg.produto = '2', 'OK', '') AS '334_Integracao Mercafacil',
IF( modulosg.modulo = '308' AND modulosg.produto = '2', 'OK', '') AS '308_Integracao Minus',
IF( modulosg.modulo = '347' AND modulosg.produto = '2', 'OK', '') AS '347_Integracao Moria Consultoria',
IF( modulosg.modulo = '167' AND modulosg.produto = '2', 'OK', '') AS '167_Integracao Nexfood',
IF( modulosg.modulo = '118' AND modulosg.produto = '2', 'OK', '') AS '118_Integracao NovAmerica',
IF( modulosg.modulo = '312' AND modulosg.produto = '2', 'OK', '') AS '312_Integracao PagPix',
IF( modulosg.modulo = '359' AND modulosg.produto = '2', 'OK', '') AS '359_Integracao Proffer',
IF( modulosg.modulo = '166' AND modulosg.produto = '2', 'OK', '') AS '166_Integracao RAPPI',
IF( modulosg.modulo = '176' AND modulosg.produto = '2', 'OK', '') AS '176_Integracao SG SISTEMAS',
IF( modulosg.modulo = '253' AND modulosg.produto = '2', 'OK', '') AS '253_Integracao Shipay',
IF( modulosg.modulo = '348' AND modulosg.produto = '2', 'OK', '') AS '348_Integracao Simpletask',
IF( modulosg.modulo = '141' AND modulosg.produto = '2', 'OK', '') AS '141_Integracao SIMPLUS',
IF( modulosg.modulo = '130' AND modulosg.produto = '2', 'OK', '') AS '130_Integracao Site Mercado',
IF( modulosg.modulo = '254' AND modulosg.produto = '2', 'OK', '') AS '254_Integracao Smart',
IF( modulosg.modulo = '311' AND modulosg.produto = '2', 'OK', '') AS '311_Integracao Supermercado Esperanca',
IF( modulosg.modulo = '322' AND modulosg.produto = '2', 'OK', '') AS '322_Integracao TI Soluti',
IF( modulosg.modulo = '171' AND modulosg.produto = '2', 'OK', '') AS '171_Integracao Tray',
IF( modulosg.modulo = '256' AND modulosg.produto = '2', 'OK', '') AS '256_Integracao Web Jasper',
IF( modulosg.modulo = '310' AND modulosg.produto = '2', 'OK', '') AS '310_Integracao Web Jasper API',
IF( modulosg.modulo = '152' AND modulosg.produto = '2', 'OK', '') AS '152_Integracao WL Assessoria e Contabilidade',
IF( modulosg.modulo = '132' AND modulosg.produto = '2', 'OK', '') AS '132_Integracao XML SetUP - SGDFE GETCARD',
IF( modulosg.modulo = '26' AND modulosg.produto = '2', 'OK', '') AS '26_Inventario Fiscal',
IF( modulosg.modulo = '13' AND modulosg.produto = '2', 'OK', '') AS '13_Inventario Fisico ( Balanco)',
IF( modulosg.modulo = '29' AND modulosg.produto = '2', 'OK', '') AS '29_Levantamento Parcial de Estoque',
IF( modulosg.modulo = '111' AND modulosg.produto = '2', 'OK', '') AS '111_Mercafacil',
IF( modulosg.modulo = '117' AND modulosg.produto = '2', 'OK', '') AS '117_Mix Fiscal',
IF( modulosg.modulo = '14' AND modulosg.produto = '2', 'OK', '') AS '14_Movimentacao de Produtos',
IF( modulosg.modulo = '30' AND modulosg.produto = '2', 'OK', '') AS '30_Movimento de Caixa',
IF( modulosg.modulo = '120' AND modulosg.produto = '2', 'OK', '') AS '120_PLAY VIEW',
IF( modulosg.modulo = '55' AND modulosg.produto = '2', 'OK', '') AS '55_Prestacao de Servico',
IF( modulosg.modulo = '1' AND modulosg.produto = '2', 'OK', '') AS '1_Produtos e Precos',
IF( modulosg.modulo = '6' AND modulosg.produto = '2', 'OK', '') AS '6_Resumo de Caixa',
IF( modulosg.modulo = '74' AND modulosg.produto = '2', 'OK', '') AS '74_SAT',
IF( modulosg.modulo = '104' AND modulosg.produto = '2', 'OK', '') AS '104_Scanntech',
IF( modulosg.modulo = '173' AND modulosg.produto = '2', 'OK', '') AS '173_Senha PDV por PINPAD - SITEF TUICCS',
IF( modulosg.modulo = '121' AND modulosg.produto = '2', 'OK', '') AS '121_Senha venda prazo - Software Express',
IF( modulosg.modulo = '59' AND modulosg.produto = '2', 'OK', '') AS '59_SGCotacao On-line',
IF( modulosg.modulo = '33' AND modulosg.produto = '2', 'OK', '') AS '33_Transferencia',
IF( modulosg.modulo = '137' AND modulosg.produto = '2', 'OK', '') AS '137_Troco Simples',
IF( modulosg.modulo = '34' AND modulosg.produto = '3', 'OK', '') AS '34_Apoio Contabil',
IF( modulosg.modulo = '103' AND modulosg.produto = '3', 'OK', '') AS '103_Autopagamento',
IF( modulosg.modulo = '106' AND modulosg.produto = '3', 'OK', '') AS '106_Autopagamento - Demo',
IF( modulosg.modulo = '49' AND modulosg.produto = '3', 'OK', '') AS '49_Balcao',
IF( modulosg.modulo = '53' AND modulosg.produto = '3', 'OK', '') AS '53_Cartao',
IF( modulosg.modulo = '3' AND modulosg.produto = '3', 'OK', '') AS '3_Clientes',
IF( modulosg.modulo = '24' AND modulosg.produto = '3', 'OK', '') AS '24_Compras de Ind£strias/Distribuidoras',
IF( modulosg.modulo = '108' AND modulosg.produto = '3', 'OK', '') AS '108_Conciliacao de cartoes - Conciflex',
IF( modulosg.modulo = '165' AND modulosg.produto = '3', 'OK', '') AS '165_Conciliacao de cartoes - VIZZO',
IF( modulosg.modulo = '4' AND modulosg.produto = '3', 'OK', '') AS '4_Contas a Pagar',
IF( modulosg.modulo = '5' AND modulosg.produto = '3', 'OK', '') AS '5_Contas a Receber',
IF( modulosg.modulo = '20' AND modulosg.produto = '3', 'OK', '') AS '20_Contas Bancarias',
IF( modulosg.modulo = '107' AND modulosg.produto = '3', 'OK', '') AS '107_Contribuicao Solidaria',
IF( modulosg.modulo = '12' AND modulosg.produto = '3', 'OK', '') AS '12_Controle de Cheques',
IF( modulosg.modulo = '23' AND modulosg.produto = '3', 'OK', '') AS '23_Controle de Comissao',
IF( modulosg.modulo = '21' AND modulosg.produto = '3', 'OK', '') AS '21_Controle de Despesas',
IF( modulosg.modulo = '7' AND modulosg.produto = '3', 'OK', '') AS '7_Controle de Loja',
IF( modulosg.modulo = '19' AND modulosg.produto = '3', 'OK', '') AS '19_Controle de Producao',
IF( modulosg.modulo = '22' AND modulosg.produto = '3', 'OK', '') AS '22_Controle de Ticket/Cartao',
IF( modulosg.modulo = '56' AND modulosg.produto = '3', 'OK', '') AS '56_Controle Gerencial',
IF( modulosg.modulo = '135' AND modulosg.produto = '3', 'OK', '') AS '135_Donuz',
IF( modulosg.modulo = '139' AND modulosg.produto = '3', 'OK', '') AS '139_Emissao de Boletos',
IF( modulosg.modulo = '15' AND modulosg.produto = '3', 'OK', '') AS '15_Entrada de Notas',
IF( modulosg.modulo = '40' AND modulosg.produto = '3', 'OK', '') AS '40_Escrita Fiscal',
IF( modulosg.modulo = '41' AND modulosg.produto = '3', 'OK', '') AS '41_Fidelizacao',
IF( modulosg.modulo = '125' AND modulosg.produto = '3', 'OK', '') AS '125_Fidelizi',
IF( modulosg.modulo = '42' AND modulosg.produto = '3', 'OK', '') AS '42_Fluxo de Caixa',
IF( modulosg.modulo = '2' AND modulosg.produto = '3', 'OK', '') AS '2_Fornecedores',
IF( modulosg.modulo = '133' AND modulosg.produto = '3', 'OK', '') AS '133_Google Maps',
IF( modulosg.modulo = '301' AND modulosg.produto = '3', 'OK', '') AS '301_Homologacao Integradores',
IF( modulosg.modulo = '313' AND modulosg.produto = '3', 'OK', '') AS '313_Integracao Ad Rocket',
IF( modulosg.modulo = '326' AND modulosg.produto = '3', 'OK', '') AS '326_Integracao Anota Ai',
IF( modulosg.modulo = '159' AND modulosg.produto = '3', 'OK', '') AS '159_Integracao APPMercados',
IF( modulosg.modulo = '320' AND modulosg.produto = '3', 'OK', '') AS '320_Integracao Area Central - API',
IF( modulosg.modulo = '147' AND modulosg.produto = '3', 'OK', '') AS '147_Integracao Area Central - ASSOCIADO',
IF( modulosg.modulo = '146' AND modulosg.produto = '3', 'OK', '') AS '146_Integracao Area Central - REDE',
IF( modulosg.modulo = '172' AND modulosg.produto = '3', 'OK', '') AS '172_Integracao Auditto',
IF( modulosg.modulo = '343' AND modulosg.produto = '3', 'OK', '') AS '343_Integracao Cartaz Facil',
IF( modulosg.modulo = '345' AND modulosg.produto = '3', 'OK', '') AS '345_Integracao Codevops',
IF( modulosg.modulo = '180' AND modulosg.produto = '3', 'OK', '') AS '180_Integracao Compre Facil',
IF( modulosg.modulo = '174' AND modulosg.produto = '3', 'OK', '') AS '174_Integracao Cresce Vendas',
IF( modulosg.modulo = '344' AND modulosg.produto = '3', 'OK', '') AS '344_Integracao Dattion',
IF( modulosg.modulo = '182' AND modulosg.produto = '3', 'OK', '') AS '182_Integracao Deju',
IF( modulosg.modulo = '346' AND modulosg.produto = '3', 'OK', '') AS '346_Integracao Docerrano',
IF( modulosg.modulo = '294' AND modulosg.produto = '3', 'OK', '') AS '294_Integracao Dominio XML',
IF( modulosg.modulo = '291' AND modulosg.produto = '3', 'OK', '') AS '291_Integracao Go Find',
IF( modulosg.modulo = '164' AND modulosg.produto = '3', 'OK', '') AS '164_Integracao IFOOD',
IF( modulosg.modulo = '181' AND modulosg.produto = '3', 'OK', '') AS '181_Integracao Insta Buy',
IF( modulosg.modulo = '333' AND modulosg.produto = '3', 'OK', '') AS '333_Integracao Izi App',
IF( modulosg.modulo = '163' AND modulosg.produto = '3', 'OK', '') AS '163_Integracao LOJAQUI',
IF( modulosg.modulo = '308' AND modulosg.produto = '3', 'OK', '') AS '308_Integracao Minus',
IF( modulosg.modulo = '347' AND modulosg.produto = '3', 'OK', '') AS '347_Integracao Moria Consultoria',
IF( modulosg.modulo = '162' AND modulosg.produto = '3', 'OK', '') AS '162_Integracao Neemo',
IF( modulosg.modulo = '167' AND modulosg.produto = '3', 'OK', '') AS '167_Integracao Nexfood',
IF( modulosg.modulo = '312' AND modulosg.produto = '3', 'OK', '') AS '312_Integracao PagPix',
IF( modulosg.modulo = '166' AND modulosg.produto = '3', 'OK', '') AS '166_Integracao RAPPI',
IF( modulosg.modulo = '176' AND modulosg.produto = '3', 'OK', '') AS '176_Integracao SG SISTEMAS',
IF( modulosg.modulo = '253' AND modulosg.produto = '3', 'OK', '') AS '253_Integracao Shipay',
IF( modulosg.modulo = '348' AND modulosg.produto = '3', 'OK', '') AS '348_Integracao Simpletask',
IF( modulosg.modulo = '141' AND modulosg.produto = '3', 'OK', '') AS '141_Integracao SIMPLUS',
IF( modulosg.modulo = '130' AND modulosg.produto = '3', 'OK', '') AS '130_Integracao Site Mercado',
IF( modulosg.modulo = '254' AND modulosg.produto = '3', 'OK', '') AS '254_Integracao Smart',
IF( modulosg.modulo = '311' AND modulosg.produto = '3', 'OK', '') AS '311_Integracao Supermercado Esperanca',
IF( modulosg.modulo = '322' AND modulosg.produto = '3', 'OK', '') AS '322_Integracao TI Soluti',
IF( modulosg.modulo = '171' AND modulosg.produto = '3', 'OK', '') AS '171_Integracao Tray',
IF( modulosg.modulo = '256' AND modulosg.produto = '3', 'OK', '') AS '256_Integracao Web Jasper',
IF( modulosg.modulo = '132' AND modulosg.produto = '3', 'OK', '') AS '132_Integracao XML SetUP - SGDFE GETCARD',
IF( modulosg.modulo = '26' AND modulosg.produto = '3', 'OK', '') AS '26_Inventario Fiscal',
IF( modulosg.modulo = '13' AND modulosg.produto = '3', 'OK', '') AS '13_Inventario Fisico ( Balanco)',
IF( modulosg.modulo = '29' AND modulosg.produto = '3', 'OK', '') AS '29_Levantamento Parcial de Estoque',
IF( modulosg.modulo = '51' AND modulosg.produto = '3', 'OK', '') AS '51_Mesa',
IF( modulosg.modulo = '117' AND modulosg.produto = '3', 'OK', '') AS '117_Mix Fiscal',
IF( modulosg.modulo = '14' AND modulosg.produto = '3', 'OK', '') AS '14_Movimentacao de Produtos',
IF( modulosg.modulo = '30' AND modulosg.produto = '3', 'OK', '') AS '30_Movimento de Caixa',
IF( modulosg.modulo = '50' AND modulosg.produto = '3', 'OK', '') AS '50_Pedidos',
IF( modulosg.modulo = '120' AND modulosg.produto = '3', 'OK', '') AS '120_PLAY VIEW',
IF( modulosg.modulo = '54' AND modulosg.produto = '3', 'OK', '') AS '54_Pre-Pedido',
IF( modulosg.modulo = '52' AND modulosg.produto = '3', 'OK', '') AS '52_Producao para entrega',
IF( modulosg.modulo = '1' AND modulosg.produto = '3', 'OK', '') AS '1_Produtos e Precos',
IF( modulosg.modulo = '6' AND modulosg.produto = '3', 'OK', '') AS '6_Resumo de Caixa',
IF( modulosg.modulo = '74' AND modulosg.produto = '3', 'OK', '') AS '74_SAT',
IF( modulosg.modulo = '104' AND modulosg.produto = '3', 'OK', '') AS '104_Scanntech',
IF( modulosg.modulo = '173' AND modulosg.produto = '3', 'OK', '') AS '173_Senha PDV por PINPAD - SITEF TUICCS',
IF( modulosg.modulo = '33' AND modulosg.produto = '3', 'OK', '') AS '33_Transferencia',
IF( modulosg.modulo = '137' AND modulosg.produto = '3', 'OK', '') AS '137_Troco Simples',
IF( modulosg.modulo = '34' AND modulosg.produto = '4', 'OK', '') AS '34_Apoio Contabil',
IF( modulosg.modulo = '49' AND modulosg.produto = '4', 'OK', '') AS '49_Balcao',
IF( modulosg.modulo = '53' AND modulosg.produto = '4', 'OK', '') AS '53_Cartao',
IF( modulosg.modulo = '3' AND modulosg.produto = '4', 'OK', '') AS '3_Clientes',
IF( modulosg.modulo = '24' AND modulosg.produto = '4', 'OK', '') AS '24_Compras de Ind£strias/Distribuidoras',
IF( modulosg.modulo = '4' AND modulosg.produto = '4', 'OK', '') AS '4_Contas a Pagar',
IF( modulosg.modulo = '5' AND modulosg.produto = '4', 'OK', '') AS '5_Contas a Receber',
IF( modulosg.modulo = '20' AND modulosg.produto = '4', 'OK', '') AS '20_Contas Bancarias',
IF( modulosg.modulo = '12' AND modulosg.produto = '4', 'OK', '') AS '12_Controle de Cheques',
IF( modulosg.modulo = '23' AND modulosg.produto = '4', 'OK', '') AS '23_Controle de Comissao',
IF( modulosg.modulo = '19' AND modulosg.produto = '4', 'OK', '') AS '19_Controle de Producao',
IF( modulosg.modulo = '56' AND modulosg.produto = '4', 'OK', '') AS '56_Controle Gerencial',
IF( modulosg.modulo = '15' AND modulosg.produto = '4', 'OK', '') AS '15_Entrada de Notas',
IF( modulosg.modulo = '40' AND modulosg.produto = '4', 'OK', '') AS '40_Escrita Fiscal',
IF( modulosg.modulo = '42' AND modulosg.produto = '4', 'OK', '') AS '42_Fluxo de Caixa',
IF( modulosg.modulo = '2' AND modulosg.produto = '4', 'OK', '') AS '2_Fornecedores',
IF( modulosg.modulo = '26' AND modulosg.produto = '4', 'OK', '') AS '26_Inventario Fiscal',
IF( modulosg.modulo = '14' AND modulosg.produto = '4', 'OK', '') AS '14_Movimentacao de Produtos',
IF( modulosg.modulo = '30' AND modulosg.produto = '4', 'OK', '') AS '30_Movimento de Caixa',
IF( modulosg.modulo = '52' AND modulosg.produto = '4', 'OK', '') AS '52_Producao para entrega',
IF( modulosg.modulo = '1' AND modulosg.produto = '4', 'OK', '') AS '1_Produtos e Precos',
IF( modulosg.modulo = '57' AND modulosg.produto = '4', 'OK', '') AS '57_Quartos',
IF( modulosg.modulo = '127' AND modulosg.produto = '12', 'OK', '') AS '127_TEF CLOUD (SCOPE GETCARD DIRETO COM INTEGRADOR)',
IF( modulosg.modulo = '64' AND modulosg.produto = '12', 'OK', '') AS '64_TEF CLOUD (SCOPE GETCARD)',
IF( modulosg.modulo = '342' AND modulosg.produto = '12', 'OK', '') AS '342_TEF CLOUD (SITEF - REDE TLS FISERV)',
IF( modulosg.modulo = '144' AND modulosg.produto = '12', 'OK', '') AS '144_TEF CLOUD (SITEF - REDE VPN GSURF)',
IF( modulosg.modulo = '350' AND modulosg.produto = '12', 'OK', '') AS '350_TEF CLOUD (SITEF - S.E.CONDUCTOR)',
IF( modulosg.modulo = '349' AND modulosg.produto = '12', 'OK', '') AS '349_TEF CLOUD (SITEF - TLS FISERV - S.E.CONDUCTOR)',
IF( modulosg.modulo = '336' AND modulosg.produto = '12', 'OK', '') AS '336_TEF CLOUD (SITEF - TLS FISERV)',
IF( modulosg.modulo = '62' AND modulosg.produto = '12', 'OK', '') AS '62_TEF CLOUD (SITEF - VPN GSURF)',
IF( modulosg.modulo = '210' AND modulosg.produto = '12', 'OK', '') AS '210_TEF CLOUD (SITEF GETCARD DIRETO COM INTEGRADOR)',
IF( modulosg.modulo = '66' AND modulosg.produto = '12', 'OK', '') AS '66_TEF CLOUD (SITEF SMART DIRETO COM INTEGRADOR)',
IF( modulosg.modulo = '65' AND modulosg.produto = '12', 'OK', '') AS '65_TEF CLOUD (SITEF TEFWAY DIRETO COM INTEGRADOR)',
IF( modulosg.modulo = '145' AND modulosg.produto = '12', 'OK', '') AS '145_TEF CLOUD (SITEF)',
IF( modulosg.modulo = '63' AND modulosg.produto = '12', 'OK', '') AS '63_TEF LOCAL (SCOPE GETCARD)',
IF( modulosg.modulo = '352' AND modulosg.produto = '12', 'OK', '') AS '352_TEF REDE (SITEF - S.E.CONDUCTOR)',
IF( modulosg.modulo = '351' AND modulosg.produto = '12', 'OK', '') AS '351_TEF REDE (SITEF - TLS FISERV - S.E.CONDUCTOR)',
IF( modulosg.modulo = '70' AND modulosg.produto = '12', 'OK', '') AS '70_TEF SITEF - OUTROS',
IF( modulosg.modulo = '69' AND modulosg.produto = '12', 'OK', '') AS '69_TEF SITEF - TEFWAY',
IF( modulosg.modulo = '79' AND modulosg.produto = '20', 'OK', '') AS '79_Ajuste de Estoque',
IF( modulosg.modulo = '252' AND modulosg.produto = '20', 'OK', '') AS '252_Arquivos Fiscais',
IF( modulosg.modulo = '13' AND modulosg.produto = '20', 'OK', '') AS '13_Balanco',
IF( modulosg.modulo = '85' AND modulosg.produto = '20', 'OK', '') AS '85_Bordero',
IF( modulosg.modulo = '92' AND modulosg.produto = '20', 'OK', '') AS '92_Cadastros diversos',
IF( modulosg.modulo = '82' AND modulosg.produto = '20', 'OK', '') AS '82_Caixas e bancos',
IF( modulosg.modulo = '98' AND modulosg.produto = '20', 'OK', '') AS '98_Cartao de credito',
IF( modulosg.modulo = '94' AND modulosg.produto = '20', 'OK', '') AS '94_CFOP',
IF( modulosg.modulo = '83' AND modulosg.produto = '20', 'OK', '') AS '83_Cheques pr¢prio',
IF( modulosg.modulo = '84' AND modulosg.produto = '20', 'OK', '') AS '84_Cheques terceiros',
IF( modulosg.modulo = '86' AND modulosg.produto = '20', 'OK', '') AS '86_Clientes e fornecedores',
IF( modulosg.modulo = '24' AND modulosg.produto = '20', 'OK', '') AS '24_Compras',
IF( modulosg.modulo = '90' AND modulosg.produto = '20', 'OK', '') AS '90_Condicao de pagamento',
IF( modulosg.modulo = '77' AND modulosg.produto = '20', 'OK', '') AS '77_Consignado',
IF( modulosg.modulo = '95' AND modulosg.produto = '20', 'OK', '') AS '95_Contabilista',
IF( modulosg.modulo = '4' AND modulosg.produto = '20', 'OK', '') AS '4_Contas a pagar',
IF( modulosg.modulo = '5' AND modulosg.produto = '20', 'OK', '') AS '5_Contas a receber',
IF( modulosg.modulo = '9' AND modulosg.produto = '20', 'OK', '') AS '9_Contra Vales',
IF( modulosg.modulo = '251' AND modulosg.produto = '20', 'OK', '') AS '251_Controle de despesas',
IF( modulosg.modulo = '209' AND modulosg.produto = '20', 'OK', '') AS '209_Controle de perdas',
IF( modulosg.modulo = '37' AND modulosg.produto = '20', 'OK', '') AS '37_Controle Patrimonial',
IF( modulosg.modulo = '105' AND modulosg.produto = '20', 'OK', '') AS '105_Equipamentos',
IF( modulosg.modulo = '87' AND modulosg.produto = '20', 'OK', '') AS '87_Fabricantes',
IF( modulosg.modulo = '99' AND modulosg.produto = '20', 'OK', '') AS '99_Grupo de imposto',
IF( modulosg.modulo = '91' AND modulosg.produto = '20', 'OK', '') AS '91_ICMS por estado',
IF( modulosg.modulo = '96' AND modulosg.produto = '20', 'OK', '') AS '96_Impressora fiscal',
IF( modulosg.modulo = '123' AND modulosg.produto = '20', 'OK', '') AS '123_Integracao TEF Scope',
IF( modulosg.modulo = '102' AND modulosg.produto = '20', 'OK', '') AS '102_Locacao',
IF( modulosg.modulo = '112' AND modulosg.produto = '20', 'OK', '') AS '112_MonitoraNFE',
IF( modulosg.modulo = '78' AND modulosg.produto = '20', 'OK', '') AS '78_Multipedido',
IF( modulosg.modulo = '76' AND modulosg.produto = '20', 'OK', '') AS '76_Orcamentos',
IF( modulosg.modulo = '101' AND modulosg.produto = '20', 'OK', '') AS '101_Ordem de servico',
IF( modulosg.modulo = '80' AND modulosg.produto = '20', 'OK', '') AS '80_Pedido de compras',
IF( modulosg.modulo = '100' AND modulosg.produto = '20', 'OK', '') AS '100_Plano de contas',
IF( modulosg.modulo = '1' AND modulosg.produto = '20', 'OK', '') AS '1_Produtos',
IF( modulosg.modulo = '74' AND modulosg.produto = '20', 'OK', '') AS '74_SAT',
IF( modulosg.modulo = '97' AND modulosg.produto = '20', 'OK', '') AS '97_Tabela de precos',
IF( modulosg.modulo = '33' AND modulosg.produto = '20', 'OK', '') AS '33_Transferencia',
IF( modulosg.modulo = '81' AND modulosg.produto = '20', 'OK', '') AS '81_Transformacao',
IF( modulosg.modulo = '89' AND modulosg.produto = '20', 'OK', '') AS '89_Transportadora',
IF( modulosg.modulo = '39' AND modulosg.produto = '20', 'OK', '') AS '39_Veiculos',
IF( modulosg.modulo = '93' AND modulosg.produto = '20', 'OK', '') AS '93_Vencimento',
IF( modulosg.modulo = '11' AND modulosg.produto = '20', 'OK', '') AS '11_Vendas',
IF( modulosg.modulo = '88' AND modulosg.produto = '20', 'OK', '') AS '88_Vendedores-Usuario',
IF( modulosg.modulo = '290' AND modulosg.produto = '21', 'OK', '') AS '290_SGDFe Central (sgdfe.sgsistemas.com.br / sgdfe.sgh',
IF( modulosg.modulo = '290' AND modulosg.produto = '22', 'OK', '') AS '290_SGDFe Central (sgdfe.sgsistemas.com.br / sgdfe.sgh',
IF( modulosg.modulo = '113' AND modulosg.produto = '23', 'OK', '') AS '113_KW',
IF( modulosg.modulo = '114' AND modulosg.produto = '23', 'OK', '') AS '114_RJK',
IF( modulosg.modulo = '156' AND modulosg.produto = '34', 'OK', '') AS '156_Controle de Cashback',
IF( modulosg.modulo = '293' AND modulosg.produto = '34', 'OK', '') AS '293_Controle de Ofertas',
IF( modulosg.modulo = '138' AND modulosg.produto = '34', 'OK', '') AS '138_Controle de Pontos',
IF( modulosg.modulo = '292' AND modulosg.produto = '34', 'OK', '') AS '292_Controle de Pontos com Oferta por Cashback',
IF( modulosg.modulo = '149' AND modulosg.produto = '34', 'OK', '') AS '149_Repasse',
IF( modulosg.modulo = '223' AND modulosg.produto = '39', 'OK', '') AS '223_Alteracoes',
IF( modulosg.modulo = '281' AND modulosg.produto = '39', 'OK', '') AS '281_Bancario',
IF( modulosg.modulo = '274' AND modulosg.produto = '39', 'OK', '') AS '274_Cadastro de Clientes e Funcionarios',
IF( modulosg.modulo = '186' AND modulosg.produto = '39', 'OK', '') AS '186_Cadastro de Fornecedores',
IF( modulosg.modulo = '184' AND modulosg.produto = '39', 'OK', '') AS '184_Cadastro de Produtos',
IF( modulosg.modulo = '216' AND modulosg.produto = '39', 'OK', '') AS '216_Cadastro de Tabela de Precos',
IF( modulosg.modulo = '202' AND modulosg.produto = '39', 'OK', '') AS '202_Cartao Presente',
IF( modulosg.modulo = '289' AND modulosg.produto = '39', 'OK', '') AS '289_Catalogo',
IF( modulosg.modulo = '193' AND modulosg.produto = '39', 'OK', '') AS '193_Clube de fidelizacao (Pontos)',
IF( modulosg.modulo = '195' AND modulosg.produto = '39', 'OK', '') AS '195_Comissao: Por Valor,Produto e Escalonado',
IF( modulosg.modulo = '330' AND modulosg.produto = '39', 'OK', '') AS '330_Compras',
IF( modulosg.modulo = '108' AND modulosg.produto = '39', 'OK', '') AS '108_Conciliacao de cartoes - Conciflex',
IF( modulosg.modulo = '196' AND modulosg.produto = '39', 'OK', '') AS '196_Consignado',
IF( modulosg.modulo = '199' AND modulosg.produto = '39', 'OK', '') AS '199_Contas a Pagar',
IF( modulosg.modulo = '200' AND modulosg.produto = '39', 'OK', '') AS '200_Contas a Receber',
IF( modulosg.modulo = '244' AND modulosg.produto = '39', 'OK', '') AS '244_Contrato de Cartao de Credito',
IF( modulosg.modulo = '107' AND modulosg.produto = '39', 'OK', '') AS '107_Contribuicao Solidaria',
IF( modulosg.modulo = '187' AND modulosg.produto = '39', 'OK', '') AS '187_Controle Caixa',
IF( modulosg.modulo = '188' AND modulosg.produto = '39', 'OK', '') AS '188_Controle de Estoque-Quantidade/Grade/Cor',
IF( modulosg.modulo = '192' AND modulosg.produto = '39', 'OK', '') AS '192_Controle de Manequim',
IF( modulosg.modulo = '194' AND modulosg.produto = '39', 'OK', '') AS '194_Controle de Metas',
IF( modulosg.modulo = '277' AND modulosg.produto = '39', 'OK', '') AS '277_Controle de Trocas',
IF( modulosg.modulo = '331' AND modulosg.produto = '39', 'OK', '') AS '331_Cotacao',
IF( modulosg.modulo = '332' AND modulosg.produto = '39', 'OK', '') AS '332_Cotacao Online',
IF( modulosg.modulo = '191' AND modulosg.produto = '39', 'OK', '') AS '191_Crediario',
IF( modulosg.modulo = '206' AND modulosg.produto = '39', 'OK', '') AS '206_D.R.E',
IF( modulosg.modulo = '183' AND modulosg.produto = '39', 'OK', '') AS '183_DashBoards',
IF( modulosg.modulo = '282' AND modulosg.produto = '39', 'OK', '') AS '282_Despesas',
IF( modulosg.modulo = '278' AND modulosg.produto = '39', 'OK', '') AS '278_Devolucoes de venda',
IF( modulosg.modulo = '218' AND modulosg.produto = '39', 'OK', '') AS '218_Emissao de Boletos',
IF( modulosg.modulo = '328' AND modulosg.produto = '39', 'OK', '') AS '328_Emissao de MDF-e',
IF( modulosg.modulo = '329' AND modulosg.produto = '39', 'OK', '') AS '329_Emissao de NFS-e',
IF( modulosg.modulo = '275' AND modulosg.produto = '39', 'OK', '') AS '275_Emissao de SAT / MFE',
IF( modulosg.modulo = '190' AND modulosg.produto = '39', 'OK', '') AS '190_Entrada de notas por XML',
IF( modulosg.modulo = '325' AND modulosg.produto = '39', 'OK', '') AS '325_Escrita fiscal',
IF( modulosg.modulo = '189' AND modulosg.produto = '39', 'OK', '') AS '189_Etiquetas',
IF( modulosg.modulo = '298' AND modulosg.produto = '39', 'OK', '') AS '298_Fracionamento',
IF( modulosg.modulo = '284' AND modulosg.produto = '39', 'OK', '') AS '284_Gerenciamento',
IF( modulosg.modulo = '301' AND modulosg.produto = '39', 'OK', '') AS '301_Homologacao Integradores',
IF( modulosg.modulo = '313' AND modulosg.produto = '39', 'OK', '') AS '313_Integracao Ad Rocket',
IF( modulosg.modulo = '159' AND modulosg.produto = '39', 'OK', '') AS '159_Integracao APPMercados',
IF( modulosg.modulo = '320' AND modulosg.produto = '39', 'OK', '') AS '320_Integracao Area Central - API',
IF( modulosg.modulo = '343' AND modulosg.produto = '39', 'OK', '') AS '343_Integracao Cartaz Facil',
IF( modulosg.modulo = '345' AND modulosg.produto = '39', 'OK', '') AS '345_Integracao Codevops',
IF( modulosg.modulo = '180' AND modulosg.produto = '39', 'OK', '') AS '180_Integracao Compre Facil',
IF( modulosg.modulo = '327' AND modulosg.produto = '39', 'OK', '') AS '327_Integracao Correios',
IF( modulosg.modulo = '174' AND modulosg.produto = '39', 'OK', '') AS '174_Integracao Cresce Vendas',
IF( modulosg.modulo = '344' AND modulosg.produto = '39', 'OK', '') AS '344_Integracao Dattion',
IF( modulosg.modulo = '182' AND modulosg.produto = '39', 'OK', '') AS '182_Integracao Deju',
IF( modulosg.modulo = '181' AND modulosg.produto = '39', 'OK', '') AS '181_Integracao Insta Buy',
IF( modulosg.modulo = '333' AND modulosg.produto = '39', 'OK', '') AS '333_Integracao Izi App',
IF( modulosg.modulo = '323' AND modulosg.produto = '39', 'OK', '') AS '323_Integracao Loja Integrada',
IF( modulosg.modulo = '163' AND modulosg.produto = '39', 'OK', '') AS '163_Integracao LOJAQUI',
IF( modulosg.modulo = '318' AND modulosg.produto = '39', 'OK', '') AS '318_Integracao Magazord',
IF( modulosg.modulo = '334' AND modulosg.produto = '39', 'OK', '') AS '334_Integracao Mercafacil',
IF( modulosg.modulo = '308' AND modulosg.produto = '39', 'OK', '') AS '308_Integracao Minus',
IF( modulosg.modulo = '319' AND modulosg.produto = '39', 'OK', '') AS '319_Integracao Nuvem Shop',
IF( modulosg.modulo = '312' AND modulosg.produto = '39', 'OK', '') AS '312_Integracao PagPix',
IF( modulosg.modulo = '317' AND modulosg.produto = '39', 'OK', '') AS '317_Integracao PlugLead',
IF( modulosg.modulo = '253' AND modulosg.produto = '39', 'OK', '') AS '253_Integracao Shipay',
IF( modulosg.modulo = '321' AND modulosg.produto = '39', 'OK', '') AS '321_Integracao Shopify',
IF( modulosg.modulo = '254' AND modulosg.produto = '39', 'OK', '') AS '254_Integracao Smart',
IF( modulosg.modulo = '311' AND modulosg.produto = '39', 'OK', '') AS '311_Integracao Supermercado Esperanca',
IF( modulosg.modulo = '322' AND modulosg.produto = '39', 'OK', '') AS '322_Integracao TI Soluti',
IF( modulosg.modulo = '171' AND modulosg.produto = '39', 'OK', '') AS '171_Integracao Tray',
IF( modulosg.modulo = '256' AND modulosg.produto = '39', 'OK', '') AS '256_Integracao Web Jasper',
IF( modulosg.modulo = '280' AND modulosg.produto = '39', 'OK', '') AS '280_Inventario de Estoque (Parcial ou Total)',
IF( modulosg.modulo = '324' AND modulosg.produto = '39', 'OK', '') AS '324_Inventario fiscal',
IF( modulosg.modulo = '245' AND modulosg.produto = '39', 'OK', '') AS '245_Movimentacao de Cheques',
IF( modulosg.modulo = '283' AND modulosg.produto = '39', 'OK', '') AS '283_Multilojas - Requisicao/Transferencia',
IF( modulosg.modulo = '248' AND modulosg.produto = '39', 'OK', '') AS '248_Nota Avulsa',
IF( modulosg.modulo = '101' AND modulosg.produto = '39', 'OK', '') AS '101_Ordem de Servico',
IF( modulosg.modulo = '221' AND modulosg.produto = '39', 'OK', '') AS '221_PDV OFFLINE',
IF( modulosg.modulo = '297' AND modulosg.produto = '39', 'OK', '') AS '297_Producao',
IF( modulosg.modulo = '204' AND modulosg.produto = '39', 'OK', '') AS '204_Promocoes',
IF( modulosg.modulo = '224' AND modulosg.produto = '39', 'OK', '') AS '224_Recibo Avulso',
IF( modulosg.modulo = '205' AND modulosg.produto = '39', 'OK', '') AS '205_Relat¢rios Dinƒmicos',
IF( modulosg.modulo = '235' AND modulosg.produto = '39', 'OK', '') AS '235_Vale para Funcionario',
IF( modulosg.modulo = '203' AND modulosg.produto = '39', 'OK', '') AS '203_Venda Ambulante/Sacoleiras',
IF( modulosg.modulo = '151' AND modulosg.produto = '42', 'OK', '') AS '151_Iti - Itau',
IF( modulosg.modulo = '304' AND modulosg.produto = '46', 'OK', '') AS '304_GOMenu Consulta (QR Code somente para consulta)',
IF( modulosg.modulo = '305' AND modulosg.produto = '46', 'OK', '') AS '305_GOMenu Delivery (Delivery)',
IF( modulosg.modulo = '306' AND modulosg.produto = '46', 'OK', '') AS '306_GOMenu Mobile (Consulta + pedido pelo celular do c',
IF( modulosg.modulo = '307' AND modulosg.produto = '46', 'OK', '') AS '307_GOMenu Pedido (Tablet na mesa)',
IF( modulosg.modulo = '223' AND modulosg.produto = '48', 'OK', '') AS '223_Alteracoes',
IF( modulosg.modulo = '281' AND modulosg.produto = '48', 'OK', '') AS '281_Bancario',
IF( modulosg.modulo = '274' AND modulosg.produto = '48', 'OK', '') AS '274_Cadastro de Clientes e Funcionarios',
IF( modulosg.modulo = '186' AND modulosg.produto = '48', 'OK', '') AS '186_Cadastro de Fornecedores',
IF( modulosg.modulo = '184' AND modulosg.produto = '48', 'OK', '') AS '184_Cadastro de Produtos',
IF( modulosg.modulo = '216' AND modulosg.produto = '48', 'OK', '') AS '216_Cadastro de Tabela de Precos',
IF( modulosg.modulo = '202' AND modulosg.produto = '48', 'OK', '') AS '202_Cartao Presente',
IF( modulosg.modulo = '289' AND modulosg.produto = '48', 'OK', '') AS '289_Catalogo',
IF( modulosg.modulo = '193' AND modulosg.produto = '48', 'OK', '') AS '193_Clube de fidelizacao (Pontos)',
IF( modulosg.modulo = '195' AND modulosg.produto = '48', 'OK', '') AS '195_Comissao: Por Valor,Produto e Escalonado',
IF( modulosg.modulo = '330' AND modulosg.produto = '48', 'OK', '') AS '330_Compras',
IF( modulosg.modulo = '108' AND modulosg.produto = '48', 'OK', '') AS '108_Conciliacao de cartoes - Conciflex',
IF( modulosg.modulo = '196' AND modulosg.produto = '48', 'OK', '') AS '196_Consignado',
IF( modulosg.modulo = '199' AND modulosg.produto = '48', 'OK', '') AS '199_Contas a Pagar',
IF( modulosg.modulo = '200' AND modulosg.produto = '48', 'OK', '') AS '200_Contas a Receber',
IF( modulosg.modulo = '244' AND modulosg.produto = '48', 'OK', '') AS '244_Contrato de Cartao de Credito',
IF( modulosg.modulo = '107' AND modulosg.produto = '48', 'OK', '') AS '107_Contribuicao Solidaria',
IF( modulosg.modulo = '187' AND modulosg.produto = '48', 'OK', '') AS '187_Controle Caixa',
IF( modulosg.modulo = '188' AND modulosg.produto = '48', 'OK', '') AS '188_Controle de Estoque-Quantidade/Grade/Cor',
IF( modulosg.modulo = '192' AND modulosg.produto = '48', 'OK', '') AS '192_Controle de Manequim',
IF( modulosg.modulo = '194' AND modulosg.produto = '48', 'OK', '') AS '194_Controle de Metas',
IF( modulosg.modulo = '277' AND modulosg.produto = '48', 'OK', '') AS '277_Controle de Trocas',
IF( modulosg.modulo = '331' AND modulosg.produto = '48', 'OK', '') AS '331_Cotacao',
IF( modulosg.modulo = '332' AND modulosg.produto = '48', 'OK', '') AS '332_Cotacao Online',
IF( modulosg.modulo = '191' AND modulosg.produto = '48', 'OK', '') AS '191_Crediario',
IF( modulosg.modulo = '206' AND modulosg.produto = '48', 'OK', '') AS '206_D.R.E',
IF( modulosg.modulo = '183' AND modulosg.produto = '48', 'OK', '') AS '183_DashBoards',
IF( modulosg.modulo = '282' AND modulosg.produto = '48', 'OK', '') AS '282_Despesas',
IF( modulosg.modulo = '278' AND modulosg.produto = '48', 'OK', '') AS '278_Devolucoes de venda',
IF( modulosg.modulo = '218' AND modulosg.produto = '48', 'OK', '') AS '218_Emissao de Boletos',
IF( modulosg.modulo = '328' AND modulosg.produto = '48', 'OK', '') AS '328_Emissao de MDF-e',
IF( modulosg.modulo = '329' AND modulosg.produto = '48', 'OK', '') AS '329_Emissao de NFS-e',
IF( modulosg.modulo = '275' AND modulosg.produto = '48', 'OK', '') AS '275_Emissao de SAT / MFE',
IF( modulosg.modulo = '190' AND modulosg.produto = '48', 'OK', '') AS '190_Entrada de notas por XML',
IF( modulosg.modulo = '325' AND modulosg.produto = '48', 'OK', '') AS '325_Escrita fiscal',
IF( modulosg.modulo = '189' AND modulosg.produto = '48', 'OK', '') AS '189_Etiquetas',
IF( modulosg.modulo = '298' AND modulosg.produto = '48', 'OK', '') AS '298_Fracionamento',
IF( modulosg.modulo = '284' AND modulosg.produto = '48', 'OK', '') AS '284_Gerenciamento',
IF( modulosg.modulo = '301' AND modulosg.produto = '48', 'OK', '') AS '301_Homologacao Integradores',
IF( modulosg.modulo = '313' AND modulosg.produto = '48', 'OK', '') AS '313_Integracao Ad Rocket',
IF( modulosg.modulo = '159' AND modulosg.produto = '48', 'OK', '') AS '159_Integracao APPMercados',
IF( modulosg.modulo = '320' AND modulosg.produto = '48', 'OK', '') AS '320_Integracao Area Central - API',
IF( modulosg.modulo = '343' AND modulosg.produto = '48', 'OK', '') AS '343_Integracao Cartaz Facil',
IF( modulosg.modulo = '345' AND modulosg.produto = '48', 'OK', '') AS '345_Integracao Codevops',
IF( modulosg.modulo = '180' AND modulosg.produto = '48', 'OK', '') AS '180_Integracao Compre Facil',
IF( modulosg.modulo = '327' AND modulosg.produto = '48', 'OK', '') AS '327_Integracao Correios',
IF( modulosg.modulo = '174' AND modulosg.produto = '48', 'OK', '') AS '174_Integracao Cresce Vendas',
IF( modulosg.modulo = '344' AND modulosg.produto = '48', 'OK', '') AS '344_Integracao Dattion',
IF( modulosg.modulo = '182' AND modulosg.produto = '48', 'OK', '') AS '182_Integracao Deju',
IF( modulosg.modulo = '181' AND modulosg.produto = '48', 'OK', '') AS '181_Integracao Insta Buy',
IF( modulosg.modulo = '333' AND modulosg.produto = '48', 'OK', '') AS '333_Integracao Izi App',
IF( modulosg.modulo = '323' AND modulosg.produto = '48', 'OK', '') AS '323_Integracao Loja Integrada',
IF( modulosg.modulo = '163' AND modulosg.produto = '48', 'OK', '') AS '163_Integracao LOJAQUI',
IF( modulosg.modulo = '318' AND modulosg.produto = '48', 'OK', '') AS '318_Integracao Magazord',
IF( modulosg.modulo = '334' AND modulosg.produto = '48', 'OK', '') AS '334_Integracao Mercafacil',
IF( modulosg.modulo = '308' AND modulosg.produto = '48', 'OK', '') AS '308_Integracao Minus',
IF( modulosg.modulo = '319' AND modulosg.produto = '48', 'OK', '') AS '319_Integracao Nuvem Shop',
IF( modulosg.modulo = '312' AND modulosg.produto = '48', 'OK', '') AS '312_Integracao PagPix',
IF( modulosg.modulo = '317' AND modulosg.produto = '48', 'OK', '') AS '317_Integracao PlugLead',
IF( modulosg.modulo = '253' AND modulosg.produto = '48', 'OK', '') AS '253_Integracao Shipay',
IF( modulosg.modulo = '321' AND modulosg.produto = '48', 'OK', '') AS '321_Integracao Shopify',
IF( modulosg.modulo = '254' AND modulosg.produto = '48', 'OK', '') AS '254_Integracao Smart',
IF( modulosg.modulo = '311' AND modulosg.produto = '48', 'OK', '') AS '311_Integracao Supermercado Esperanca',
IF( modulosg.modulo = '322' AND modulosg.produto = '48', 'OK', '') AS '322_Integracao TI Soluti',
IF( modulosg.modulo = '171' AND modulosg.produto = '48', 'OK', '') AS '171_Integracao Tray',
IF( modulosg.modulo = '256' AND modulosg.produto = '48', 'OK', '') AS '256_Integracao Web Jasper',
IF( modulosg.modulo = '280' AND modulosg.produto = '48', 'OK', '') AS '280_Inventario de Estoque (Parcial ou Total)',
IF( modulosg.modulo = '324' AND modulosg.produto = '48', 'OK', '') AS '324_Invetario fiscal',
IF( modulosg.modulo = '245' AND modulosg.produto = '48', 'OK', '') AS '245_Movimentacao de Cheques',
IF( modulosg.modulo = '283' AND modulosg.produto = '48', 'OK', '') AS '283_Multilojas - Requisicao/Transferencia',
IF( modulosg.modulo = '248' AND modulosg.produto = '48', 'OK', '') AS '248_Nota Avulsa',
IF( modulosg.modulo = '101' AND modulosg.produto = '48', 'OK', '') AS '101_Ordem de Servico',
IF( modulosg.modulo = '221' AND modulosg.produto = '48', 'OK', '') AS '221_PDV OFFLINE',
IF( modulosg.modulo = '297' AND modulosg.produto = '48', 'OK', '') AS '297_Producao',
IF( modulosg.modulo = '204' AND modulosg.produto = '48', 'OK', '') AS '204_Promocoes',
IF( modulosg.modulo = '224' AND modulosg.produto = '48', 'OK', '') AS '224_Recibo Avulso',
IF( modulosg.modulo = '205' AND modulosg.produto = '48', 'OK', '') AS '205_Relat¢rios Dinƒmicos',
IF( modulosg.modulo = '235' AND modulosg.produto = '48', 'OK', '') AS '235_Vale para Funcionario',
IF( modulosg.modulo = '203' AND modulosg.produto = '48', 'OK', '') AS '203_Venda Ambulante/Sacoleiras',
IF( modulosg.modulo = '223' AND modulosg.produto = '50', 'OK', '') AS '223_Alteracoes',
IF( modulosg.modulo = '281' AND modulosg.produto = '50', 'OK', '') AS '281_Bancario',
IF( modulosg.modulo = '274' AND modulosg.produto = '50', 'OK', '') AS '274_Cadastro de Clientes e Funcionarios',
IF( modulosg.modulo = '186' AND modulosg.produto = '50', 'OK', '') AS '186_Cadastro de Fornecedores',
IF( modulosg.modulo = '184' AND modulosg.produto = '50', 'OK', '') AS '184_Cadastro de Produtos',
IF( modulosg.modulo = '216' AND modulosg.produto = '50', 'OK', '') AS '216_Cadastro de Tabela de Precos',
IF( modulosg.modulo = '202' AND modulosg.produto = '50', 'OK', '') AS '202_Cartao Presente',
IF( modulosg.modulo = '289' AND modulosg.produto = '50', 'OK', '') AS '289_Catalogo',
IF( modulosg.modulo = '193' AND modulosg.produto = '50', 'OK', '') AS '193_Clube de fidelizacao (Pontos)',
IF( modulosg.modulo = '195' AND modulosg.produto = '50', 'OK', '') AS '195_Comissao: Por Valor,Produto e Escalonado',
IF( modulosg.modulo = '330' AND modulosg.produto = '50', 'OK', '') AS '330_Compras',
IF( modulosg.modulo = '108' AND modulosg.produto = '50', 'OK', '') AS '108_Conciliacao de cartoes - Conciflex',
IF( modulosg.modulo = '196' AND modulosg.produto = '50', 'OK', '') AS '196_Consignado',
IF( modulosg.modulo = '199' AND modulosg.produto = '50', 'OK', '') AS '199_Contas a Pagar',
IF( modulosg.modulo = '200' AND modulosg.produto = '50', 'OK', '') AS '200_Contas a Receber',
IF( modulosg.modulo = '244' AND modulosg.produto = '50', 'OK', '') AS '244_Contrato de Cartao de Credito',
IF( modulosg.modulo = '187' AND modulosg.produto = '50', 'OK', '') AS '187_Controle Caixa',
IF( modulosg.modulo = '188' AND modulosg.produto = '50', 'OK', '') AS '188_Controle de Estoque-Quantidade/Grade/Cor',
IF( modulosg.modulo = '192' AND modulosg.produto = '50', 'OK', '') AS '192_Controle de Manequim',
IF( modulosg.modulo = '194' AND modulosg.produto = '50', 'OK', '') AS '194_Controle de Metas',
IF( modulosg.modulo = '277' AND modulosg.produto = '50', 'OK', '') AS '277_Controle de Trocas',
IF( modulosg.modulo = '331' AND modulosg.produto = '50', 'OK', '') AS '331_Cotacao',
IF( modulosg.modulo = '332' AND modulosg.produto = '50', 'OK', '') AS '332_Cotacao Online',
IF( modulosg.modulo = '191' AND modulosg.produto = '50', 'OK', '') AS '191_Crediario',
IF( modulosg.modulo = '206' AND modulosg.produto = '50', 'OK', '') AS '206_D.R.E',
IF( modulosg.modulo = '183' AND modulosg.produto = '50', 'OK', '') AS '183_DashBoards',
IF( modulosg.modulo = '282' AND modulosg.produto = '50', 'OK', '') AS '282_Despesas',
IF( modulosg.modulo = '278' AND modulosg.produto = '50', 'OK', '') AS '278_Devolucoes de venda',
IF( modulosg.modulo = '218' AND modulosg.produto = '50', 'OK', '') AS '218_Emissao de Boletos',
IF( modulosg.modulo = '328' AND modulosg.produto = '50', 'OK', '') AS '328_Emissao de MDF-e',
IF( modulosg.modulo = '329' AND modulosg.produto = '50', 'OK', '') AS '329_Emissao de NFS-e',
IF( modulosg.modulo = '275' AND modulosg.produto = '50', 'OK', '') AS '275_Emissao de SAT / MFE',
IF( modulosg.modulo = '190' AND modulosg.produto = '50', 'OK', '') AS '190_Entrada de notas por XML',
IF( modulosg.modulo = '325' AND modulosg.produto = '50', 'OK', '') AS '325_Escrita fiscal',
IF( modulosg.modulo = '189' AND modulosg.produto = '50', 'OK', '') AS '189_Etiquetas',
IF( modulosg.modulo = '284' AND modulosg.produto = '50', 'OK', '') AS '284_Gerenciamento',
IF( modulosg.modulo = '301' AND modulosg.produto = '50', 'OK', '') AS '301_Homologacao Integradores',
IF( modulosg.modulo = '313' AND modulosg.produto = '50', 'OK', '') AS '313_Integracao Ad Rocket',
IF( modulosg.modulo = '159' AND modulosg.produto = '50', 'OK', '') AS '159_Integracao APPMercados',
IF( modulosg.modulo = '320' AND modulosg.produto = '50', 'OK', '') AS '320_Integracao Area Central - API',
IF( modulosg.modulo = '343' AND modulosg.produto = '50', 'OK', '') AS '343_Integracao Cartaz Facil',
IF( modulosg.modulo = '345' AND modulosg.produto = '50', 'OK', '') AS '345_Integracao Codevops',
IF( modulosg.modulo = '180' AND modulosg.produto = '50', 'OK', '') AS '180_Integracao Compre Facil',
IF( modulosg.modulo = '327' AND modulosg.produto = '50', 'OK', '') AS '327_Integracao Correios',
IF( modulosg.modulo = '174' AND modulosg.produto = '50', 'OK', '') AS '174_Integracao Cresce Vendas',
IF( modulosg.modulo = '344' AND modulosg.produto = '50', 'OK', '') AS '344_Integracao Dattion',
IF( modulosg.modulo = '182' AND modulosg.produto = '50', 'OK', '') AS '182_Integracao Deju',
IF( modulosg.modulo = '181' AND modulosg.produto = '50', 'OK', '') AS '181_Integracao Insta Buy',
IF( modulosg.modulo = '333' AND modulosg.produto = '50', 'OK', '') AS '333_Integracao Izi App',
IF( modulosg.modulo = '323' AND modulosg.produto = '50', 'OK', '') AS '323_Integracao Loja Integrada',
IF( modulosg.modulo = '163' AND modulosg.produto = '50', 'OK', '') AS '163_Integracao LOJAQUI',
IF( modulosg.modulo = '318' AND modulosg.produto = '50', 'OK', '') AS '318_Integracao Magazord',
IF( modulosg.modulo = '308' AND modulosg.produto = '50', 'OK', '') AS '308_Integracao Minus',
IF( modulosg.modulo = '319' AND modulosg.produto = '50', 'OK', '') AS '319_Integracao Nuvem Shop',
IF( modulosg.modulo = '312' AND modulosg.produto = '50', 'OK', '') AS '312_Integracao PagPix',
IF( modulosg.modulo = '317' AND modulosg.produto = '50', 'OK', '') AS '317_Integracao PlugLead',
IF( modulosg.modulo = '253' AND modulosg.produto = '50', 'OK', '') AS '253_Integracao Shipay',
IF( modulosg.modulo = '321' AND modulosg.produto = '50', 'OK', '') AS '321_Integracao Shopify',
IF( modulosg.modulo = '254' AND modulosg.produto = '50', 'OK', '') AS '254_Integracao Smart',
IF( modulosg.modulo = '311' AND modulosg.produto = '50', 'OK', '') AS '311_Integracao Supermercado Esperanca',
IF( modulosg.modulo = '322' AND modulosg.produto = '50', 'OK', '') AS '322_Integracao TI Soluti',
IF( modulosg.modulo = '171' AND modulosg.produto = '50', 'OK', '') AS '171_Integracao Tray',
IF( modulosg.modulo = '256' AND modulosg.produto = '50', 'OK', '') AS '256_Integracao Web Jasper',
IF( modulosg.modulo = '280' AND modulosg.produto = '50', 'OK', '') AS '280_Inventario de Estoque (Parcial ou Total)',
IF( modulosg.modulo = '324' AND modulosg.produto = '50', 'OK', '') AS '324_Invetario fiscal',
IF( modulosg.modulo = '245' AND modulosg.produto = '50', 'OK', '') AS '245_Movimentacao de Cheques',
IF( modulosg.modulo = '283' AND modulosg.produto = '50', 'OK', '') AS '283_Multilojas - Requisicao/Transferencia',
IF( modulosg.modulo = '248' AND modulosg.produto = '50', 'OK', '') AS '248_Nota Avulsa',
IF( modulosg.modulo = '101' AND modulosg.produto = '50', 'OK', '') AS '101_Ordem de Servico',
IF( modulosg.modulo = '221' AND modulosg.produto = '50', 'OK', '') AS '221_PDV OFFLINE',
IF( modulosg.modulo = '204' AND modulosg.produto = '50', 'OK', '') AS '204_Promocoes',
IF( modulosg.modulo = '224' AND modulosg.produto = '50', 'OK', '') AS '224_Recibo Avulso',
IF( modulosg.modulo = '205' AND modulosg.produto = '50', 'OK', '') AS '205_Relat¢rios Dinƒmicos',
IF( modulosg.modulo = '235' AND modulosg.produto = '50', 'OK', '') AS '235_Vale para Funcionario',
IF( modulosg.modulo = '203' AND modulosg.produto = '50', 'OK', '') AS '203_Venda Ambulante/Sacoleiras',
IF( modulosg.modulo = '339' AND modulosg.produto = '57', 'OK', '') AS '339_CTe',
IF( modulosg.modulo = '340' AND modulosg.produto = '57', 'OK', '') AS '340_MDFe',
IF( modulosg.modulo = '341' AND modulosg.produto = '57', 'OK', '') AS '341_NFCe',
IF( modulosg.modulo = '337' AND modulosg.produto = '57', 'OK', '') AS '337_NFe',
IF( modulosg.modulo = '338' AND modulosg.produto = '57', 'OK', '') AS '338_NFSe' FROM modulosg GROUP BY cnpj
)  modulos on
    modulos.CNPJMODULO = sg.cgc
left join (
	select 
		cnpj as CNPJPDV,
	    SUM(qtdpdv) as "TOTAL_PDVs",
    
    SUBQUERY TOTAL PDVS

)   quantidadesPDV on quantidadesPDV.CNPJPDV = sg.cgc
	left join (		
	select 
		cnpj as CNPJESTACOES,
	    SUM(qtdestac) as "TOTAL_ESTACOES",

    SUBQUERY TOTAL ESTACOES

)   quantidadesESTACOES on quantidadesESTACOES.CNPJESTACOES = sg.cgc
left join (
		select
			pd.cnpj as CNPJSUBMODULOS,

    SUBQUERY SUBMODULOS

) submodulos on submodulos.CNPJSUBMODULOS = sg.cgc
) as q