q.`APP CLUBE DE DESCONTO`,
q.`34_Controle de Pontos`,
q.`34_Repasse`,
q.`34_Controle de Cashback`,
q.`34_Controle de Pontos com Oferta por Cashback`,
q.`34_Controle de Ofertas`,
q.`APP PRE VENDA`,
q.`CARTEIRA DIGITAL`,
q.`42_Iti - Itau`,
q.`CTE (TECNOSPEED)`,
q.`9_submodulo`,
q.`EMISSAO 1 NFCE CONTINGENCIA`,
q.`EMULADOR`,
q.`FORCA DE VENDAS - HERBIE`,
q.`41_estacoes`,
q.`GESTAO IMEDIATA`,
q.`GOMENU`,
q.`46_GOMenu Consulta (QR Code somente para consulta)`,
q.`46_GOMenu Delivery (Delivery)`,
q.`46_GOMenu Mobile (Consulta + pedido pelo celular do c`,
q.`46_GOMenu Pedido (Tablet na mesa)`,
q.`INTEGRACAO PDV`,
q.`23_KW`,
q.`23_RJK`,
q.`INTEGRACAO VSELL MOBILE`,
q.`INTEGRACAO WMW`,
q.`MANAGER SAAS`,
q.`57_NFe`,
q.`57_NFSe`,
q.`57_CTe`,
q.`57_MDFe`,
q.`57_NFCe`,
q.`MDFE (TECNOSPEED)`,
q.`MDFE-FLEXDOCS`,
q.`MOBI POCKET`,
q.`MOBIGESTAO`,
q.`NFCE (TECNOSPEED)`,
q.`NFCE-FLEXDOCS`,
q.`NFE (TECNOSPEED)`,
q.`7_submodulo`,
q.`NFE-FLEXDOCS`,
q.`NFSE (SGCLOUD)`,
q.`NFSE (TECNOSPEED)`,
q.`8_submodulo`,
q.`NFSE-FLEXDOCS`,
q.`PORTAL XML`,
q.`SELF-CHECKOUT`,
q.`38_pdvs`,
q.`SG ACESSO`,
q.`SG ANALISE`,
q.`20_submodulo`,
q.`20_pdvs`,
q.`20_estacoes`,
q.`20_Produtos`,
q.`20_Contas a pagar`,
q.`20_Contas a receber`,
q.`20_Contra Vales`,
q.`20_Vendas`,
q.`20_Balanco`,
q.`20_Compras`,
q.`20_Transferencia`,
q.`20_Controle Patrimonial`,
q.`20_Veiculos`,
q.`20_SAT`,
q.`20_Orcamentos`,
q.`20_Consignado`,
q.`20_Multipedido`,
q.`20_Ajuste de Estoque`,
q.`20_Pedido de compras`,
q.`20_Transformacao`,
q.`20_Caixas e bancos`,
q.`20_Cheques pr¢prio`,
q.`20_Cheques terceiros`,
q.`20_Bordero`,
q.`20_Clientes e fornecedores`,
q.`20_Fabricantes`,
q.`20_Vendedores-Usuario`,
q.`20_Transportadora`,
q.`20_Condicao de pagamento`,
q.`20_ICMS por estado`,
q.`20_Cadastros diversos`,
q.`20_Vencimento`,
q.`20_CFOP`,
q.`20_Contabilista`,
q.`20_Impressora fiscal`,
q.`20_Tabela de precos`,
q.`20_Cartao de credito`,
q.`20_Grupo de imposto`,
q.`20_Plano de contas`,
q.`20_Ordem de servico`,
q.`20_Locacao`,
q.`20_Equipamentos`,
q.`20_MonitoraNFE`,
q.`20_Integracao TEF Scope`,
q.`20_Controle de perdas`,
q.`20_Controle de despesas`,
q.`20_Arquivos Fiscais`,
q.`SG CARTAZ`,
q.`SG COMANDA`,
q.`SG MAPA FISCAL`,
q.`28_submodulo`,
q.`SG VIEW`,
q.`SG-NFCE`,
q.`22_SGDFe Central (sgdfe.sgsistemas.com.br / sgdfe.sgh`,
q.`SG-NFE`,
q.`21_SGDFe Central (sgdfe.sgsistemas.com.br / sgdfe.sgh`,
q.`SGBI`,
q.`SGBLUE EYE`,
q.`SGCLOUD`,
q.`39_submodulo`,
q.`39_pdvs`,
q.`39_estacoes`,
q.`39_Ordem de Servico`,
q.`39_Contribuicao Solidaria`,
q.`39_Conciliacao de cartoes - Conciflex`,
q.`39_Integracao APPMercados`,
q.`39_Integracao LOJAQUI`,
q.`39_Integracao Tray`,
q.`39_Integracao Cresce Vendas`,
q.`39_Integracao Compre Facil`,
q.`39_Integracao Insta Buy`,
q.`39_Integracao Deju`,
q.`39_DashBoards`,
q.`39_Cadastro de Produtos`,
q.`39_Cadastro de Fornecedores`,
q.`39_Controle Caixa`,
q.`39_Controle de Estoque-Quantidade/Grade/Cor`,
q.`39_Etiquetas`,
q.`39_Entrada de notas por XML`,
q.`39_Crediario`,
q.`39_Controle de Manequim`,
q.`39_Clube de fidelizacao (Pontos)`,
q.`39_Controle de Metas`,
q.`39_Comissao: Por Valor,Produto e Escalonado`,
q.`39_Consignado`,
q.`39_Contas a Pagar`,
q.`39_Contas a Receber`,
q.`39_Cartao Presente`,
q.`39_Venda Ambulante/Sacoleiras`,
q.`39_Promocoes`,
q.`39_Relat¢rios Dinƒmicos`,
q.`39_D.R.E`,
q.`39_Cadastro de Tabela de Precos`,
q.`39_Emissao de Boletos`,
q.`39_PDV OFFLINE`,
q.`39_Alteracoes`,
q.`39_Recibo Avulso`,
q.`39_Vale para Funcionario`,
q.`39_Contrato de Cartao de Credito`,
q.`39_Movimentacao de Cheques`,
q.`39_Nota Avulsa`,
q.`39_Integracao Shipay`,
q.`39_Integracao Smart`,
q.`39_Integracao Web Jasper`,
q.`39_Cadastro de Clientes e Funcionarios`,
q.`39_Emissao de SAT / MFE`,
q.`39_Controle de Trocas`,
q.`39_Devolucoes de venda`,
q.`39_Inventario de Estoque (Parcial ou Total)`,
q.`39_Bancario`,
q.`39_Despesas`,
q.`39_Multilojas - Requisicao/Transferencia`,
q.`39_Gerenciamento`,
q.`39_Catalogo`,
q.`39_Producao`,
q.`39_Fracionamento`,
q.`39_Homologacao Integradores`,
q.`39_Integracao Minus`,
q.`39_Integracao Supermercado Esperanca`,
q.`39_Integracao PagPix`,
q.`39_Integracao Ad Rocket`,
q.`39_Integracao PlugLead`,
q.`39_Integracao Magazord`,
q.`39_Integracao Nuvem Shop`,
q.`39_Integracao Area Central - API`,
q.`39_Integracao Shopify`,
q.`39_Integracao TI Soluti`,
q.`39_Integracao Loja Integrada`,
q.`39_Inventario fiscal`,
q.`39_Escrita fiscal`,
q.`39_Integracao Correios`,
q.`39_Emissao de MDF-e`,
q.`39_Emissao de NFS-e`,
q.`39_Compras`,
q.`39_Cotacao`,
q.`39_Cotacao Online`,
q.`39_Integracao Izi App`,
q.`39_Integracao Mercafacil`,
q.`39_Integracao Cartaz Facil`,
q.`39_Integracao Dattion`,
q.`39_Integracao Codevops`,
q.`SGCONCILIADOR`,
q.`SGCONTABIL`,
q.`15_estacoes`,
q.`SGERP LINUX`,
q.`1_submodulo`,
q.`1_pdvs`,
q.`1_Produtos e Precos`,
q.`1_Fornecedores`,
q.`1_Clientes`,
q.`1_Contas a Pagar`,
q.`1_Contas a Receber`,
q.`1_Resumo de Caixa`,
q.`1_Controle de Loja`,
q.`1_Cartao Ponto`,
q.`1_Contra Vales para Clientes`,
q.`1_M¢dulos de Consulta de Loja`,
q.`1_Faturamento de Vendas`,
q.`1_Cheque Pre Datados`,
q.`1_Inventario Fisico ( Balanco)`,
q.`1_Movimentacao de Produtos`,
q.`1_Entrada de Notas/Calculo de Precos`,
q.`1_Vendas de PDV's/Rentabilidade`,
q.`1_Cotacao de Atacado`,
q.`1_Cheques Devolvidos`,
q.`1_Producao ( Padaria , Acougue)`,
q.`1_Contas Bancarias`,
q.`1_Controle de Despesas`,
q.`1_Controle de Convenios/Ticket/Cartao`,
q.`1_Comissao de Vendedores`,
q.`1_Compras de Ind£strias/Distribuidoras`,
q.`1_Indices Financeiros`,
q.`1_Inventario Fiscal`,
q.`1_Importacao/Exportacao`,
q.`1_Controle de Trocas`,
q.`1_Levantamento Parcial de Estoque`,
q.`1_Movimento de Caixa`,
q.`1_Pesquisa de Precos`,
q.`1_Controle de Verbas`,
q.`1_Transferencia`,
q.`1_Apoio Contabil`,
q.`1_Balanco Setorial`,
q.`1_Controle de Promocoes`,
q.`1_Controle Patrimonial`,
q.`1_Controle de Veiculos`,
q.`1_Escrita Fiscal`,
q.`1_Fidelizacao`,
q.`1_Fluxo de Caixa`,
q.`1_Fechamento de Caixa de Lojas`,
q.`1_Gerenciamento de Gondolas`,
q.`1_Servico de Atendimento ao Cliente`,
q.`1_Consulta de Apoio Gerencial`,
q.`1_Vendas Cooperados/Associados`,
q.`1_Mapa Fiscal`,
q.`1_SGCotacao On-line`,
q.`1_SGPESQ`,
q.`1_AT&M`,
q.`1_Controle Financeiro`,
q.`1_Modulo Gestao`,
q.`1_PAF ECF`,
q.`1_SAT`,
q.`1_Proposta`,
q.`1_Scanntech`,
q.`1_Contribuicao Solidaria`,
q.`1_Conciliacao de cartoes - Conciflex`,
q.`1_Conciliacao de cartoes - Procard`,
q.`1_Atualizacao tributaria - Virtual`,
q.`1_Integracao Cerprosoft Sav`,
q.`1_Conciliacao de cartoes - TeiaCard`,
q.`1_Mix Fiscal`,
q.`1_Integracao NovAmerica`,
q.`1_Integracao Consignet`,
q.`1_PLAY VIEW`,
q.`1_Senha venda prazo - Software Express`,
q.`1_DMCard - Integracao Soumais`,
q.`1_Integracao cartoes Cocalcard`,
q.`1_Conciliacao de cartoes - PJM`,
q.`1_Integracao Mercadex`,
q.`1_Integracao Site Mercado`,
q.`1_Integracao XML SetUP - SGDFE LOCAL`,
q.`1_Integracao XML SetUP - SGDFE GETCARD`,
q.`1_Integracao Fiscal FGF`,
q.`1_Grava Logs Externamente`,
q.`1_Troco Simples`,
q.`1_Emissao de Boletos`,
q.`1_Emissao NFCe Retaguarda`,
q.`1_Integracao SIMPLUS`,
q.`1_Integracao controle de catraca CloudPark`,
q.`1_Integracao Area Central - REDE`,
q.`1_Integracao Area Central - ASSOCIADO`,
q.`1_Controle Flex`,
q.`1_Integracao Alfred`,
q.`1_Integracao WL Assessoria e Contabilidade`,
q.`1_Solucoes Fiscais`,
q.`1_Integracao Cyberlog - WMS`,
q.`1_Integracao Askyn`,
q.`1_Integracao Beblue`,
q.`1_Integracao APPMercados`,
q.`1_Integracao arMHAzena`,
q.`1_Contabilidade - Regras Fiscais`,
q.`1_Integracao LOJAQUI`,
q.`1_Conciliacao de cartoes - VIZZO`,
q.`1_Integracao Nexfood`,
q.`1_Integracao IANDEV`,
q.`1_Integracao KIKKER`,
q.`1_Integracao Amo Delivery`,
q.`1_Integracao Tray`,
q.`1_Integracao Auditto`,
q.`1_Senha PDV por PINPAD - SITEF TUICCS`,
q.`1_Integracao Cresce Vendas`,
q.`1_Integracao NappSync`,
q.`1_Integracao SG SISTEMAS`,
q.`1_Integracao de Associacao (Menu)`,
q.`1_Controle de licitacoes`,
q.`1_Integracao Site Mercado API`,
q.`1_Integracao Compre Facil`,
q.`1_Integracao Insta Buy`,
q.`1_Integracao Deju`,
q.`1_Integracao Cupom Verde`,
q.`1_Integracao Shipay`,
q.`1_Integracao Smart`,
q.`1_Integracao Web Jasper`,
q.`1_Integracao Go Find`,
q.`1_Integracao Dominio XML`,
q.`1_Integracao Matera`,
q.`1_Homologacao Integradores`,
q.`1_Integracao Ideris`,
q.`1_Integracao Minus`,
q.`1_Integracao InfoPrice`,
q.`1_Integracao Supermercado Esperanca`,
q.`1_Integracao PagPix`,
q.`1_Integracao Ad Rocket`,
q.`1_Conciliacao cartoes - Valida Solucoes`,
q.`1_Integracao IMENDES`,
q.`1_Integracao Area Central - API`,
q.`1_Integracao TI Soluti`,
q.`1_Integracao Loja Integrada`,
q.`1_Integracao Izi App`,
q.`1_Integracao Mercafacil`,
q.`1_Integracao Cartaz Facil`,
q.`1_Integracao Dattion`,
q.`1_Integracao Codevops`,
q.`1_Integracao Docerrano`,
q.`1_Integracao Moria Consultoria`,
q.`1_Integracao Simpletask`,
q.`1_Integracao One BI`,
q.`1_ICMS Centralizado`,
q.`1_Integracao Apice`,
q.`1_Integracao Proffer`,
q.`1_Integracao Nexello`,
q.`SGERP WINDOWS`,
q.`2_submodulo`,
q.`2_pdvs`,
q.`2_estacoes`,
q.`2_Produtos e Precos`,
q.`2_Fornecedores`,
q.`2_Clientes`,
q.`2_Contas a Pagar`,
q.`2_Contas a Receber`,
q.`2_Resumo de Caixa`,
q.`2_Controle de Loja`,
q.`2_Contra Vales`,
q.`2_Controle de Vendas`,
q.`2_Controle de Cheques`,
q.`2_Inventario Fisico ( Balanco)`,
q.`2_Movimentacao de Produtos`,
q.`2_Entrada de Notas`,
q.`2_Cotacao de Atacado`,
q.`2_Controle de Producao`,
q.`2_Contas Bancarias`,
q.`2_Controle de Despesas`,
q.`2_Controle de Ticket/Cartao`,
q.`2_Comissoes`,
q.`2_Compras de Ind£strias/Distribuidoras`,
q.`2_Inventario Fiscal`,
q.`2_Controle de Trocas`,
q.`2_Levantamento Parcial de Estoque`,
q.`2_Movimento de Caixa`,
q.`2_Transferencia`,
q.`2_Apoio Contabil`,
q.`2_Escrita Fiscal`,
q.`2_Fidelizacao`,
q.`2_Fluxo de Caixa`,
q.`2_Prestacao de Servico`,
q.`2_Controle Gerencial`,
q.`2_SGCotacao On-line`,
q.`2_SAT`,
q.`2_Scanntech`,
q.`2_Contribuicao Solidaria`,
q.`2_Conciliacao de cartoes - Conciflex`,
q.`2_Mercafacil`,
q.`2_Mix Fiscal`,
q.`2_Integracao NovAmerica`,
q.`2_Integracao Consignet`,
q.`2_PLAY VIEW`,
q.`2_Senha venda prazo - Software Express`,
q.`2_Integracao Site Mercado`,
q.`2_Integracao XML SetUP - SGDFE GETCARD`,
q.`2_Donuz`,
q.`2_Troco Simples`,
q.`2_Emissao de Boletos`,
q.`2_Integracao SIMPLUS`,
q.`2_Integracao Area Central - REDE`,
q.`2_Integracao Area Central - ASSOCIADO`,
q.`2_Controle Flex`,
q.`2_Integracao WL Assessoria e Contabilidade`,
q.`2_Integracao Askyn`,
q.`2_Integracao APPMercados`,
q.`2_Integracao LOJAQUI`,
q.`2_Conciliacao de cartoes - VIZZO`,
q.`2_Integracao RAPPI`,
q.`2_Integracao Nexfood`,
q.`2_Integracao Tray`,
q.`2_Integracao Auditto`,
q.`2_Senha PDV por PINPAD - SITEF TUICCS`,
q.`2_Integracao Cresce Vendas`,
q.`2_Integracao SG SISTEMAS`,
q.`2_Integracao Compre Facil`,
q.`2_Integracao Insta Buy`,
q.`2_Integracao Deju`,
q.`2_Integracao Cupom Verde`,
q.`2_Integracao Shipay`,
q.`2_Integracao Smart`,
q.`2_Integracao Web Jasper`,
q.`2_Integracao Go Find`,
q.`2_Integracao Dominio XML`,
q.`2_Homologacao Integradores`,
q.`2_Integracao Minus`,
q.`2_Integracao Web Jasper API`,
q.`2_Integracao Supermercado Esperanca`,
q.`2_Integracao PagPix`,
q.`2_Integracao Ad Rocket`,
q.`2_Integracao IMENDES`,
q.`2_Integracao Area Central - API`,
q.`2_Integracao TI Soluti`,
q.`2_Integracao Anota Ai`,
q.`2_Integracao Izi App`,
q.`2_Integracao Mercafacil`,
q.`2_Integracao Cartaz Facil`,
q.`2_Integracao Dattion`,
q.`2_Integracao Codevops`,
q.`2_Integracao Docerrano`,
q.`2_Integracao Moria Consultoria`,
q.`2_Integracao Simpletask`,
q.`2_Integracao Apice`,
q.`2_Integracao Proffer`,
q.`SGESTAR`,
q.`SGFOODS`,
q.`3_submodulo`,
q.`3_pdvs`,
q.`3_estacoes`,
q.`3_Produtos e Precos`,
q.`3_Fornecedores`,
q.`3_Clientes`,
q.`3_Contas a Pagar`,
q.`3_Contas a Receber`,
q.`3_Resumo de Caixa`,
q.`3_Controle de Loja`,
q.`3_Controle de Cheques`,
q.`3_Inventario Fisico ( Balanco)`,
q.`3_Movimentacao de Produtos`,
q.`3_Entrada de Notas`,
q.`3_Controle de Producao`,
q.`3_Contas Bancarias`,
q.`3_Controle de Despesas`,
q.`3_Controle de Ticket/Cartao`,
q.`3_Controle de Comissao`,
q.`3_Compras de Ind£strias/Distribuidoras`,
q.`3_Inventario Fiscal`,
q.`3_Levantamento Parcial de Estoque`,
q.`3_Movimento de Caixa`,
q.`3_Transferencia`,
q.`3_Apoio Contabil`,
q.`3_Escrita Fiscal`,
q.`3_Fidelizacao`,
q.`3_Fluxo de Caixa`,
q.`3_Balcao`,
q.`3_Pedidos`,
q.`3_Mesa`,
q.`3_Producao para entrega`,
q.`3_Cartao`,
q.`3_Pre-Pedido`,
q.`3_Controle Gerencial`,
q.`3_SAT`,
q.`3_Autopagamento`,
q.`3_Scanntech`,
q.`3_Autopagamento - Demo`,
q.`3_Contribuicao Solidaria`,
q.`3_Conciliacao de cartoes - Conciflex`,
q.`3_Mix Fiscal`,
q.`3_PLAY VIEW`,
q.`3_Fidelizi`,
q.`3_Integracao Site Mercado`,
q.`3_Integracao XML SetUP - SGDFE GETCARD`,
q.`3_Google Maps`,
q.`3_Donuz`,
q.`3_Troco Simples`,
q.`3_Emissao de Boletos`,
q.`3_Integracao SIMPLUS`,
q.`3_Integracao Area Central - REDE`,
q.`3_Integracao Area Central - ASSOCIADO`,
q.`3_Integracao APPMercados`,
q.`3_Integracao Neemo`,
q.`3_Integracao LOJAQUI`,
q.`3_Integracao IFOOD`,
q.`3_Conciliacao de cartoes - VIZZO`,
q.`3_Integracao RAPPI`,
q.`3_Integracao Nexfood`,
q.`3_Integracao Tray`,
q.`3_Integracao Auditto`,
q.`3_Senha PDV por PINPAD - SITEF TUICCS`,
q.`3_Integracao Cresce Vendas`,
q.`3_Integracao SG SISTEMAS`,
q.`3_Integracao Compre Facil`,
q.`3_Integracao Insta Buy`,
q.`3_Integracao Deju`,
q.`3_Integracao Shipay`,
q.`3_Integracao Smart`,
q.`3_Integracao Web Jasper`,
q.`3_Integracao Go Find`,
q.`3_Integracao Dominio XML`,
q.`3_Homologacao Integradores`,
q.`3_Integracao Minus`,
q.`3_Integracao Supermercado Esperanca`,
q.`3_Integracao PagPix`,
q.`3_Integracao Ad Rocket`,
q.`3_Integracao Area Central - API`,
q.`3_Integracao TI Soluti`,
q.`3_Integracao Anota Ai`,
q.`3_Integracao Izi App`,
q.`3_Integracao Cartaz Facil`,
q.`3_Integracao Dattion`,
q.`3_Integracao Codevops`,
q.`3_Integracao Docerrano`,
q.`3_Integracao Moria Consultoria`,
q.`3_Integracao Simpletask`,
q.`SGFOODS MOBILE`,
q.`19_estacoes`,
q.`SGHOTEL`,
q.`4_submodulo`,
q.`4_estacoes`,
q.`4_Produtos e Precos`,
q.`4_Fornecedores`,
q.`4_Clientes`,
q.`4_Contas a Pagar`,
q.`4_Contas a Receber`,
q.`4_Controle de Cheques`,
q.`4_Movimentacao de Produtos`,
q.`4_Entrada de Notas`,
q.`4_Controle de Producao`,
q.`4_Contas Bancarias`,
q.`4_Controle de Comissao`,
q.`4_Compras de Ind£strias/Distribuidoras`,
q.`4_Inventario Fiscal`,
q.`4_Movimento de Caixa`,
q.`4_Apoio Contabil`,
q.`4_Escrita Fiscal`,
q.`4_Fluxo de Caixa`,
q.`4_Balcao`,
q.`4_Producao para entrega`,
q.`4_Cartao`,
q.`4_Controle Gerencial`,
q.`4_Quartos`,
q.`SGMOBILE`,
q.`5_submodulo`,
q.`5_estacoes`,
q.`SGMODA`,
q.`48_submodulo`,
q.`48_pdvs`,
q.`48_estacoes`,
q.`48_Ordem de Servico`,
q.`48_Contribuicao Solidaria`,
q.`48_Conciliacao de cartoes - Conciflex`,
q.`48_Integracao APPMercados`,
q.`48_Integracao LOJAQUI`,
q.`48_Integracao Tray`,
q.`48_Integracao Cresce Vendas`,
q.`48_Integracao Compre Facil`,
q.`48_Integracao Insta Buy`,
q.`48_Integracao Deju`,
q.`48_DashBoards`,
q.`48_Cadastro de Produtos`,
q.`48_Cadastro de Fornecedores`,
q.`48_Controle Caixa`,
q.`48_Controle de Estoque-Quantidade/Grade/Cor`,
q.`48_Etiquetas`,
q.`48_Entrada de notas por XML`,
q.`48_Crediario`,
q.`48_Controle de Manequim`,
q.`48_Clube de fidelizacao (Pontos)`,
q.`48_Controle de Metas`,
q.`48_Comissao: Por Valor,Produto e Escalonado`,
q.`48_Consignado`,
q.`48_Contas a Pagar`,
q.`48_Contas a Receber`,
q.`48_Cartao Presente`,
q.`48_Venda Ambulante/Sacoleiras`,
q.`48_Promocoes`,
q.`48_Relat¢rios Dinƒmicos`,
q.`48_D.R.E`,
q.`48_Cadastro de Tabela de Precos`,
q.`48_Emissao de Boletos`,
q.`48_PDV OFFLINE`,
q.`48_Alteracoes`,
q.`48_Recibo Avulso`,
q.`48_Vale para Funcionario`,
q.`48_Contrato de Cartao de Credito`,
q.`48_Movimentacao de Cheques`,
q.`48_Nota Avulsa`,
q.`48_Integracao Shipay`,
q.`48_Integracao Smart`,
q.`48_Integracao Web Jasper`,
q.`48_Cadastro de Clientes e Funcionarios`,
q.`48_Emissao de SAT / MFE`,
q.`48_Controle de Trocas`,
q.`48_Devolucoes de venda`,
q.`48_Inventario de Estoque (Parcial ou Total)`,
q.`48_Bancario`,
q.`48_Despesas`,
q.`48_Multilojas - Requisicao/Transferencia`,
q.`48_Gerenciamento`,
q.`48_Catalogo`,
q.`48_Producao`,
q.`48_Fracionamento`,
q.`48_Homologacao Integradores`,
q.`48_Integracao Minus`,
q.`48_Integracao Supermercado Esperanca`,
q.`48_Integracao PagPix`,
q.`48_Integracao Ad Rocket`,
q.`48_Integracao PlugLead`,
q.`48_Integracao Magazord`,
q.`48_Integracao Nuvem Shop`,
q.`48_Integracao Area Central - API`,
q.`48_Integracao Shopify`,
q.`48_Integracao TI Soluti`,
q.`48_Integracao Loja Integrada`,
q.`48_Invetario fiscal`,
q.`48_Escrita fiscal`,
q.`48_Integracao Correios`,
q.`48_Emissao de MDF-e`,
q.`48_Emissao de NFS-e`,
q.`48_Compras`,
q.`48_Cotacao`,
q.`48_Cotacao Online`,
q.`48_Integracao Izi App`,
q.`48_Integracao Mercafacil`,
q.`48_Integracao Cartaz Facil`,
q.`48_Integracao Dattion`,
q.`48_Integracao Codevops`,
q.`SGMONITORAMENTONOTAS`,
q.`SGNFE WINDOWS`,
q.`18_estacoes`,
q.`SGPOCKET`,
q.`6_submodulo`,
q.`6_estacoes`,
q.`TEF`,
q.`12_TEF CLOUD (SITEF - VPN GSURF)`,
q.`12_TEF LOCAL (SCOPE GETCARD)`,
q.`12_TEF CLOUD (SCOPE GETCARD)`,
q.`12_TEF CLOUD (SITEF TEFWAY DIRETO COM INTEGRADOR)`,
q.`12_TEF CLOUD (SITEF SMART DIRETO COM INTEGRADOR)`,
q.`12_TEF SITEF - TEFWAY`,
q.`12_TEF SITEF - OUTROS`,
q.`12_TEF CLOUD (SCOPE GETCARD DIRETO COM INTEGRADOR)`,
q.`12_TEF CLOUD (SITEF - REDE VPN GSURF)`,
q.`12_TEF CLOUD (SITEF)`,
q.`12_TEF CLOUD (SITEF GETCARD DIRETO COM INTEGRADOR)`,
q.`12_TEF CLOUD (SITEF - TLS FISERV)`,
q.`12_TEF CLOUD (SITEF - REDE TLS FISERV)`,
q.`12_TEF CLOUD (SITEF - TLS FISERV - S.E.CONDUCTOR)`,
q.`12_TEF CLOUD (SITEF - S.E.CONDUCTOR)`,
q.`12_TEF REDE (SITEF - TLS FISERV - S.E.CONDUCTOR)`,
q.`12_TEF REDE (SITEF - S.E.CONDUCTOR)`,
q.`TISS`,
