q.`APP CLUBE DE DESCONTO`,
q.`34_Controle de Pontos`,
q.`34_Repasse`,
q.`34_Controle de Cashback`,
q.`34_Controle de Pontos com Oferta por Cashback`,
q.`34_Controle de Ofertas`,
q.`APP PRE VENDA`,
q.`CTE (TECNOSPEED)`,
q.`EMISSAO 1 NFCE CONTINGENCIA`,
q.`FORCA DE VENDA`,
q.`29_ESTACOES`,
q.`FORCA DE VENDAS - HERBIE`,
q.`41_ESTACOES`,
q.`GESTAO IMEDIATA`,
q.`GOMENU`,
q.`46_GOMenu Consulta (QR Code somente para consulta)`,
q.`46_GOMenu Delivery (Delivery)`,
q.`46_GOMenu Mobile (Consulta + pedido pelo celular do c`,
q.`46_GOMenu Pedido (Tablet na mesa)`,
q.`MANAGER SAAS`,
q.`57_NFe`,
q.`57_NFSe`,
q.`57_CTe`,
q.`57_MDFe`,
q.`57_NFCe`,
q.`MDFE (TECNOSPEED)`,
q.`MDFE-FLEXDOCS`,
q.`MOBI POCKET`,
q.`MOBIGESTAO`,
q.`NFCE (TECNOSPEED)`,
q.`NFCE-FLEXDOCS`,
q.`NFE (TECNOSPEED)`,
q.`NFE-FLEXDOCS`,
q.`NFSE (TECNOSPEED)`,
q.`NFSE-FLEXDOCS`,
q.`PORTAL XML`,
q.`R-GOURMET`,
q.`3_SUBMODULO`,
q.`3_PDVs`,
q.`3_ESTACOES`,
q.`3_Produtos e Precos`,
q.`3_Fornecedores`,
q.`3_Clientes`,
q.`3_Contas a Pagar`,
q.`3_Contas a Receber`,
q.`3_Resumo de Caixa`,
q.`3_Controle de Loja`,
q.`3_Controle de Cheques`,
q.`3_Inventario Fisico ( Balanco)`,
q.`3_Movimentacao de Produtos`,
q.`3_Entrada de Notas`,
q.`3_Controle de Producao`,
q.`3_Contas Bancarias`,
q.`3_Controle de Despesas`,
q.`3_Controle de Ticket/Cartao`,
q.`3_Controle de Comissao`,
q.`3_Compras de Industrias/Distribuidoras`,
q.`3_Inventario Fiscal`,
q.`3_Levantamento Parcial de Estoque`,
q.`3_Movimento de Caixa`,
q.`3_Transferencia`,
q.`3_Apoio Contabil`,
q.`3_Escrita Fiscal`,
q.`3_Fidelizacao`,
q.`3_Fluxo de Caixa`,
q.`3_Balcao`,
q.`3_Pedidos`,
q.`3_Mesa`,
q.`3_Producao para entrega`,
q.`3_Cartao`,
q.`3_Pre-Pedido`,
q.`3_Controle Gerencial`,
q.`3_SAT`,
q.`3_Autopagamento`,
q.`3_Scanntech`,
q.`3_Autopagamento - Demo`,
q.`3_Contribuicao Solidaria`,
q.`3_Conciliacao de cartoes - Conciflex`,
q.`3_Mix Fiscal`,
q.`3_PLAY VIEW`,
q.`3_Fidelizi`,
q.`3_Integracao Site Mercado`,
q.`3_Integracao XML SetUP - SGDFE GETCARD`,
q.`3_Google Maps`,
q.`3_Donuz`,
q.`3_Troco Simples`,
q.`3_Emissao de Boletos`,
q.`3_Integracao SIMPLUS`,
q.`3_Integracao Area Central - REDE`,
q.`3_Integracao Area Central - ASSOCIADO`,
q.`3_Integracao Neemo`,
q.`3_Integracao IFOOD`,
q.`3_Conciliacao de cartoes - VIZZO`,
q.`3_Integracao RAPPI`,
q.`3_Integracao Nexfood`,
q.`3_Integracao Tray`,
q.`3_Integracao Auditto`,
q.`3_Senha PDV por PINPAD - SITEF TUICCS`,
q.`3_Integracao Cresce Vendas`,
q.`3_Integracao SG SISTEMAS`,
q.`3_Integracao Shipay`,
q.`3_Integracao Dominio XML`,
q.`3_Integracao PagPix`,
q.`3_Integracao Anota Ai`,
q.`RJK-PDV`,
q.`2_SUBMODULO`,
q.`2_PDVs`,
q.`2_ESTACOES`,
q.`2_Produtos e Precos`,
q.`2_Fornecedores`,
q.`2_Clientes`,
q.`2_Contas a Pagar`,
q.`2_Contas a Receber`,
q.`2_Resumo de Caixa`,
q.`2_Controle de Loja`,
q.`2_Contra Vales`,
q.`2_Controle de Vendas`,
q.`2_Controle de Cheques`,
q.`2_Inventario Fisico ( Balanco)`,
q.`2_Movimentacao de Produtos`,
q.`2_Entrada de Notas`,
q.`2_Cotacao de Atacado`,
q.`2_Controle de Producao`,
q.`2_Contas Bancarias`,
q.`2_Controle de Despesas`,
q.`2_Controle de Ticket/Cartao`,
q.`2_Comissoes`,
q.`2_Compras de Industrias/Distribuidoras`,
q.`2_Inventario Fiscal`,
q.`2_Controle de Trocas`,
q.`2_Levantamento Parcial de Estoque`,
q.`2_Movimento de Caixa`,
q.`2_Transferencia`,
q.`2_Apoio Contabil`,
q.`2_Escrita Fiscal`,
q.`2_Fidelizacao`,
q.`2_Fluxo de Caixa`,
q.`2_Prestacao de Servico`,
q.`2_Controle Gerencial`,
q.`2_SGCotacao On-line`,
q.`2_SAT`,
q.`2_Scanntech`,
q.`2_Contribuicao Solidaria`,
q.`2_Conciliacao de cartoes - Conciflex`,
q.`2_Mercafacil`,
q.`2_Mix Fiscal`,
q.`2_Integracao NovAmerica`,
q.`2_Integracao Consignet`,
q.`2_PLAY VIEW`,
q.`2_Senha venda prazo - Software Express`,
q.`2_Integracao Site Mercado`,
q.`2_Integracao XML SetUP - SGDFE GETCARD`,
q.`2_Donuz`,
q.`2_Troco Simples`,
q.`2_Emissao de Boletos`,
q.`2_Integracao SIMPLUS`,
q.`2_Integracao Area Central - REDE`,
q.`2_Integracao Area Central - ASSOCIADO`,
q.`2_Controle Flex`,
q.`2_Integracao WL Assessoria e Contabilidade`,
q.`2_Integracao Askyn`,
q.`2_Integracao APPMercados`,
q.`2_Integracao LOJAQUI`,
q.`2_Conciliacao de cartoes - VIZZO`,
q.`2_Integracao RAPPI`,
q.`2_Integracao Nexfood`,
q.`2_Integracao Tray`,
q.`2_Integracao Auditto`,
q.`2_Senha PDV por PINPAD - SITEF TUICCS`,
q.`2_Integracao Cresce Vendas`,
q.`2_Integracao SG SISTEMAS`,
q.`2_Integracao Compre Facil`,
q.`2_Integracao Insta Buy`,
q.`2_Integracao Deju`,
q.`2_Integracao Cupom Verde`,
q.`2_Integracao Shipay`,
q.`2_Integracao Dominio XML`,
q.`2_Integracao Web Jasper API`,
q.`2_Integracao PagPix`,
q.`2_Integracao IMENDES`,
q.`2_Integracao Mercafacil`,
q.`SELF-CHECKOUT`,
q.`38_PDVs`,
q.`SG CARTAZ`,
q.`SG VIEW`,
q.`SG-NFCE`,
q.`22_SGDFE SG GETCARD`,
q.`SG-NFE`,
q.`21_SGDFE SG GETCARD`,
q.`SGBI`,
q.`SGCLOUD`,
q.`39_SUBMODULO`,
q.`39_PDVs`,
q.`39_ESTACOES`,
q.`39_Ordem de Servico`,
q.`39_Contribuicao Solidaria`,
q.`39_Conciliacao de cartoes - Conciflex`,
q.`39_Integracao APPMercados`,
q.`39_Integracao LOJAQUI`,
q.`39_Integracao Tray`,
q.`39_Integracao Cresce Vendas`,
q.`39_Integracao Compre Facil`,
q.`39_Integracao Insta Buy`,
q.`39_Integracao Deju`,
q.`39_DashBoards`,
q.`39_Cadastro de Produtos`,
q.`39_Cadastro de Fornecedores`,
q.`39_Controle Caixa`,
q.`39_Controle de Estoque-Quantidade/Grade/Cor`,
q.`39_Etiquetas`,
q.`39_Entrada de notas por XML`,
q.`39_Crediario`,
q.`39_Controle de Manequim`,
q.`39_Clube de fidelizacao (Pontos)`,
q.`39_Controle de Metas`,
q.`39_Comissao: Por Valor,Produto e Escalonado`,
q.`39_Consignado`,
q.`39_Contas a Pagar`,
q.`39_Contas a Receber`,
q.`39_Cartao Presente`,
q.`39_Venda Ambulante/Sacoleiras`,
q.`39_Promocoes`,
q.`39_Relatorios Dinamicos`,
q.`39_D.R.E`,
q.`39_Cadastro de Tabela de Precos`,
q.`39_Emissao de Boletos`,
q.`39_PDV OFFLINE`,
q.`39_Alteracoes`,
q.`39_Recibo Avulso`,
q.`39_Vale para Funcionario`,
q.`39_Contrato de Cartao de Credito`,
q.`39_Movimentacao de Cheques`,
q.`39_Nota Avulsa`,
q.`39_Integracao Shipay`,
q.`39_Integracao Smart`,
q.`39_Integracao Web Jasper`,
q.`39_Cadastro de Clientes e Funcionarios`,
q.`39_Emissao de SAT / MFE`,
q.`39_Controle de Trocas`,
q.`39_Devolucoes de venda`,
q.`39_Inventario de Estoque (Parcial ou Total)`,
q.`39_Bancario`,
q.`39_Despesas`,
q.`39_Multilojas - Requisicao/Transferencia`,
q.`39_Gerenciamento`,
q.`39_Catalogo`,
q.`39_Producao`,
q.`39_Fracionamento`,
q.`39_Homologacao Integradores`,
q.`39_Integracao Minus`,
q.`39_Integracao Supermercado Esperanca`,
q.`39_Integracao PagPix`,
q.`39_Integracao Ad Rocket`,
q.`39_Integracao PlugLead`,
q.`39_Integracao Magazord`,
q.`39_Integracao Nuvem Shop`,
q.`39_Integracao Area Central - API`,
q.`39_Integracao Shopify`,
q.`39_Integracao TI Soluti`,
q.`39_Integracao Loja Integrada`,
q.`39_Inventario fiscal`,
q.`39_Escrita fiscal`,
q.`39_Integracao Correios`,
q.`39_Emissao de MDF-e`,
q.`39_Emissao de NFS-e`,
q.`39_Compras`,
q.`39_Cotacao`,
q.`39_Cotacao Online`,
q.`39_Integracao Izi App`,
q.`39_Integracao Cartaz Facil`,
q.`39_Integracao Dattion`,
q.`39_Integracao Codevops`,
q.`SGERP LINUX`,
q.`1_SUBMODULO`,
q.`1_PDVs`,
q.`1_Produtos e Precos`,
q.`1_Fornecedores`,
q.`1_Clientes`,
q.`1_Contas a Pagar`,
q.`1_Contas a Receber`,
q.`1_Resumo de Caixa`,
q.`1_Controle de Loja`,
q.`1_Cartao Ponto`,
q.`1_Contra Vales para Clientes`,
q.`1_Modulos de Consulta de Loja`,
q.`1_Faturamento de Vendas`,
q.`1_Cheque Pre Datados`,
q.`1_Inventario Fisico ( Balanco)`,
q.`1_Movimentacao de Produtos`,
q.`1_Entrada de Notas/Calculo de Precos`,
q.`1_Vendas de PDV's/Rentabilidade`,
q.`1_Cotacao de Atacado`,
q.`1_Cheques Devolvidos`,
q.`1_Producao ( Padaria , Acougue)`,
q.`1_Contas Bancarias`,
q.`1_Controle de Despesas`,
q.`1_Controle de Convenios/Ticket/Cartao`,
q.`1_Comissao de Vendedores`,
q.`1_Compras de Industrias/Distribuidoras`,
q.`1_Indices Financeiros`,
q.`1_Inventario Fiscal`,
q.`1_Importacao/Exportacao`,
q.`1_Controle de Trocas`,
q.`1_Levantamento Parcial de Estoque`,
q.`1_Movimento de Caixa`,
q.`1_Pesquisa de Precos`,
q.`1_Controle de Verbas`,
q.`1_Transferencia`,
q.`1_Apoio Contabil`,
q.`1_Balanco Setorial`,
q.`1_Controle de Promocoes`,
q.`1_Controle Patrimonial`,
q.`1_Controle de Veiculos`,
q.`1_Escrita Fiscal`,
q.`1_Fidelizacao`,
q.`1_Fluxo de Caixa`,
q.`1_Fechamento de Caixa de Lojas`,
q.`1_Gerenciamento de Gondolas`,
q.`1_Servico de Atendimento ao Cliente`,
q.`1_Consulta de Apoio Gerencial`,
q.`1_Vendas Cooperados/Associados`,
q.`1_Mapa Fiscal`,
q.`1_SGCotacao On-line`,
q.`1_SGPESQ`,
q.`1_AT&M`,
q.`1_Controle Financeiro`,
q.`1_Modulo Gestao`,
q.`1_PAF ECF`,
q.`1_SAT`,
q.`1_Proposta`,
q.`1_Scanntech`,
q.`1_Contribuicao Solidaria`,
q.`1_Conciliacao de cartoes - Conciflex`,
q.`1_Conciliacao de cartoes - Procard`,
q.`1_Atualizacao tributaria - Virtual`,
q.`1_Integracao Cerprosoft Sav`,
q.`1_Conciliacao de cartoes - TeiaCard`,
q.`1_Mix Fiscal`,
q.`1_Integracao NovAmerica`,
q.`1_Integracao Consignet`,
q.`1_PLAY VIEW`,
q.`1_Senha venda prazo - Software Express`,
q.`1_DMCard - Integracao Soumais`,
q.`1_Integracao cartoes Cocalcard`,
q.`1_Conciliacao de cartoes - PJM`,
q.`1_Integracao Mercadex`,
q.`1_Integracao Site Mercado`,
q.`1_Integracao XML SetUP - SGDFE LOCAL`,
q.`1_Integracao XML SetUP - SGDFE GETCARD`,
q.`1_Integracao Fiscal FGF`,
q.`1_Grava Logs Externamente`,
q.`1_Troco Simples`,
q.`1_Emissao de Boletos`,
q.`1_Emissao NFCe Retaguarda`,
q.`1_Integracao SIMPLUS`,
q.`1_Integracao controle de catraca CloudPark`,
q.`1_Integracao Area Central - REDE`,
q.`1_Integracao Area Central - ASSOCIADO`,
q.`1_Controle Flex`,
q.`1_Integracao Alfred`,
q.`1_Integracao WL Assessoria e Contabilidade`,
q.`1_Solucoes Fiscais`,
q.`1_Integracao Cyberlog - WMS`,
q.`1_Integracao Askyn`,
q.`1_Integracao Beblue`,
q.`1_Integracao APPMercados`,
q.`1_Integracao arMHAzena`,
q.`1_Contabilidade - Regras Fiscais`,
q.`1_Integracao LOJAQUI`,
q.`1_Conciliacao de cartoes - VIZZO`,
q.`1_Integracao Nexfood`,
q.`1_Integracao IANDEV`,
q.`1_Integracao KIKKER`,
q.`1_Integracao Amo Delivery`,
q.`1_Integracao Tray`,
q.`1_Integracao Auditto`,
q.`1_Senha PDV por PINPAD - SITEF TUICCS`,
q.`1_Integracao Cresce Vendas`,
q.`1_Integracao NappSync`,
q.`1_Integracao SG SISTEMAS`,
q.`1_Integracao de Associacao (Menu)`,
q.`1_Controle de licitacoes`,
q.`1_Integracao Site Mercado API`,
q.`1_Integracao Compre Facil`,
q.`1_Integracao Insta Buy`,
q.`1_Integracao Deju`,
q.`1_Integracao Cupom Verde`,
q.`1_Integracao Shipay`,
q.`1_Integracao Smart`,
q.`1_Integracao Web Jasper`,
q.`1_Integracao Go Find`,
q.`1_Integracao Dominio XML`,
q.`1_Integracao Matera`,
q.`1_Homologacao Integradores`,
q.`1_Integracao Ideris`,
q.`1_Integracao Minus`,
q.`1_Integracao InfoPrice`,
q.`1_Integracao Supermercado Esperanca`,
q.`1_Integracao PagPix`,
q.`1_Integracao Ad Rocket`,
q.`1_Conciliacao cartoes - Valida Solucoes`,
q.`1_Integracao IMENDES`,
q.`1_Integracao Area Central - API`,
q.`1_Integracao TI Soluti`,
q.`1_Integracao Loja Integrada`,
q.`1_Integracao Izi App`,
q.`1_Integracao Mercafacil`,
q.`1_Integracao Cartaz Facil`,
q.`1_Integracao Dattion`,
q.`1_Integracao Codevops`,
q.`1_Integracao Docerrano`,
q.`1_Integracao Moria Consultoria`,
q.`1_Integracao Simpletask`,
q.`SGFOODS MOBILE`,
q.`19_ESTACOES`,
q.`SGMOBILE`,
q.`5_ESTACOES`,
q.`SGMONITORAMENTONOTAS`,
q.`SGNFE WINDOWS`,
q.`SGPOCKET`,
q.`6_ESTACOES`,
q.`TEF`,
q.`12_TEF SITEF - VPN GSURF`,
q.`12_TEF SCOPE ITAUTEC LOCAL`,
q.`12_TEF SCOPE ITAUTEC GETCARD`,
q.`12_TEFWAY`,
q.`12_TEF SMART`,
q.`12_TEF SITEF - TEFWAY`,
q.`12_TEF SITEF - OUTROS`,
q.`12_TEF SCOPE INTEGRACAO GETCARD`,
q.`12_TEF REDE (SITEF)`,
q.`12_TEF CLOUD (SITEF)`,
q.`12_TEF CLOUD GETCARD (SITEF)`,
q.`12_TEF CLOUD (SITEF) - CNPJ SG`,
q.`12_TEF CLOUD GETCARD (SITEF) - CNPJ SG`,
q.`12_TEF CLOUD (SITEF - TLS FISERV)`,
q.`12_TEF REDE (SITEF - TLS FISERV)`,
q.`12_TEF CLOUD (SITEF - TLS FISERV - S.E.CONDUCTOR)`,
q.`12_TEF CLOUD (SITEF - S.E.CONDUCTOR)`,
q.`12_TEF REDE (SITEF - TLS FISERV - S.E.CONDUCTOR)`,
q.`12_TEF REDE (SITEF - S.E.CONDUCTOR)`,
q.`TISS`,
